### ISSUE TITLE
New system for obstacle generation from motion constraints

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1010]
### Description of the task
Currently obstacle generation is under navigator util. We can put that in the navigator/obstacle folder instead

Please consult @jonathanlew @garethellis0 and @MathewMacDougall on how this should look

### Acceptance criteria

- [ ] move obstacle generation functions from util.{cpp,h} to obstacle_generation.{cpp,h}
- [ ] tests

### Blocked By
#812 #944

**Comment by garethellis0** [comment]
Could we please be more specific with the "Acceptance Criteria" for this? These criteria should provide a clear set of things to need to be resolved, like "move obstacle generation functions from `util.{cpp,h}` to `obstacle_generation.{cpp,h}`. Please keep in mind that these tickets can be taken by new members with minimal context, and the more information we put here, the less time we spend explaining and the less time they have to spend asking.

**Comment by jonathanlew** [comment]
Yup I made as a placeholder since we should think higher level about how the obstacle generation/factory all works together

**Comment by jonathanlew** [comment]
Done by #1013
