### ISSUE TITLE
Draw obstacles with the visualizer

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1022]
### Description of the task
Navigator passes obstacles to PathManager, who then passes it to the PathPlanner to path plan. Since path planning is done around obstacles, we want to see what the path planner is trying to avoid. We want to visualize the perimeter of all the obstacles in the visualizer. It's OK for all obstacles to have the same colour overlap on top of each other.

### Acceptance criteria

- [ ] Visualize all obstacles
- [ ] Visual inspection

**Comment by hardik-ddod** [comment]
@jonathanlew Do we have a dummy game scenario on which I could try running the current visualizer on my computer right now?

**Comment by MathewMacDougall** [comment]
@hardik-ddod you can use `grsim` for that. [The docs](https://github.com/UBC-Thunderbots/Software/blob/master/docs/getting-started.md#installing-grsim) explain how to install it. Then you can just run `grsim` from a terminal and it should open.

Then just build and run the `//software:full_system` target with the `--backend grsim` flag.

So the full command might look like `bazel run //software:full_system -- --backend grsim`, run from the `Software/src` folder.

**Comment by hardik-ddod** [comment]
@MathewMacDougall TY papa leader!

**Comment by jonathanlew** [comment]
yeah I synced up with hardik offline, but thanks

**Comment by garethellis0** [comment]
@hardik-ddod - where's this at right now?

**Comment by hardik-ddod** [comment]
@garethellis0 I am still trying to understand how everything works... not much work is done on this one...

**Comment by garethellis0** [comment]
OK, could you please unassign yourself from this ticket until https://github.com/UBC-Thunderbots/Software/pull/1049 gets merged? Then Mathew M. would be the person to talk to about this.
