### ISSUE TITLE
Add A "Valgrind" Executable As A Runnable Bazel Target

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1035]
### Description of the task
The current version of valgrind on ubuntu 18 is `3.13`. However it appears that the version of clang we are using outputs debug targets with a format that valgrind `3.13` cannot read. Version `3.15` appears to work just fine. 

We want the ability to run valgrind via `bazel run //tools:valgrind` (or similar) so that we know the version of valgrind we're using will always be correct. This will likely entail building valgrind from source, the downloads for which can be found here: http://valgrind.org/downloads/

Alternatively, we could consider setting up the new version of valgrind as part of the `setup_software` script. This would reduce build times for commands like `bazel build //...`, because we wouldn't have to rebuild valgrind, however it wouldn't speed CI up much, since CI needs to run `setup_software.sh` anyways.

### Acceptance criteria

- [ ] Decide between setting up valgrind as a bazel target or as part of `setup_software.sh`
- [ ] Implement the chosen method.

**Comment by henryymliu** [comment]
We can use the `snap` version of valgrind (https://snapcraft.io/valgrind), it works on all distributions of Linux that support `snap`.

**Comment by MathewMacDougall** [comment]
Can you freeze the version of a `snap` package? The issue might be that it could auto-update on someone's machine and break

**Comment by henryymliu** [comment]
Not in ubuntu right now, but `sudo snap install valgrind --channel=stable/3.15.0 --classic` might work?
I also can't remember if Ubuntu has snap enabled by default, or if one has to `apt install snapd` first

**Comment by garethellis0** [comment]
I think `sudo snap install valgrind --channel=stable --classic` should be fine, we really don't need to peg the version. I also had to run `sudo apt remove valgrind` to remove the version installed by apt-get (really it just depends which executable it hits first in the path).
