### ISSUE TITLE
Investigate Using std::atomic Across The Codebase

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1072]
### Description of the task
[std::atomic](https://en.cppreference.com/w/cpp/atomic/atomic) provides a wrapper to make objects thread-safe. There are many places in the codebase, like in the `PassGenerator` and in several `MultithreadedObserver` classes, that we have locks for a single piece of data. We could likely just replace many of these locks with instances of `std::atomic`. 

The difficulty here is understanding when it is / is not appropriate to use `std::atomic`, as there are places where the locks are blocking for specific sections of code, not just single accesses.

### Acceptance criteria

- [ ] Find all locations in the repo that could benefit from this
- [ ] Either change all locations if it's not too much work, or file tickets to change all the locations

**Comment by garethellis0** [comment]
Closing this because it provides _much_ less benefit then many other tickets, and so is unlikely to be completed this year. @MathewMacDougall - please feel free to re-open if you disagree!

**Comment by MathewMacDougall** [comment]
No need to re-open as you didn't close it :stuck_out_tongue: . I'd say leave it open for now since it should be a pretty quick fix in only a few places should we choose to address it, although I agree it's lower value.

**Comment by jonathanlew** [comment]
std::atomic can only be used on trivially copyable functions and only guarantee sequentially consistency on multiple operations https://stackoverflow.com/questions/31978324/what-exactly-is-stdatomic, so they aren't appropriate for most of our code base where we have "transactions" that we want to happen atomically

**Comment by MathewMacDougall** [comment]
Yea I'd be fine closing this since there's not a ton of value of trying to convert everything we can just to use `atomic`.
