### ISSUE TITLE
Document the Simulated Tests structure and assumptions

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1080]
### Description of the task

We need to document the new structure and changes introduced in #1067 . This includes how the WorldStateValidator fits in to the structure and how the SimulatedTests fixture is set up (including timing between components).

### Acceptance criteria

- [ ] Add documentation

**Comment by MathewMacDougall** [comment]
@garethellis0 Thoughts on if this documentation should go in-code or in the markdown? A bit of both?

High-level structure for testing makes sense to go in markdown, but I'm not sure how much of the "assumptions made" stuff should go in markdown, since it's more tied to the implementation and _could_ change. Although the basic assumptions about timing / waiting on values are pretty generic so probably would be fine in markdown.

@jonathanlew @akhilveeraghanta FYI

**Comment by garethellis0** [comment]
I think the cutoff should be that if you're talking about more then one class, that should go in the markdown, but not super strongly set on this.
