### ISSUE TITLE
Visualizer: Make sure AI Control widgets are updated when parameters change

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1090]
### Description of the task

Right now not all widgets in the `AI Control` tab are bound to their respective parameter callbacks, so they will not be immediately updated if something else changes the parameter value. These widgets should be connected to their corresponding parameter callbacks. There are many examples in the code that can be followed / copied, like the other widgets in the `AI Control` tab or the ones in the `Parameter` tab.

### Acceptance criteria

- [ ] Check for any widgets that are not connected to their parameter callback
- [ ] Connect the AI Control widgets to their parameter callbacks

**Comment by jonathanlew** [comment]
@akhilveeraghanta How does this fit into the new dynamic params?

**Comment by MathewMacDougall** [comment]
No difference between old and new. It should just be a matter of connecting callback functions (which both the old and new versions have).

**Comment by MathewMacDougall** [comment]
It's just that there may be params not connected to their respective DyanmicParam _at all_

**Comment by jonathanlew** [comment]
new visualizer incoming
