### ISSUE TITLE
Visualizer: Enable and disable drawing components

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1091]
### Description of the task

Users should be able to toggle what is drawn in the Visualizer at runtime. For example, they may want to enable drawing navigation obstacles for debugging, but disable them later so the view isn't crowded.

Indicating what things should be drawn would likely be handled by the DynamicParameter system. We could create a new config file for these "GUI drawing" parameters.

This config would likely then be passed to the functions that create the `DrawFunctions` that are given to the GUI. Using the parameters, the `DrawFunctions` can selectively be built up depending on what the user wants to be shown.

This is kind of like Google Map layers
### Acceptance criteria

- [ ] Allow users to toggle what is drawn in the world view

**Comment by akhilveeraghanta** [comment]
Decided to not do because we are visualizing stuff in the jupyter notebook, will re-open if more layers are added

**Comment by MathewMacDougall** [comment]
Agree, this is probably unneeded complexity at this point.
