### ISSUE TITLE
Geom: Refactor `Segment` to fit New Geometry hierarchy

### ISSUE THREAD

**Issue by scveloso** [UBC-Thunderbots/Software#1098]
### Description of the task
Segment should be refactored to fit the new classes and hierarchy in ```new_geom```. Currently, the ```segment.h``` in ```new_geom``` is a direct copy of the one in the old geom directory and should be refactored. Possible refactoring is to have line segment inherit from spline.
 

### Acceptance criteria

- [ ] Refactor ```segment``` such that it fits in the new geometry hierarchy.
- [ ] Unit tests for any new logic / previously untested logic

### Blocked by:
#983 Segment may inherit Spline in the new geometry hierarchy

**Comment by jonathanlew** [comment]
The goal of this issue going forward is to build off of https://github.com/UBC-Thunderbots/Software/pull/1456, namely the midpoint, length, getsegstart, forbidding degenerate construction, and separation into .h and .cpp files changes. However, it should _not_ include changes to `Point`, or moving collinear, intersects or distance
