### ISSUE TITLE
Geom: Improve ConvexPolygon::isConvex()

### ISSUE THREAD

**Issue by scveloso** [UBC-Thunderbots/Software#1140]
### Description of the task
We can improve ```ConvexPolygon::isConvex()``` by either:
- Implement the Bentley-Ottoman algorithm to determine if a set of segments are self intersecting (violates convex property)
- Implementing the following pseudocode once ```new_geom/intersects``` no longer depends on old geom
```
1. abs(each corner) is < 180 deg
2. All angles are either greater or less then zero (depending if points are given in CW or CCW order) ( do we have tests for CW and CCW?)
3. The polygon is not self-intersecting (this effectively replaces the final check):
for (Edge e1 : edges){
     for (Edge e2 : edges){
        if (intersects(e1, e2))  {
             return true
        }
    }
}
return false;
```

Currently, the ```isConvex()``` method calculates total angle of polygon corner's but we want to improve this as some valid convex polygons barely considered as not convex. 

### Acceptance criteria
One of:
- [ ] Change ```isConvex()``` to Bentley-Ottman Algorithm
- [ ] Change ```isConvex()``` to above implementation of pseudocode
And:
- [ ] Unit tests for either approach above

### Blocked By
- #1098

**Comment by garethellis0** [comment]
A lot of the issues with the current implementation come from the fact that we are summing the results of `n` floating point calculations and then comparing to `360` (or `2*pi`) and so accumulation of floating point error can make the function return incorrect results.
