### ISSUE TITLE
Refactor Ball Filter

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1141]
### Description of the task

The Ball Filter still has a few large functions, and could use some minor re-structuring for readability.
* The publicly exposed function should be `estimateBallState` or `getEstimatedBallState` since this is more descriptive than `getFilteredData`
* The new `getEstimatedBallState` function can probably be broken down better into smaller functions without so many edge cases.

### Acceptance criteria

- [ ] Refactor ball filter
- [ ] Make sure tests still pass

### Blocked By
#1135

**Comment by jonathanlew** [comment]
Are there additional areas in ball filter that can be refactored?

**Comment by MathewMacDougall** [comment]
Nothing major comes to mind, mostly just breaking up a few large functions like I mentioned above. Also most of the functions should be made private.

**Comment by kelvinkoon** [comment]
There is already a function in `ball_filter.cpp` called `estimateBallState`. I assume this ticket is about the `getFilteredData` function, renaming it to something like `getFilteredBall`, and breaking the function / cleaning it up.
Or is the ticket about the entire `BallFilter` class and its respective functions?

**Comment by MathewMacDougall** [comment]
It was generally about the whole thing. `estimateBallState` is the only function that really needs to be public, which on it's own is _slightly_ large and could probably be refactored along with other functions to be simpler. This definitely doesn't have to be a high-priority ticket.
