### ISSUE TITLE
Update GenericFactory To Use A Function To Get The Index, Rather Then A Variable

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1142]
### Description of the task
Currently, the `GenericFactory` class relies on all classes that use it have a `static` variable called `name`. We should have those classes implement `static IndexType getFactoryIndex()` where `IndexType` is a template parameter to the `GenericFactory` class.

So for most existing classes this would likely be `std::string getFactoryIndex()`, but for future classes maybe it's something like `int getFactoryIndex()` if we want to lookup a class from an `int`. Or maybe classes could implement both, so we could register them in factories to be looked up from a `std::string` or an `int`. 

### Acceptance criteria

- [ ] Update `TGenericFactory` to register a class based on the index obtained from a function `IndexType getIndexFunction. So instead of ` GenericFactory<IndexType, TypeToCreate>::registerCreator(T::name, generic_creator);`, it would be something like ` GenericFactory<IndexType, TypeToCreate>::registerCreator(T::getFactoryIndex, generic_creator);`
- [ ] Update all users of the `GenericFactory` to implement this method instead of exposing `name` as a static variable

### Blocked By
#762

**Comment by jonathanlew** [comment]
with the TYPENAME(T) change, this is redundant
