### ISSUE TITLE
Create "ball chip angle of departure" constant for robots

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1179]
### Description of the task

Different robots may chip differently if the ball leave the chipper at a different angle. We should make this a Robot constant.

For the current (3rd) generation of robots, this value may need to be determined experimentally.

### Acceptance criteria

- [ ] Determine and create a "ball chip angle of departure" robot constant

**Comment by jonathanlew** [comment]
Confirmed from mech that it's 45 degrees
