### ISSUE TITLE
Update values for robot linear damping in simulation once new controller implemented

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1187]
### Description of the task

Our current bang-bang controller is very nearly an open-loop control algorithm. It essentially assumes that the force it applies to the robot's wheels is "what it expects", and the controller gain and other constants have been tuned for on-field performance. As a result, robots tend to overshoot their destinations in our simulator.

In order to compensate for this, we have increased the values for linear and angular robot damping in the simulation, to a point where the robots will not significantly overshoot their destinations.

One the new PID / Spline controller is implemented by @EvanMorcom , we should have a proper control algorithm with feedback that should be more robust to these damping constants (or we'll know better values to approximate specific robot dynamics used in the model for control).

The values to change are `robot_linear_damping` and `robot_angular_damping` in `physics_robot.h`. Their original values were `0.2`, and were somewhat arbitrary. The values should be returned to something reasonable near that value.

### Acceptance criteria

- [ ] Revert the damping constants for the robot in our simulator

### Blocked By

This is blocked until the new PID / Spline controller are done, but there are currently no tickets for them. Ask @EvanMorcom or @MathewMacDougall if you are unsure if this ticket is still blocked.

**Comment by jonathanlew** [comment]
new er force sim + new motion planning so closing
