### ISSUE TITLE
Create Documentation For CubeMX Choices

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1192]
### Description of the task
We have made a bunch of decisions about settings in `CubeMx` that we can't leave comments on directly because they end up in auto-generated files. We should document all these choices, probably in a markdown file.

### Acceptance criteria

- [ ] Figure out which doc to put this in, or add a new doc if _absolutely_ neccesary (but really, try to avoid this)
- [ ] Fill out existing or new doc with explanations of major decisions made in CubeMX and why they were made. Format appropriately.

**Comment by akhilveeraghanta** [comment]
No longer using CubeMX
