### ISSUE TITLE
Convert Radio System to Protobuf

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1216]
### Description of the task

Our current radio system uses a custom packing system which is efficient but difficult to maintain and update as we move into the new firmware.

As part of this ticket, that protocol will need to be replaced w/ protobuf. And the necessary firmware changes on the dongle/robot and the software changes need to be field tested.

After some discussion, we decided the new packing will be as follows
`| robot id | protobuf payload | estop | `

- the robot will only de-serialize the data if the data is meant for it
- the estop is outside of the payload so that if a robot goes out of vision, it still receives the estop bit

### Acceptance criteria

- [ ] Transition old firmware to use protobuf
- [ ] Implement round robin to send packets over
- [ ] Lot of field testing
- [ ] Nuke unused code
- [ ] Define protobuf that will replace existing system

### Blocked By
N/A

**Comment by jonathanlew** [comment]
With the new sensor fusion design #1135, we've decided that we won't convert radio to protobuf immediately since we can wrap the annunciator/mrf in a radio backend and output SensorProto. I would hold off on this for now

**Comment by akhilveeraghanta** [comment]
This is only for `TbotsRobotMsg`, the `TbotsMsg` would still need to be proto or custom packing for any new data we choose to send.
