### ISSUE TITLE
Setup ThreadedObserver and Buffers Structure in Robot Diagnostics

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1229]
### Description of the task
Setup ThreadedObserver and Buffers structure in Robot Diagnostics. Currently Robot Diagnostics has stubs for communicating with the robot and the feedback area is undeveloped. Before we can handle communication, we need to first set up a structure for communicating data between the main thread and the gui thread. In addition, we need to make RobotDiagnostics an `Observer` of `SensorMsg` so it can get its data directly from `Backend` 

### Acceptance criteria

- [ ] Setup ThreadedObserver and Buffers structure in Robot Diagnostics
- [ ] Add more structure

### Blocked By
#1227 #1228

**Comment by garethellis0** [comment]
Should this be blocked on #1228 as well?
