### ISSUE TITLE
Remove old arm toolchain from firmware setup script

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1246]
### Description of the task

We no longer use the arm toolchain that is downloaded in the `setup_firmware.sh` script (we now use one installed with bazel), so it can be removed from the setup script. While we're there, we should try remove anything else unused from the firmware setup script.

### Acceptance criteria

- [ ] Remove the arm toolchain setup from the setup firmware script

**Comment by jonathanlew** [comment]
resolved by #1247
