### ISSUE TITLE
Move primitives folder up one level

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1269]
### Description of the task

We generally try put directories / code at the highest level at which they are used. ie. files should only be used by other files at the same level, or in a subdirectory.

I'm proposing we move the Primitives folder up one level from `software/ai/primitives` to `software/primitives`, because they are used by the `ai`, the backends, and soon-to-be simulator, and in that sense are not a concept purely contained in the AI ( like `Intents` for example)

### Acceptance criteria

- [ ] Move `software/ai/primitives` to `software/primitives`

**Comment by jonathanlew** [comment]
Resolved by #1270
