### ISSUE TITLE
Create TbotsSoftwareMsg Proto for Robot Diagnostics

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1273]
### Description of the task
Currently, primitives are sent in custom encoded packets over radio the robots. The new TbotsSoftwareMsg Proto will use the Protobuf encoding and standardize this packet for the old and new robots. The new proto design will need to be able to send the primitives used by RobotDiagnostics, such as DirectVelocity, DirectWheel, dribbling, kicking, chipping.

### Acceptance criteria

- [ ] Develop structure for Tbots_SoftwareMsg Proto
- [ ] Add enough primitives for RobotDiagnostics to do its job

**Comment by akhilveeraghanta** [comment]
Will be done as part of #1386, including vision and the rest of the primitives
