### ISSUE TITLE
Add fields to Robot and Update Function from Values in TbotsRobotMsg proto

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1276]
### Description of the task
From the framework created in #1164, we need to add fields to represent the useful data contained in TbotsRobotMsg as designed in #1272. We also need to be able to take protos and create or update Robots. For simplicity, it's OK to add fields that enemy robots cannot hope to initialize

### Acceptance criteria

- [ ] Add fields to FriendlyRobot
- [ ] Create update or create functions for FriendlyRobot from TbotsRobotMsg proto
- [ ] Unit testing

### Blocked By
#1164 #1272

**Comment by MathewMacDougall** [comment]
Just to clarify, what info are you thinking of including in the `FriendlyRobot` or `Team` classes? IMO we should avoid putting anything unnecessary for AI logic into the `Friendly...` classes. In the case of #1277 , it should subscribe to the `RobotStatus` messages directly to get the additional data it needs.

**Comment by jonathanlew** [comment]
> Just to clarify, what info are you thinking of including in the `FriendlyRobot` or `Team` classes? IMO we should avoid putting anything unnecessary for AI logic into the `Friendly...` classes. In the case of #1277 , it should subscribe to the `RobotStatus` messages directly to get the additional data it needs.

With the new SensorFusion architecture #1135, there won't be any `Subject`s that output RobotStatus. Visualizer can `Observe` either `SensorProto` or `World`

**Comment by jonathanlew** [comment]
> > Just to clarify, what info are you thinking of including in the `FriendlyRobot` or `Team` classes? IMO we should avoid putting anything unnecessary for AI logic into the `Friendly...` classes. In the case of #1277 , it should subscribe to the `RobotStatus` messages directly to get the additional data it needs.
> 
> With the new SensorFusion architecture #1135, there won't be any `Subject`s that output RobotStatus. Visualizer can `Observe` either `SensorProto` or `World`

~From offline discussion, Visualizer will `Observe` both `SensorProto` or `World`, at least for now~

Edit: see https://docs.google.com/document/d/13BExBYrU6o96WMQGdhUzqdiBatNYfe-HLZJH3kaj3fo/edit?usp=sharing for info about the architecture

**Comment by jonathanlew** [comment]
We are opting for a different architecture, see #1477 and #1522 for more details
