### ISSUE TITLE
Create a new SimulatorBackend to output SensorProto

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1279]
### Description of the task
Create a new SimulatorBackend to output SensorProto using the new simulator in #1244 that outputs SSL_WrapperPacket represent vision data. This should be easily swapped in to integrate things in #1135

### Acceptance criteria

- [ ] Create a new SimulatorBackend to output SensorProto
- [ ] Add unit tests
### Blocked By
 #1283 #1244

**Comment by MathewMacDougall** [comment]
Assigning this to myself as I'll likely deal with it during Simulator upgrades (still need to make tickets after the RFC Design doc).
