### ISSUE TITLE
Create ProtoMulticastListener

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1280]
### Description of the task
We need a generic class to connect to a multicast group to receive protos - ProtoMulticastListener. This will be to receive SSL_WrapperPacket, Referee from SSL and also to implement RobotCommunicator. 

### Acceptance criteria

- [ ] Create ProtoMulticastListener
- [ ] full system integration testing

**Comment by MathewMacDougall** [comment]
I can also do this if @akhilveeraghanta doesn't have time since I'll need it for the Simulator relatively quickly as well
