### ISSUE TITLE
Change firmware polynomial library to allow for t1 > t2 parameterizations

### ISSUE THREAD

**Issue by EvanMorcom** [UBC-Thunderbots/Software#1322]
### Description of the task
The current firmware polynomial library only allows for parameterizations where t1 < t2.

This means current polynomial parameterizations can only move in 1-direction along the curve, compared to having a path that can be 'traversed' in either direction.

### Acceptance criteria
Firmware polynomial functions will allow for t2 < t1 parametrization

(This ticket is being filed so that the 'reverse_parameterization' hack can be removed form the firmware trajectory planner)

**Comment by MathewMacDougall** [comment]
@EvanMorcom can you add tags to this issue?
