### ISSUE TITLE
Implement Unit Test for Primitive ValidatePrimitiveMessage()

### ISSUE THREAD

**Issue by EvanMorcom** [UBC-Thunderbots/Software#133]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
The test/primitives/primitive.cpp unit test file needs a test for the ValidatePrimitiveMessage() function. It is supposed to throw an exception if the message is invalid but as of writing exception handling is not implemented.

**Describe the solution you'd like**
Create a unit test that expects an exception to be thrown if a primitive message is invalid.

**Additional context**
Required issue #16 to complete

**Comment by garethellis0** [comment]
resolved with #376
