### ISSUE TITLE
Simulator: Figure out how to backspin chip

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1343]
### Description of the task

Backspin chipping is something we may want to make use of that we don't get "for free" in simulation because we simulate in 2D. We need to figure out how to simulate backspin chipping. This would require changes in the "physics" layer of the Simulator, mostly to the PhysicsBall and PhysicsRobot classes.

Possible ideas
* Create a model of how backspin chipping at different speeds affects the ball in real life. Then use this model to apply forces to the ball to simulate this real-world behavior. eg. apply a force / impulse to the ball when it lands proportional to how much backspin it has to slow the ball down
* Create a simple internal model similar to above, but make it "ideal" rather than trying to model real-life behavior. Eg. dribbling with less than 1000 rpm has no effect, 1000-2000 slows the ball down, 3000+ causes the all to land and go in reverse (back to the robot)

This should really only be implemented if backspin chipping is something we plan to make use of in our strategy. Check with @jonathanlew @akhilveeraghanta and the software team prior to delving too deep.

### Acceptance criteria

- [ ] Figure out how to simulate backspin chipping

**Comment by EvanMorcom** [comment]
My first though is using the dribbler RPM to get a contact velocity between the ball and the dribbler. There is a constant ratio between the angular velocity of the dribbler and ball that is (R_dribbler/R_ball)*W_dribbler. Use that and a formula for force of a spinning ball in the air.
@MathewMacDougall

**Comment by jonathanlew** [comment]
we will be moving to er force simulator so we'll make a new ticket if this is a priority
