### ISSUE TITLE
Create BallState without timestamp

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1355]
### Description of the task

For certain applications like initializing the state of a physics simulation, it is useful to have a representation of the ball that does not contain timestamp data because it does not make sense in this case.

We should split our `BallState` class slightly to support non-timestamped data as well.

### Acceptance criteria

- [ ] Split `BallState` to also handle non-timestamped data

**Comment by jonathanlew** [comment]
Resolved by #1357
