### ISSUE TITLE
Check equality conditions of timestamped data

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1356]
### Description of the task

While working on #1355, I noticed that the current equality operator for `BallState` (now `BallStateWithTimestamp`) did not use the time data for equality.

ie. States with the same position and velocity, but different timestampes, were considered equal

IIRC the original intention was to make comparisons easier that the real "data" was the same. Especially now that we have disctinction between timestamped and non-timestamped data, this definition of equality no longer makes sense.

We should make the equality operator for `BallStateWithTimestamp` use the timestamp as well for equality, and fix any errors as needed.

### Acceptance criteria

- [ ] Include the timestamp in the equality operator for `BallStateWithTimestamp`

### Blocked By

#1355

**Comment by jonathanlew** [comment]
timestamped data no longer exists
