### ISSUE TITLE
Verify that World::updateRefboxStage and World::updateRefboxGameState works as intended

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1369]
### Description of the task
Verify that World::updateRefboxStage and World::updateRefboxGameState work as intended with WorldTests. We currently don't have tests on these functions at all

### Acceptance criteria

- [ ] Add WorldTests

### Blocked By
#1135

**Comment by MathewMacDougall** [comment]
We might need to have a quick talk about what datastructure we want to use to wrap `refbox` and `gamecontroller` stuff (if we don't have that already). We'll want an "easy" way to set things things for tests.

**Comment by jonathanlew** [comment]
`RefboxStage` and `RefboxGameState` are both enums. What did you have in mind?

**Comment by MathewMacDougall** [comment]
Ah never mind that should be fine. Was thinking of setting the "end result" like `isHalt()` directly, but that's not really necessary.
