### ISSUE TITLE
Create validation functions for time-invariant SSL rules

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1374]
## **Edit: Possibly superseded by #1607. This ticket is on hold until #1607 is resolved**

A core component of our soon-to-be simulated testing system is the ability to validate what the robots and AI do. 

#1055 added "validation functions", which are the functions we use to validate behavior in simulated tests. At a high-level, there are two types:
1. time-invariant conditions
2. time-variant conditions

This ticket will focus on writing time-invariant validation functions for any SSL rules that apply.

These validation functions will be used in our larger simulated testing framework. [The documentation for this framework can be found here](https://github.com/UBC-Thunderbots/Software/blob/master/docs/software-architecture-and-design.md#simulated-integration-tests). Example of it's usage can be found in `src/software/simulated_tests`

**Action items**
1. Read the [SSL rules](https://robocup-ssl.github.io/ssl-rules/sslrules.html)
2. Create a list of rules that we can implement as time-invariant validation functions
3. Check the list with @MathewMacDougall or post in slack for more public discussion
4. Once each rule is OK'd, add it as an "Acceptance criteria" below. This ticket will be used to track all rules we are adding, rather than making a ticket for each
5. For each rule
    1. Implement it
    2. Test it if necessary. Some will be simple enough they don't need additional tests, others may be complicated enough they will. Use your best judgement
    3. Open a PR to add that validation function (note that we're doing one rule / function per PR to keep them smaller and more manageable)

To start, lets put the validation functions in a new `src/software/simulated_tests/validation_functions` folder. We should be able to put these all in a file called `ssl_rules` or similar.

### Acceptance criteria

- [ ] TODO - All rules we want to add functions for here

**Comment by akhilveeraghanta** [comment]
There aren't that many rules that apply to all plays equally. Closing this ticket for now
