### ISSUE TITLE
Define TbotsSoftwareMsg

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1386]
### Description of the task

Need to define `TbotsSoftwareMsg` to communicate from the AI to the robot.
Currently, primitives are sent in custom encoded packets over radio the robots. The new TbotsSoftwareMsg Proto will use the Protobuf encoding and standardize this packet for the old and new robots. 

### Acceptance criteria

- [ ] Define msgs assuming no changes to current radio system

### Blocked By
N/A

**Comment by jonathanlew** [comment]
Resolved by #1389
