### ISSUE TITLE
Implement simulated test for FriendlyKickoffPlay

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1396]
### Description of the task

Currently there exists a skeleton simulated test for the friendly kickoff play, but it has no validation functions to it's not actually checking anything. This ticket is for writing / using validation functions to properly test the play.

### Acceptance criteria

- [ ] Implement the simulated test for the friendly kickoff play

**Comment by jonathanlew** [comment]
resolved by https://github.com/UBC-Thunderbots/Software/pull/1943
