### ISSUE TITLE
Remove GrSim

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1416]
### Description of the task
Once we move to a simulator replacement for GrSim, we can delete it. 
We can also resolve: #982, #742, #1281

### Acceptance criteria

- [ ] Delete estimatePositionAtFutureTime from Ball
- [ ] Delete GrSim
- [ ] :tada:

### Blocked By
#1541 #1536 #1537 #1328

**Comment by MathewMacDougall** [comment]
:heart_eyes:
