### ISSUE TITLE
Add mirror link to STM32H7 HAL download

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1427]
### Description of the task

HAL download sometimes fails when either Cubes servers are down or we experience a network blip causing CI to randomly fail. This ticket involves adding a mirror to the link in `//firmware_new/rules.bzl` so download from  
### Acceptance criteria

- [ ] Find a mirror link
- [ ] Add it to //firmware_new/rules.bzl line 13 as an additional download location

### Blocked By

N/A

**Comment by jonathanlew** [comment]
not an issue anymore
