### ISSUE TITLE
Implement Automatic Restart Of AI When Exceptions Are Thrown And Not Caught

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1431]
### Description of the task
In `full_system_main` we should have a generic catch for all exceptions. When we catch an exception we should log it via `LOG(ERROR)` and then restart everything.

### Acceptance criteria

- [ ] Catch all exceptions in `full_system_main` and log them via `LOG(ERROR)`
- [ ] When we catch an exception in `full_system_main`, everything should be restarted as if the program was running for the first time

**Comment by garethellis0** [comment]
@jonathanlew @akhilveeraghanta - FYI

**Comment by jonathanlew** [comment]
resolved by #1994
