### ISSUE TITLE
Change geom functions to return class variables by const reference

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1444]
### Description of the task
This will reduce unnecessary copying if the caller assigns it to a const type or uses it in a const context (e.g. `for (const auto& g: getGeoms())`).  

For example, change `Point CrossShape::getMidPoint() const` to `const Point& CrossShape::getMidPoint() const` :crossed_swords: 

### Acceptance criteria

- [ ] As titled

**Comment by MathewMacDougall** [comment]
Good idea. Possibly applicable to a lot of our code actually.

**Comment by jonathanlew** [comment]
Might not be worth it since it can sometimes degrade performance. We need to be careful

**Comment by MathewMacDougall** [comment]
Oh? In what cases can performance degrade?

**Comment by jonathanlew** [comment]
I haven't really looked into it, but I think it's if we're assigning a const to non-const or the other way around, and that triggers a copy. I could be that it's just for `Point`, which has copying defined in the `operator=`

**Comment by jonathanlew** [comment]
Returning local variables by const reference is the same as returning a pointer to the stack, which is a big nono

**Comment by MathewMacDougall** [comment]
Ah true
