### ISSUE TITLE
Replace 1e-9, 1e-6, 1e-5 with Appropriate Constants

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1445]
### Description of the task
There exist 1e-9 and 1e-5 in many places in the code base. They should be replaced with constants such as GeomConstant::FIXED_EPSILON, for consistency and robustness.

### Acceptance criteria

- [ ] Design the right set of constants to replace the ones in the title
- [ ] Make sure tests pass still

**Comment by MathewMacDougall** [comment]
Are they used in tests or in the code? I think they're mostly fine to leave if they're in tests?

**Comment by jonathanlew** [comment]
They are used in some places in code
