### ISSUE TITLE
DynamicParameters: Add example generated code to the config examples for each language output

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1447]
### Description of the task

building on #1296 we should add some example generated code so we can have an idea of what the generated code will look like and that our schema provides everything we need. It's a last chance to find any issues before we "commit" to the schema and start writing the generation code.

### Acceptance criteria

- [ ] Add example generated code for the existing configs in C++
- [ ] Add example generated code for the existing configs in C
- [ ] Add example generated code for the existing configs in Python

**Comment by akhilveeraghanta** [comment]
C and CPP params are finished, decided to not do python params for now because we have python bindings for cpp params
