### ISSUE TITLE
Better names for SSLFieldLines enum

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1451]
### Description of the task

Building from the discussion [here](https://github.com/UBC-Thunderbots/Software/pull/1446#discussion_r437148646), we ideally want the enum names that refer to various field lines to match our internal conventions rather than the SSL.

Here's a table of SSL names and our equivalents. As mentioned in the comment thread, our convention mostly exist for naming _points_ (eg. `posXPosYCorner`) rather than line segments. Additional concerns were brought up with the use of `POS` and `NEG` / `RIGHT` and `LEFT` since everything here will label the "raw" input, without regard for any coordinate flipping we do internally (which is what lets us assume the "friendly" half is always -x).

| SSL Name        | Thunderbots Name | Description |
| :-------------: |:-------------:| ---------------- |
| TOP_TOUCH_LINE      | POS_Y_FIELD_LINE | |
| BOTTOM_TOUCH_LINE      | NEG_Y_FIELD_LINE      | |
| LEFT_GOAL_LINE | NEG_X_FIELD_LINE      |     |
| RIGHT_GOAL_LINE | POS_X_FIELD_LINE      |     |
| HALFWAY_LINE | HALFWAY_LINE |     |
| CENTER_LINE | CENTER_LINE | Runs from one goal to the other along the center of the field    |
| LEFT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_STRETCH      | The line along the "top" of the -x defense area |
| RIGHT_PENALTY_STRETCH | POS_X_DEFENSE_AREA_STRETCH      | Same as LEFT_PENALTY_STRETCH for on the +x side |
| RIGHT_GOAL_TOP_LINE | POS_X_GOAL_POS_Y_LINE      | For the goal on the +x side of the field: The line on the +y side of the field that runs from the post to the back of the net (along the x-axis)    |
| RIGHT_GOAL_BOTTOM_LINE | POS_X_GOAL_NEG_Y_LINE      | Same as above but on the -y side    |
| RIGHT_GOAL_DEPTH_LINE | POS_X_GOAL_STRETCH      | The line that makes up the "back of the net" (along the y-axis)    |
| LEFT_GOAL_TOP_LINE | NEG_X_GOAL_POS_Y_LINE      | Same as above but for the goal on the -x side    |
| LEFT_GOAL_BOTTOM_LINE | NEG_X_GOAL_NEG_Y_LINE      | Same as above but for the goal on the -x side    |
| LEFT_GOAL_DEPTH_LINE | NEG_X_GOAL_STRETCH      | Same as above but for the goal on the -x side    |
| LEFT_FIELD_LEFT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_POS_Y_LINE      | For the defense area on the -x half of the field: Connects the `LEFT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the +y side)    |
| LEFT_FIELD_RIGHT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_NEG_Y_LINE      | For the defense area on the -x half of the field: Connects the `LEFT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the -y side)    |
| RIGHT_FIELD_LEFT_PENALTY_STRETCH | POS_X_DEFENSE_AREA_NEG_Y_LINE      | For the defense area on the +x half of the field: Connects the `RIGHT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the -y side)    |
| RIGHT_FIELD_RIGHT_PENALTY_STRETCH |  POS_X_DEFENSE_AREA_POS_Y_LINE      | For the defense area on the +x half of the field: Connects the `RIGHT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the +y side)    |

This issue is to figure out what names we want to use, and then change them in the code.

### Acceptance criteria

- [ ] Figure out names
- [ ] Change names in code
- [ ] Create fully labelled ASCII diagram by this enum

### Blocked By

#1446

**Comment by garethellis0** [comment]
Hmm, `POS_X_DEFENSE_AREA_POS_Y_LINE` is about as good as anything I can think of. Perhaps `POS_Y_LINE_OF_POS_X_DEFENSE_AREA`?

**Comment by garethellis0** [comment]
Some other suggestions:
- `POS_Y_FIELD_LINE` -> `POS_Y_FIELD_EDGE` and similarly for POS/NEG X/Y
- `CENTER_LINE` is a bit ambiguous, if I didn't see `HALFWAY_LINE` right above it I could easily confuse them, but at the same time I don't have any better suggestions off the top of my head
- `STRETCH` in general is very confusing. 
- `NEG_X_GOAL_STRETCH` -> `NEG_X_GOAL_REAR_LINE`

**Comment by MathewMacDougall** [comment]
New version of the table with the previous suggestions

@garethellis0 I took your idea of `REAR_LINE` and tried it with the defense area to replace `STRETCH`

I'm also coming around to the wording of `POS_Y_LINE_OF_POS_X_DEFENSE_AREA`. @EvanMorcom @jordanzliu @jonathanlew @akhilveeraghanta what do you think?

| SSL Name        | Thunderbots Name | Description |
| :-------------: |:-------------:| ---------------- |
| TOP_TOUCH_LINE      | POS_Y_FIELD_EDGE | |
| BOTTOM_TOUCH_LINE      | NEG_Y_FIELD_EDGE      | |
| LEFT_GOAL_LINE | NEG_X_FIELD_EDGE      |     |
| RIGHT_GOAL_LINE | POS_X_FIELD_EDGE      |     |
| HALFWAY_LINE | HALFWAY_LINE |     |
| CENTER_LINE | CENTER_LINE | Runs from one goal to the other along the center of the field    |
| LEFT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_FRONT_LINE      | The line along the "top" of the -x defense area |
| RIGHT_PENALTY_STRETCH | POS_X_DEFENSE_AREA_FRONT_LINE      | Same as LEFT_PENALTY_STRETCH for on the +x side |
| RIGHT_GOAL_TOP_LINE | POS_X_GOAL_POS_Y_LINE      | For the goal on the +x side of the field: The line on the +y side of the field that runs from the post to the back of the net (along the x-axis)    |
| RIGHT_GOAL_BOTTOM_LINE | POS_X_GOAL_NEG_Y_LINE      | Same as above but on the -y side    |
| RIGHT_GOAL_DEPTH_LINE | POS_X_GOAL_REAR_LINE      | The line that makes up the "back of the net" (along the y-axis)    |
| LEFT_GOAL_TOP_LINE | NEG_X_GOAL_POS_Y_LINE      | Same as above but for the goal on the -x side    |
| LEFT_GOAL_BOTTOM_LINE | NEG_X_GOAL_NEG_Y_LINE      | Same as above but for the goal on the -x side    |
| LEFT_GOAL_DEPTH_LINE | NEG_X_GOAL_REAR_LINE      | Same as above but for the goal on the -x side    |
| LEFT_FIELD_LEFT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_POS_Y_LINE      | For the defense area on the -x half of the field: Connects the `LEFT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the +y side)    |
| LEFT_FIELD_RIGHT_PENALTY_STRETCH | NEG_X_DEFENSE_AREA_NEG_Y_LINE      | For the defense area on the -x half of the field: Connects the `LEFT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the -y side)    |
| RIGHT_FIELD_LEFT_PENALTY_STRETCH | POS_X_DEFENSE_AREA_NEG_Y_LINE      | For the defense area on the +x half of the field: Connects the `RIGHT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the -y side)    |
| RIGHT_FIELD_RIGHT_PENALTY_STRETCH |  POS_X_DEFENSE_AREA_POS_Y_LINE      | For the defense area on the +x half of the field: Connects the `RIGHT_GOAL_LINE` to the `PENALTY_STRETCH` line (on the +y side)    |

**Comment by garethellis0** [comment]
This all make sense to me now, but my opinion isn't worth that much at this point given that I already know what they all are.

**Comment by jared-paul** [comment]
I like the most recent enum names, I was able to understand most of them without looking at the descriptions

**Comment by MathewMacDougall** [comment]
@jonathanlew @jordanzliu thoughts on the updated names?

**Comment by jonathanlew** [comment]
I understand most of them. The confusing one is NEG_X_DEFENSE_AREA_POS_Y_LINE, which is inconsistent with NEG_X_DEFENSE_AREA_FRONT_LINE/REAR_LINE. Maybe it should be NEG_X_DEFENSE_AREA_POS_Y_SIDE_LINE or NEG_X_DEFENSE_AREA_LEFT_LINE?

**Comment by MathewMacDougall** [comment]
I'd prefer `POS/NEG_Y` over `LEFT/RIGHT`. @garethellis0 thoughts?

@jonathanlew what do you think of `POS_Y_LINE_OF_POS_X_DEFENSE_AREA`?

**Comment by jonathanlew** [comment]
That's fine too

**Comment by MathewMacDougall** [comment]
I might go for `POS_Y_LINE_OF_POS_X_DEFENSE_AREA` then unless anyone else has an idea.
