### ISSUE TITLE
DynamicParameters: How to pass them into factories?

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1452]
### Description of the task

We are noticing several situations where we want to pass a DynamicParameter `Config` into a class on construction. However, If this class is part of a factory this becomes much more difficult if each object in the factory requires a different `config`. For example, this is an issue passing configs to various `backends` via the `GenericFactory`, or to `Plays`.

**Factories that require the same parameter**
* Backends

**Factories that require different parameters**
* Plays

**Some solutions that have been considered:**
_static class functions that return the correct subconfig from some top-level config_
* Only works if there is a top-level config
* May require the entire top-level config to be mocked for tests (which isn't good if it contains other things not needed by the factory constructors)

_Manually registering things in factories rather than using the generic one_
* Slightly more work to add / remove factory items, and requires slightly more knowledge of factories?
* More "obvious" what's going on
* In the case of Plays, multiple factories / levels of factories could be used like Playbooks?

This ticket is to discuss and figure out the best way to handle these cases so that we can dependency inject `configs` into factory-created objects.

### Acceptance criteria

- [ ] TODO

**Comment by MathewMacDougall** [comment]
ATM I'm kinda leaning to just using manual factories rather than the GenericFactory
* It's a simpler and "more obvious" solution
* We only have 2 factories and rarely add/remove entries, so it's really not more work to maintain
* Gives us more explicit control over how things are created

**Comment by MathewMacDougall** [comment]
@garethellis0 @jonathanlew @EvanMorcom @akhilveeraghanta

**Comment by akhilveeraghanta** [comment]
I agree, `Play Factory` and `Backend Factory` can be non-generic, makes dependency injection into the backends _much_ easier

**Comment by garethellis0** [comment]
We could template the generic factory on an optional argument to pass into the constructor? 

ie.
```
template <class IndexType, class SuperClass, class Subclass, typename ConstructorArg>
class TGenericFactory : public GenericFactory<IndexType, TypeToCreate, ConstructorArg>
...
std::unique_ptr<SuperClass> createInstance(IndexType, ConstructorArg)
```

**Comment by MathewMacDougall** [comment]
That only works if all constructors registered in the factory take the same parameter (and that parameter needs a default constructor), which isn't the case for Plays (and in fact Backends may diverge too)

**Comment by garethellis0** [comment]
Good point. At this point I'm definitely leaning towards non-generic factories as well.

**Comment by jonathanlew** [comment]
Can we inherit from the generic factory?

**Comment by MathewMacDougall** [comment]
You mean inherit to get all the functionality, but expose the functions to manually register stuff?

**Comment by jonathanlew** [comment]
Yeah, I haven't thought it through, but it sounds like a good idea

**Comment by garethellis0** [comment]
I'm unsure what functionality would be shared, but would support it if there is any (I'd also just call it `Factory` instead of `GenericFactory`).
