### ISSUE TITLE
Pull out functions in SSLProtobufReader and test them

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1470]
### Description of the task
as titled

### Acceptance criteria

- [ ] make naming consistent
- [ ] testing

**Comment by MathewMacDougall** [comment]
Where are the functions going to go? the `proto/message_translation` folder?

**Comment by jonathanlew** [comment]
> Where are the functions going to go? the `proto/message_translation` folder?

yes
