### ISSUE TITLE
2019 Fleet Retirement Clean Up

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1475]
### Description of the task 
When we retire the 2019 fleet, we can remove a lot of code that supported the old robots, including radio, firmware, dongle. 

### Acceptance criteria

- [ ] Delete firmware/boards/legacy_robot_stm32f4
- [ ] Delete firmware/boards/legacy_dongle_stm32f4
- [ ] _Maybe_ delete some shared firmware from `firmware/shared` if no longer used
- [ ] Remove stm32f4 targets from travis
- [ ] Remove radio backend and mrf code

**Comment by akhilveeraghanta** [comment]
hmm did we want to do this? thought the plan was to support old robots so we have a reference point, and then drop support

**Comment by jonathanlew** [comment]
I needed to link an issue for #1473, this is not for now, this is for the hopefully not too distant future

**Comment by MathewMacDougall** [comment]
> hopefully not too distant future

plz :pray:

**Comment by jonathanlew** [comment]
resolved by #2464
