### ISSUE TITLE
Visualizer - Add Support For Code Coverage Checking

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#148]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We should add support for code coverage checking to the typescript code that lives in the visualizer. 

**Describe the solution you'd like**
One each build, Travis CI should automatically upload code coverage information to codecov. Here is an example of how to do this for typescript: https://github.com/codecov/example-typescript

**Comment by qgolsteyn** [comment]
This will really depend on the unit testing framework we end up using for the Typescript portion of the project. This [repo](https://github.com/codecov/example-node) provides more example on how to do this for various frameworks. At first glance, it doesn't appear too difficult.
