### ISSUE TITLE
Add sensor fusion tests

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1480]
### Description of the task
Once the threaded portion of SensorFusion is split off, then we can test the non-threaded version. 

### Acceptance criteria

- [ ] SensorFusion tests

### Blocked By
Splitting SensorFusion into threaded and non-threaded parts

**Comment by jonathanlew** [comment]
@MathewMacDougall is there an issue to link to sensor fusion being broken up into threaded and non-threaded parts?

**Comment by MathewMacDougall** [comment]
It will be done as part of #1439
