### ISSUE TITLE
Update description for parameters in yaml files

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#149]
`TODO: Add description as part of #149` need to be replaced with actual brief descriptions so that there is some context to what the parameter is changing. 

The file is located at `util/parameter/config/*.yaml`

**Comment by akhilveeraghanta** [comment]
@MathewMacDougall is this possible to do as part of the upcoming dynamic parameter changes? Also kind of falls under documentation

**Comment by MathewMacDougall** [comment]
Yea this will implicitly be done as we move params over.
