### ISSUE TITLE
Enable SNTP on robot_stm32h7

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1518]
### Description of the task
SNTP: Simple network time protocol

Since we are on the network, and since lwip supports it, we should be able to sync up the STM32H7 with the network time allowing us to better timestamp packets and be synced up with AI.

### Acceptance criteria

- [ ] Enable STNP in STM32CubeMX
- [ ] Figure out a way to get the network time
- [ ] Update all prototimestamps from `sys_now` to the network time from SNTP

### Blocked By
Nothing

**Comment by jonathanlew** [comment]
we've moved away from the stm32h7 architecture so this is outdated
