### ISSUE TITLE
Send RobotStatus from robot_stm32h7

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1519]
### Description of the task

We need to populate and send robot status from the robot to AI.
This ticket will be further defined after the blocked items are resolved.

### Acceptance criteria

- [ ] TBD

### Blocked By
This ticket is blocked on sensor availability and abstractions around those sensors to get the data.
This ticket will be further defined once that becomes more clear.

**Comment by jonathanlew** [comment]
we've moved away from the stm32h7 architecture so this issue is outdated
