### ISSUE TITLE
Determine Nominal Battery Voltage

### ISSUE THREAD

**Issue by EvanMorcom** [UBC-Thunderbots/Software#1532]
### Description of the task

Some location in the code need to be aware of the nominal battery voltage. Ex, the controller needs to know how much voltage it can apply.
This nominal voltage could be determine experimentally or perhaps through the battery data sheet.
### Acceptance criteria

All TODO's with this issue # are resolved, and the change made to shared/constants.h

**Comment by jonathanlew** [comment]
not a problem with trinamic
