### ISSUE TITLE
Visualizer: Draw field vertically

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1535]
### Description of the task

It will take up less space overall

### Acceptance criteria

- [ ] As titled

**Comment by MathewMacDougall** [comment]
Polling @akhilveeraghanta @jonathanlew @kelvinkoon @jared-paul @LiCody @HaomiaoZ for if you think this is a good/worthwhile change or not.

**Comment by HaomiaoZ** [comment]
So when the field is taking less space means we have more space for? Personally I prefer a horizontal field since it feels more natural to me, but I'm total ok with changing it to vertical if space is an issue now

**Comment by MathewMacDougall** [comment]
My initial reasoning was that we don't need the entire width of the screen for logs, since most of those messages are pretty short. Making the field vertical would in theory offer more space for things like robot status (eg. batter and capacitor voltage). I was initially inspired by the Robojackets UI.

I could always make a quick mockup and we can use that to help decide what may be better. For example, we could leave the field horizontal and just put the status information where the logs are.

**Comment by MathewMacDougall** [comment]
![mock_vertical_gui](https://user-images.githubusercontent.com/21165407/92547195-366d9480-f209-11ea-9cee-1e865664a03d.png)

Quick mock GUI with a vertical field. It's pretty close to "to-scale" on a 16:9 ratio screen. I assumed we'd show the entire field, which is 9.6/6.6 = about a 1.45 ratio.
