### ISSUE TITLE
Add Flags to Move Intent

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#154]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
Old AI had special move actions, such as staying on side of the field. This feature needs to be added to new AI. 

**Describe the solution you'd like**
Add these features as flags to move intents, intending them to be consumed by the navigator or be passed to the primitive level.

**Describe alternatives you've considered**
We could make specific actions to describe the function of each flag, but unifying the actions into one move intent with flags allows more code reuse.

**Comment by henryymliu** [comment]
~~After discussions, this is not needed.~~

**Comment by henryymliu** [comment]
Would it be useful to add this to the Intent base class, not just MoveIntent?

**Comment by MathewMacDougall** [comment]
Hmmm not sure. Traditionally, the flags were only really for the MoveIntent since it was the only one that incorporated navigation. ATM I can't think of a use for the flags in other intents, so for now it's probably easiest to just add them to the MoveIntent. It should be easy to make generic in the future if we need it.

**Comment by henryymliu** [comment]
Currently I'm porting over MoveFlags from the old AI; if we ever want other flags for the other intents in the future I should consider that in the design.

**Comment by henryymliu** [comment]
Maybe if it's so trivial to port we might as well do it in the first place?

**Comment by MathewMacDougall** [comment]
Fine with me
