### ISSUE TITLE
SimulatorGUI: Set ball velocity

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1542]
### Description of the task

as titled

Being able to set the ball velocity from the GUI is very useful to set up various test scenarios for the AI, especially in combination with the Simulator's pause feature.

There are many ways this could be done from a UI/UX perspective so here are some options:
* "Click and drag" the ball to set the velocity. When the mouse button is released, the ball's velocity would be set to the vector formed by the click-and-drag (so it's like "slingshotting" the ball).
* Pop up a text-box and input the vector manally

### Acceptance criteria

- [ ] as titled

**Comment by jonathanlew** [comment]
resolved by #1877
