### ISSUE TITLE
Set protobuf fields by copying to `mutable_...` and `add_...` instead of using `set_allocated_...`

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1557]
### Description of the task
as titled
The goal is to avoid using release in some places and not in others, since that can be confusing to new (and old) members.

Old, error-prone style:
```
std::unique_ptr<sub_proto> sub_p_ptr;
std::unique_ptr<proto_to_add> add_p_ptr;
// setting a field in proto
proto.set_allocated_sub_proto(sub_p_ptr.release());
// Adding add_p_ptr to a repeated field
*(proto.add_sub_proto()) = *add_p_ptr;
```
New convention:
```
std::unique_ptr<sub_proto> sub_p_ptr;
std::unique_ptr<proto_to_add> add_p_ptr;
// setting a field in proto
*(proto.mutable_sub_proto()) = *sub_p_ptr;
// Adding add_p_ptr to a repeated field
*(proto.add_sub_proto()) = *add_p_ptr;
```

### Acceptance criteria

- [ ] change instances
- [ ] change code conventions

**Comment by MathewMacDougall** [comment]
Might be good to note the difference in this example of setting a single primitive/value, vs adding a value to a repeated field.
