### ISSUE TITLE
Change getName() in Play and Tactic To Return A Name Based On a Preprocessor Macro

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#159]
Currently, the implementation of `getName` for plays looks like:
```
std::string ShadowEnemyTactic::getName() const
{
    return "Shadow Enemy Tactic";
}
```
or 
```
std::string PenaltyKickPlay::getName() const
{
    return PenaltyKickPlay::name;
}
```
Ideally, we would instead have a preprocessor macro here that would (at compile time) determine the class name and put it's string representation here. We should replace the implementation in all plays (or ideally just somehow implement it in the `Play` class).

**Comment by jonathanlew** [comment]
https://stackoverflow.com/questions/3649278/how-can-i-get-the-class-name-from-a-c-object
Ideally, we want to have a function in a parent class so that none of the child classes have to implement getName. More investigation needed to see if this works.
