### ISSUE TITLE
Clean Up DirectWheels Primitive

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1590]
### Description of the task
Clean up the Direct Wheels primitive to make it more usable.

### Acceptance criteria

- [ ] Change functions:
`getWheel0Power` -> `getFrontLeftPower`
`getWheel1Power` -> `getBackLeftPower`
`getWheel2Power` -> `getBackRightPower`
`getWheel3Power` -> `getFrontRightPower`
- [ ] Change the units of `power` used throughout the class to something more meaningful. These changes should also be reflected in the firmware implementation of the the direct wheels primitive

**Comment by jonathanlew** [comment]
I think the correct solution is https://github.com/UBC-Thunderbots/Software/issues/1649
