### ISSUE TITLE
StandaloneSimulator robot placement doesn't display during pause

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1599]
### Description of the task

Known issue introduced in #1594 with the initial robot placement feature

> However this doesn't fix the original issue of robot placement not being updated visually while the Simulator is paused. This is because these updates only happen at the end of a physics tick (to synchronize with the Box2D world), but that doesn't happen during pause.

We need to find a way to show the updated locations of robots being placed while the simulator is paused.

This may not be possible due to how most robot and ball updates are currently done. In summary:
* When the simulator is requested to set the position of a robot or ball, this action is stored in a queue. Actions in this queue are then run in order after each Box2D physics step. The reason for this is that we must make sure we don't mutate the physics world **_in the middle of a physics step_**, otherwise the program will crash (Box2D has internal checks for these mutations and will abort the program).
* If the simulator is in the "pause" state, there will be no physics updates occurring meaning this action queue will not be processed. Therefore the robot / ball will not actually be moved until simulation starts again.

We explicitly chose not to manually trigger an additional physics update because this could lead to slightly strange behavior (one would not expect simulation to occur at all during pause), and depending where it's invoked from could bypass any internal timing systems in the simulator.

It may be possible to do a zero-time physics step so that the post-step action queue can be processed but effectively nothing changes and simulated time does not move forwards (ie. call `stepSimulation(Duration::fromSeconds(0));`. This would need to be investigated.

### Acceptance criteria

- [ ] TODO

**Comment by jonathanlew** [comment]
closed due to new thunderscope and simulator architecture
