### ISSUE TITLE
Add custom exceptions and exception handling

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#16]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
When we encounter run time errors, such as an unrecognized Primitive trying to be constructed, we need a better way to handle these errors than either ignoring them or immediately aborting the program. Simply using std::exit, std::abort, or assert does not give much information about the problem be default, and any case that includes once of those is not testable.

**Describe the solution you'd like**
We should add proper exception handling in the places in our code where a runtime error such as above could occur. If an unexpected scenario occurs, our code should throw an exception. Even if the exception is not handled by a parent function (which it likely won't be), it will cause the program to gracefully shut down and provide the user more context for what happened, and where. We can also include test cases that excessive these unexpected scenarios and can check the correct exception is thrown.

The first places that should be looked at are where we receive and cast Intents in the navigator (`rrt.cpp`), 
the static 'Primitive factory" function in the Abstract Primitive class (`primitive.h/.cpp`). There may be some other places marked with a `TODO` as well.

We should try use c++'s built-in exceptions, and choose those that are the most relevant to the error we encounter. Something like `std::invalid_argument` is probably best.

**Edit**: Make sure to update the comments for any functions that are modified to include the `@throws` label

**Describe alternatives you've considered**
LIke mentioned above, we can deal with runtime errors by either correcting for them as much as possible (eg. with default values), or aborting/exiting the program. We should not tolerate these errors as they are severe and indicated errors in the code elsewhere (ie. we should never be getting this unexpected data, where is it coming from?). We should also not abort/exit the program because without any print statements they provide no insight to why the program was stopped, and are not cases that can be tested with a unit test.

**Comment by garethellis0** [comment]
_We're T-10 days to the end of September, so just doing a quick run-through to see if there's anything we can afford to push to an October sprint._

Is this needed for an MVP? I definitely feel it's a need-to-have in general, but I think we can afford to push this out by a month if we're not going to get it finished for the September sprint.

**Comment by MathewMacDougall** [comment]
Agreed, we have higher priorities. Removing from September sprint scope.

**Comment by MathewMacDougall** [comment]
_We're T-7 days to the end of October, so just doing a quick run-through to see if there's anything we can afford to push to an November sprint._

This should ideally be finished for October so we can establish the "correct" procedure for the kinds of cases that require exceptions or warnings. @orayasrimokla ETA on a PR?

**Comment by orayasrimokla** [comment]
Adding a pull request by the end of today! It's a very basic exception outline so it will need a little more work after October.

**Comment by garethellis0** [comment]
Just making a note here that we should make sure to resolve all `TODO`'s in the codebase associated with this ticket before closing it (there are several places that we should be throwing exceptions, but are waiting for this to be finished).

**Comment by MathewMacDougall** [comment]
^ Yup mentioned this in my review
