### ISSUE TITLE
Add Checks For Merge Conflict Markers In Formatting Scripts

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1600]
### Description of the task
We can use `git diff --check` to check for merge conflict markers in files. This should be a blocking check in CI. This could be a check in CI or maybe part of the `fix_formatting.sh` script. Adding it to `fix_formatting.sh` seems a little deceptive since it's a *check* not a *fix*, but at the same time we probably want to be able to run this check locally, not just in CI.

**Comment by akhilveeraghanta** [comment]
This is really good, can we also automatically add newlines at the end of the file, saves a lot of "add newline at EOF" comments

https://unix.stackexchange.com/questions/31947/how-to-add-a-newline-to-the-end-of-a-file

`git ls-files -z | while IFS= read -rd '' f; do tail -c1 < "$f" | read -r _ || echo >> "$f"; done`

**Comment by jonathanlew** [comment]
For this to run correctly locally, you would need to git fetch upstream first, right?

**Comment by garethellis0** [comment]
> For this to run correctly locally, you would need to git fetch upstream first, right?

I don't _think_ you would have to?

We definitely do not want to start doing pushes/pulls/fetches in peoples repos.
