### ISSUE TITLE
Replace getStart/getEnd with getEndpoints

### ISSUE THREAD

**Issue by kelvinkoon** [UBC-Thunderbots/Software#1603]
### Description of the task

In the `Segment` class, there are methods for returning `start` and `end`. A segment should not have a start and end, so we want to replace it with `getEndPoints`, which will return a `pair<Point>`.

`getEndPoints` should not guarantee which point is returned first. As such, portions of the code which rely specifically on `start` or `end` will need to be refactored somehow. 
For previous discussion, see https://github.com/UBC-Thunderbots/Software/pull/1591#issuecomment-657170840

### Acceptance criteria

- [ ] `getStart` and `getEnd` are rewritten as `getEndPoints`
- [ ] `getEndPoints` returns `pair<Point>`
- [ ] Tests still pass

### Blocked By

Currently blocked by #1098

**Comment by jonathanlew** [comment]
It's not worth fixing given higher priority work
