### ISSUE TITLE
Write validation funcions for Corner Kick Play

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1608]
### Description of the task

Start building up a suite of validation functions we can use to validate plays, starting with the Corner Kick Play.

To start, modify the existing Corner Kick Play test to be a very simple scenario where we know only 1 robot will receive the ball. Write some basic validation functions to assert the passer kicks the ball, the receiver one-time kicks, and the ball enters the enemy net.

Please put up a WIP PR at this point so we can see what that looks like. We can use the initial version to make more informed decisions about how to write these validation functions going forwards. (What's easy to use, what's easy to write, etc).

### Acceptance criteria

- [ ] See description. Get a quick version working first then put up a WIP PR
- [ ] Discuss the PR
- [ ] Make final version

**Comment by jonathanlew** [comment]
closed by #1736
