### ISSUE TITLE
Assign friendly robots based on friendly team color

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#161]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
Logic should be added to change which robots are on the friendly team based on the `friendly_team_color` set in the Parameter Server (see #160)

**Describe the solution you'd like**
Implement logic to assign robots to the friendly team based on their color and the color of the friendly team. This should go in the `backend_input` node.

1. We will also need to change the code in `getFilteredFriendlyTeamData` (and the enemy equivalent), since this is where we actually select the robots being used for each team.
2. Similarly, the `setOurFieldSide()` function and the `our_field_side` variable aren't being used yet and will need to be for this to work
3. In both cases, the "refbox override" parameters will also need to be used. Otherwise we will always be using our manually set values and not listening to the refbox.

**Comment by henryymliu** [comment]
@akhilveeraghanta i'm going off hazy memory of a discussion at the beginning of this month, is this okay to move to the backlog or are the requirements clear now?

**Comment by akhilveeraghanta** [comment]
@henrymliu we need to check if the refbox provides this information, which would change the scope of this ticket

**Comment by henryymliu** [comment]
Briefly looking at `ssl_referee.proto`, there are `TeamInfo` messages for yellow and blue teams, and `TeamInfo` contains a `name` field for the name of our team. Those can be used to determine what color we are.
