### ISSUE TITLE
Log Errors From Trajectory Planner In Move Primitive

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1622]
### Description of the task
The trajectory planner returns error codes to tell us if and how trajectory generation failed. We should log these errors and send them back to software so they're visible to the user. Note that there may not yet be a logging system in place for logging errors from firmware. Please consult with senior software folks to check this!

### Acceptance criteria

- [ ] Log errors returned by the trajectory planner in the move primitive in firmware

### Blocked By
https://github.com/UBC-Thunderbots/Software/issues/1652

**Comment by MathewMacDougall** [comment]
Since the firmware is running a trajectory sent to it by software, do we even need to send errors back? Wouldn't we encounter the error in software first if one exists, so can log it from there?

**Comment by garethellis0** [comment]
In an ideal world yes, but the AI is making decisions based on the last perceived state of the robot, and the robot state will change by the time we're actually executing the trajectory on the robot.

**Comment by MathewMacDougall** [comment]
Fair enough, and a system to log onboard errors would be more generally useful. Seems like this is something we could add to RobotStatus easily since the trajectory errors are basically enums anywway.
