### ISSUE TITLE
Add `static const std::string NAME` to every Tactic and return that value in the `getName()` function

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1629]
### Description of the task
We want to have access to the name of a type of `Tactic` in a static way, e.g. `MoveTactic::NAME` to access the return value of the `getName()` function, without instantiating a `MoveTactic`. We want this to be consistent with the Play class.

### Acceptance criteria

- [ ] Add `static const std::string NAME` to each *_tactic.h
- [ ] Set the value of name in the .cpp like so: `const std::string MoveTactic::name = "Move Tactic";` in each *_tactic.cpp
- [ ] return this value in the getName() function

**Comment by MathewMacDougall** [comment]
Just curious if there is a use-case beyond consistency? Are we arbitrarily creating tactics just to get the name somewhere?

**Comment by jonathanlew** [comment]
Yeah, basically for consistency.
