### ISSUE TITLE
Rename tick functions to app_[primitive_name]_primitive_tick

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1631]
### Description of the task
For example, rename `spinning_move_tick` to  app_spinning_move_primitive_tick

### Acceptance criteria

- [ ] Rename all such instances in firwmare/app/primitives folder

**Comment by Resocram** [comment]
@jonathanlew Just wondering, should the format be app [primitive_name] primitive tick or app primitive [primitive_name] tick? This [code style guide](https://github.com/UBC-Thunderbots/Software/blob/master/docs/code-style-guide.md) says it should be PREFIX_FILENAME_NAME, so would it be app primitive [primitive_name] tick?

**Comment by jonathanlew** [comment]
I think an example might help. Taking the example of spinning_move_primitive, the filename is `spinning_move_primitive.c`, so the prefix(app or io) is `app`, the filename is `spinning_move_primitive` and the name is `tick`, then the full name would be ` app_spinning_move_primitive_tick`, right?

**Comment by Resocram** [comment]
Oh sorry I was looking at the directory containing those files and it was named primitive, so I got confused. Thanks for the clarification!
