### ISSUE TITLE
Create PrimitiveMsg Factory

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1639]
### Description of the task
Create primitive_msg_factory[.h/.cpp] in software/primitive for creating `PrimitiveNewMsg`s. The file will contain functions like
`std::unique_ptr<PrimitiveMsg> createAutokickMovePrimitive(const Point &dest, const Angle &final_angle, double final_speed, double dribbler_speed, double kick_speed)` for all `*PrimitiveMsg` in primitive.proto except for `DirectControlPrimitiveMsg`

NOTE: while this will be called PrimitiveMsgFactory, it will create PrimitiveNewMsgs as defined in primitive.proto since as a step before integration for the new primitive protos. During integration, we will rename PrimitiveNewMsg to PrimitiveMsg

### Acceptance criteria

- [ ] New factory functions
- [ ] Tests

### Blocked By
#1620

**Comment by MathewMacDougall** [comment]
Curious why this factory takes the primitive parameters directly, rather than a specific Primitive class?

eg. why not `std::unique_ptr<PrimitiveMsg> createPrimitive(const MovePrimitive& primitive);`?

**Comment by jonathanlew** [comment]
With the new primitive protobufs being more expressive, we can do away with the Primitive class entirely, so this issue it targetting that new architecture. https://github.com/UBC-Thunderbots/Software/pull/1637 is the first step in that direction

**Comment by MathewMacDougall** [comment]
Ah ok if the current Primitive class doesn't exist / is removed this makes way more sense :+1:
