### ISSUE TITLE
Split Firmware MovePrimitive and create MoveManager

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1647]
### Description of the task
split to match primitive.proto split

### Acceptance criteria

- [ ] Item A
- [ ] Item B
- [ ] Item C

**Comment by MathewMacDougall** [comment]
What's the `MoveManager`? You just mean update the `PrimitiveManager`?

**Comment by jonathanlew** [comment]
it's a place to share the act of moving among move_primitive, autokick_move_primitive, autochip_move_primitive
