### ISSUE TITLE
Add logic to start/stop the AI

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#165]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
The AI needs logic to start/stop running it's decision making.

**Describe the solution you'd like**
Logic should be added to the `ai` node to start/stop running the AI logic based on the `AI_running_state` from the parameter server. See #164. A simple `if` check that runs the AI logic if true should be sufficient.

**Comment by akhilveeraghanta** [comment]
@MathewMacDougall now that the AI doesn't run in a loop and is more callback based, do we need this param + check? 

If so, would we just check at the begining of `worldUpdateCallback` and return if `run_ai` is set to false?

**Comment by MathewMacDougall** [comment]
Good point. Yes that seems more reasonable.
