### ISSUE TITLE
Add networking setup to documentation to run Simulator

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1666]
### Description of the task

While trying to run the Simulator with 2 AIs, we realized by Ubuntu closes all ports by default (no data goes through), so we need to explicitly open the ports we use to communicate in order for things to work.

Eg.
```
sudo ufw allow 42069
sudo ufw allow 42070
sudo ufw allow 42071
```

We should figure out how we want to involve this in our environment setup. Options:
* Add it to the documentation
* Add it to the setup scripts
* Something else?

In all cases it's a bit tricky since we'd have to make sure the values are up to date with our internal constants, or tell the user to check the contants file for the most up to date values. Thoughts on the best way to do this?

### Acceptance criteria

- [ ] Figure out how to set up networking ports in our environment setup
- [ ] Do it

**Comment by MathewMacDougall** [comment]
@akhilveeraghanta @jonathanlew @kelvinkoon @jared-paul @LiCody @HaomiaoZ

**Comment by kelvinkoon** [comment]
I think you can do `sudo ufw allow 42069:42071` to keep it a one-liner.
If you're doing a script, maybe also do `sudo ufw status` to see that it worked.

My intuition about the ports is they shouldn't change much so I don't see anything wrong with telling them to check the constants file and the documentation pointing to it.

**Comment by kelvinkoon** [comment]
Confirmed by @jsn0716 no additional setup was needed with port configurations/ufw. I think maybe just adding a note that if `ai vs ai` isn't running, try this series of commands.
