### ISSUE TITLE
Rename Manager to More Specific Names

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1668]
### Description of the task
`Manager` is  a vague term that doesn't convey much information. We should rename them where we can to more specific terminology

### Acceptance criteria

- [ ] Review all instances of Manager in names
- [ ] Replace them where possible

**Comment by Resocram** [comment]
@jonathanlew Do you have any specific examples of Manager that you wanted me to change? I only see managers in primitive_manager and motion_constraint_manager?

**Comment by jonathanlew** [comment]
Yes those two and `PathManager`

**Comment by akhilveeraghanta** [comment]
Decided to not change `PathManager` and `PrimitiveManager` for now (not worth the arch effort)
