### ISSUE TITLE
Fix PasserTactic not Kicking

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1690]
### Description of the task
Corner kick play test isn't working: 
![cornerkicknotworking](https://user-images.githubusercontent.com/31377876/90681739-bd39dd80-e218-11ea-83fe-7aac6dea933c.gif)
In this example, it should kick the ball, but it doesn't.
This also occurs in the free_kick_play_test
 I've narrowed it down to https://github.com/UBC-Thunderbots/Software/pull/1619 and I suspect it's the PasserTactic changes

### Acceptance criteria

- [ ] Make it kick

**Comment by MathewMacDougall** [comment]
resolved by #1693
