### ISSUE TITLE
Update GUI Variable naming in Robot Diagnostics

### ISSUE THREAD

**Issue by LiCody** [UBC-Thunderbots/Software#1730]
### Description of the task

Our GUI naming convention has changed so we want to change the ```Robot Diagnostics``` widget to match that.
Refer to https://github.com/UBC-Thunderbots/Software/blob/master/docs/software-architecture-and-design.md#gui
and #1718 for examples

### Acceptance criteria

- [ ] Rename variables in robot diagnostics

**Comment by jonathanlew** [comment]
Given the changes coming to the visualizer, it's worth holding off on it until we're sure we're keeping it
