### ISSUE TITLE
Make isApplicable and invariantHolds in Plays static

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1733]
### Description of the task
The`isApplicable` and `invariantHolds` functions for plays don't use their member variables, so they should made `static`

### Acceptance criteria

- [ ] Make `isApplicable` and `invariantHolds` in Plays `static`

**Comment by itsarune** [comment]
`isApplicable` and `invariantHolds` are declared as:
`virtual bool isApplicable(const World& world) const = 0;` and
`virtual bool invariantHolds(const World& world) const = 0;` and is later overwritten by subclasses. These functions cannot be declared `static`

**Comment by itsarune** [comment]
`isApplicable` and `invariantHolds` are declared as:
`virtual bool isApplicable(const World& world) const = 0;` and
`virtual bool invariantHolds(const World& world) const = 0;` and is later overwritten by subclasses. These functions cannot be declared `static`
