### ISSUE TITLE
Implement ErrorCode Logging Infastructure on robot_stm32h7

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1752]
### Description of the task

There are critical failures on the robots that are communicated through "error codes". These error codes are currently defined in the `RobotStatusMsg` proto. We need a way of logging and communicating these error codes back to AI.

### Acceptance criteria

- [ ] Create error code logging infrastructure for `firmware_new`
- [ ] Ensure proper integration with #1506 (we probably want to send an error code when we hard fault)
- [ ] Update `RobotStatusMsg` to include the error codes
- [ ] Ensure that the logged error codes show up on the Visualizer

### Blocked By
N/A

**Comment by jonathanlew** [comment]
we've moved away from the stm32h7 architecture so this issue is outdated
