### ISSUE TITLE
Reduce clutter from CI logs

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1753]
### Description of the task
From https://github.com/UBC-Thunderbots/Software/pull/1544,

> Its really hard to figure out what went wrong because the build logs for travis are incredibly long
Travis doesn't support ANSI escape characters so every time bazel does a carriage return and rewrites the same line, it shows up as a new line causing the logs to flood
We can suppress the loading progress, and the progress, which makes it significantly less cluttered

https://github.com/UBC-Thunderbots/Software/pull/1544 attempted to fix this, but if dependencies take too long to download, Travis CI can time out since it won't see the constant progress messages. We need to figure out how to make the downloading of dependencies print out periodically _or_ disable Travis CI timeouts

### Acceptance criteria

- [ ] reduce clutter without causing CI to fail

**Comment by akhilveeraghanta** [comment]
closed as part of #1812 because it collapses the logs
