### ISSUE TITLE
Add logrotate sink to g3log

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#1754]
### Description of the task
g3log is designed to have logging sinks that define where the logs get stored. Currently we don't define a sink which causes every log to print `g3logworker has no sinks`. This also means that logs are not currently saved to a file.

~~~
g3logworker has no sinks. Message: [2020/09/27 17:37:51 704875  WARNING [crease_defender_tactic.cpp->calculateDesiredState:114]  Could not draw a line ...
g3logworker has no sinks. Message: [2020/09/27 17:37:51 705004  WARNING [crease_defender_tactic.cpp->calculateDesiredState:114]  Could not draw a line ...
g3logworker has no sinks. Message: [2020/09/27 17:37:51 705047  WARNING [crease_defender_tactic.cpp->calculateDesiredState:114]  Could not draw a line ...
g3logworker has no sinks. Message: [2020/09/27 17:37:51 705214  WARNING [crease_defender_tactic.cpp->calculateDesiredState:114]  Could not draw a line ...
g3logworker has no sinks. Message: [2020/09/27 17:37:51 705258  WARNING [crease_defender_tactic.cpp->calculateDesiredState:114]  Could not draw a line ...
~~~

We can  fix this and also add support for having logs that persist by adding the `logrotate` sink. 
https://github.com/KjellKod/g3sinks

### Acceptance criteria

- [ ] Add the g3sink repo to `WORKSPACE` as a dependency
- [ ] Extend `g3log.BUILD` in the `external` folder to build the `g3sinks` library
- [ ] Follow `g3sink` documentation to add `logrotate` sink to the `LogWorker` currently in `software/logger/logger.h` 
- [ ] Make sure that logs show up on the terminal and also logged to a log file

### Blocked By
N/A

**Comment by LiCody** [comment]
resolved by #1845
