### ISSUE TITLE
Separate robot_communication node into a radio node and grsim node

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#176]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
The current `robot_communication` node should be separated into 2 separate nodes: 1 for radio communication, and one for grSim communication.

This will keep each type of communication separate, and allow for more specific behavior/interfaces in each.

**Describe the solution you'd like**
Separate the code that communicates with grSim into its own node, and separate the code that will deal with the radio and robot communication into another separate node.

**Comment by MathewMacDougall** [comment]
If we split the nodes, we don't really have a need for the generic `Backend` class anymore, each node can just have its own class. Although both backends would take the same parameters for now, I don't see any reason why separating them would be harmful.

@garethellis0 @henrymliu @EvanMorcom @akhilveeraghanta FYI

**Comment by garethellis0** [comment]
Yeah, the API for the backend is really just enforced at the ROS message level, though I wouldn't mind having them both inherit from an abstract `Backend` class (makes it easier if we ever decide to switch away from ROS).
