### ISSUE TITLE
Obtain Robot Physical Constants

### ISSUE THREAD

**Issue by EvanMorcom** [UBC-Thunderbots/Software#178]
Our robots use a bang-bang motion controller to control their motion on the field. Bang-bang controllers have 2 states: Max acceleration and Zero acceleration. For our robot firmware and software to accurately represent the motion of the robots the MAX_ACCELERATION, and MAX_ANG_ACCELERATION constants should be obtained. 

The max acceleration values can be obtained by applying maximum voltage to the robots motors, and using accelerometers/precise timing to obtain the acceleration.  

Additionally, it is useful to know the ROBOT_MAX_SPEED and ROBOT_MAX_ANG_SPEED for motion control.

These max speed values could be obtained when the robot is a max speed using a camera with a known frame rate.
These constants can be found at: src/thunderbots/shared/constants.h

**Comment by garethellis0** [comment]
@EvanMorcom @MathewMacDougall - we should properly tag this or close it. Not sure if it's worth having this ticket open right now, especially given that we're doing a new generation of robots.

**Comment by MathewMacDougall** [comment]
I think we might as well close it. In our speed tests the existing values were actually kind of close to what we observed in testing.
