### ISSUE TITLE
PrimitiveManager: Separate Primitive Protobuf Interpretation from Primitive Invokation 

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1814]
### Description of the task
Following from discussion related to #1668, the PrimitiveManager is doing 2 things:
1. Interpret primitive protobufs to set up the primitive states correctly
2. Execute the primitive using the start/tick/end interfaces

We should separate these responsibilities into two files.

### Acceptance criteria

- [ ] separate responsibilities into 2 files
- [ ] make sure the behaviour is the same

**Comment by akhilveeraghanta** [comment]
decided to not do, not worth the refactor effort
