### ISSUE TITLE
Visualize custom shapes in visualizer

### ISSUE THREAD

**Issue by qgolsteyn** [UBC-Thunderbots/Software#184]
We want to give the visualizer the ability to display every shape compatible with the AI. Aka, implement the conversion between shape message to shape in the UI. Highly dependent on #183 

Will also need to revisit the color system in corner kick to support continuous shade creation. Essentially we will have a base shade for each color (red, orange, green, etc.) and a shade modifier, which is an integer between 0 to 1.

**Comment by garethellis0** [comment]
Just as a quick comment, I'd like to add fixing the very scattered color definitions in the visualizer. Right now if I were to add or remove a color I'd need to make changes in 3-5 places. Ideally we only have to do it in one.
