### ISSUE TITLE
Add Log level and Logging functions for cost/evaluation functions

### ISSUE THREAD

**Issue by LiCody** [UBC-Thunderbots/Software#1842]
### Description of the task

For debugging modules that rely on cost or evaluation functions we want to use the logger to generate a .csv file for analysis

### Acceptance criteria

- [ ] Add cost/evaluation log level to `custom_logging_level.h`
- [ ] Add cost/evaluation logging function to the custom sink to write values to a .csv file so that the .csv file can be plotted
- [ ] Modify the logging call function so that logs at this log level arent sent to the .log file

### Blocked By

#1754

**Comment by jonathanlew** [comment]
Some ideas:
* `LOG(CSV)<<"filename.csv"<<"val1,val2,val3"` appends to a file called filename.csv
* the macro above can be wrapped in another macro to ensure good formatting, e.g. `LOG(CSV,filename.csv)<<"val1,val2,val3"`
* we can check this into the codebase only if this logging level is disabled by default.
