### ISSUE TITLE
ThetaStarPathPlanner performance issues

### ISSUE THREAD

**Issue by jordanzliu** [UBC-Thunderbots/Software#1852]
### Description of the task

This is a ticket to track low-hanging fruit for improving ThetaStarPathPlanner performance, see acceptance criteria for individual tasks

### Acceptance criteria

- [ ] Use `unordered_set` instead of `set`, `unordered_map` instead of `map` for `unblocked_grid` and `line_of_sight_cache`

**Comment by jonathanlew** [comment]
superseded by #2048
