### ISSUE TITLE
Implement Simulated Stop Play Test

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1908]
### Description of the task
Write validation functions to ensure that the robots obey the [rules for stopping](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_stop). Add tests for robots close to ball/far from ball + friendlyhalf/enemyhalf 

### Acceptance criteria

- [ ] write validation functions to check rules
- [ ] identify any broken rules and potential solutions

**Comment by jonathanlew** [comment]
We should aim to have a test for robots moving too quickly as discussed here: https://github.com/UBC-Thunderbots/Software/issues/1882

**Comment by tarakong01** [comment]
Do you mean as in, test a scenario where robots are moving too fast and make sure the test fails? Or just testing that they are moving <= 1.5 m/s as the rules state?

**Comment by jonathanlew** [comment]
The first one. Set up a test scenario where the robots go too fast and a validation function that catches it, then remove that check and add a TODO linked to #1882.
