### ISSUE TITLE
Add "EstopOption" as part of robot status message

### ISSUE THREAD

**Issue by amrm3lm** [UBC-Thunderbots/Software#1956]
We need a way to identify when we want our backend to setup a connection with an Arduino to get the state of Estop (like when doing physical testing/competition), and when our backend is working for the simulator (so that no estop is needed). Our solution to this is to add a proto of "EstopOption" that is sent from the robots to sensor fusion as part of the robots status message. If this proto exists, then we know we are dealing with real robots and need to setup estop.

**Comment by jonathanlew** [comment]
Closed by #2070
