### ISSUE TITLE
Integrate motor drivers into firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2063]
### Description of the task
Mainboard rev2 currently has the wrong pins routed through the card edge,  so we can't really integrate the motors without mainboard rev2.1 fixing this issue.

The pins have also changed a bit, so this ticket will involve fixing that too. 

### Acceptance criteria

- [ ] Integrate motors into robot
- [ ] Make sure we can control them through robot diagnostics
- [ ] Do some basic tuning

### Blocked By

Waiting for Mainboard v2.1 (or a manual board edit)

**Comment by jonathanlew** [comment]
out of date given switch to i2c interface and new motor drivers
