### ISSUE TITLE
Integrate u-blox odinw262 into firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2064]
### Description of the task

Mainboard rev v2 has support for the ublox odin262 chip, but doesn't provide a way to reset the chip making it harder to command it using AT commands. The u-blox board is also in the works, so we have to disable the WiFi in the new robot

This ticket involves re-enabling the ublox communicator and configuring the chip when the hardware is available. 

### Acceptance criteria

- [ ] Integrate u-blox into new robot
- [ ] Make sure it works

### Blocked By
Not having ublox board/new mainboard rev

**Comment by jonathanlew** [comment]
out of date given move to jetson nano
