### ISSUE TITLE
Implement Kicker and Chipper Firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2080]
### Description of the task

The power board provides an interface to charger/discharge capacitors so that we can kick and chip. This ticket involves 

*implementing the functions in `charger.c/h` to charge and discharge the capacitors.
`CHARGE_PWR_BRD` pin is the one we should be using, talk to electrical to figure out how we are supposed to toggle that pin.

* implement the kick/chip functions in `chicker.c/h`
* implementing the break beam to support auto kick/chip

Power board interface:
![image](https://user-images.githubusercontent.com/31548846/118371952-d67f7880-b563-11eb-880a-00fafc5d9e96.png)

Break beam interface: 
![image](https://user-images.githubusercontent.com/31548846/118372373-2cedb680-b566-11eb-9e3d-80ef0c61d58c.png)

### Acceptance criteria

- [ ] Implement charger.c/h
- [ ] Implement the chicker.c/h functios
- [ ] Test!

### Blocked By
The app layer, we need the ability to safely e-stop and discharge before implementing this change.

**Comment by liambontkes** [comment]
Breakbeam functionality:

1. Interrupt triggered whenever the Breakbeam is broken.
2. Function to poll the Breakbeam's state (for robot diagnostics).

**Comment by jonathanlew** [comment]
out of date given move to power board mcu
