### ISSUE TITLE
Decouple primitive manager from FreeRTOS

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2082]
### Description of the task
Currently the primitive manager has preproccessor macros to switch between different semaphore implementations. 
We can simplify the code and make it more maintainable my making the primitive manager more portable

Couple ways we could do this: 
1. implement a wrapper around a semaphore, and move the complexity of switching the underlying implementation there
2. get rid of the semaphore altogether, and leave it up to the task/thread to synchronize

### Acceptance criteria

- [ ] Remove `Freertos.h` from primitive manager in the app layer
- [ ] Test

### Blocked By
N/A

**Comment by jonathanlew** [comment]
out of date given move to linux for robot os
