### ISSUE TITLE
Update Function Names and Comments in geom/util.*

### ISSUE THREAD

**Issue by jessicahe21** [UBC-Thunderbots/Software#209]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
While refactoring the geometry classes, it was found that some function names and comments in `geom/util.*` are difficult to understand and sometimes wrong. It could be an enhancement to review and update those one day, maybe during some sort of massive code cleanup. 

**Describe the solution you'd like**
Members familiar with the old code can be a great help to potentially understanding and helping with updating those function names and comments.

**Comment by jsn0716** [comment]
Now included in #959
