### ISSUE TITLE
Firmware HAL Bugs

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2095]
One ticket to track all HAL related firmware bugs and good resources that talk about them/provided fixes for them

## Known Issues to be addressed:
- [ ] https://community.st.com/s/question/0D53W00000m0xZRSAY/code-generation-and-eth-descriptor-count
- [ ] https://nadler.com/embedded/newlibAndFreeRTOS.html

## Really good resources:
-  https://community.st.com/s/question/0D50X0000BOtfhnSQB/how-to-make-ethernet-and-lwip-working-on-stm32
-  https://community.st.com/s/question/0D50X0000C6eNNSSQ2/bug-fixes-stm32h7-ethernet
-  https://community.st.com/s/article/FAQ-Ethernet-not-working-on-STM32H7x3
-  https://stmh7.com/001-the-ethernet-hal/

**Comment by jonathanlew** [comment]
out of date given move to jetson nano
