### ISSUE TITLE
Integrate INA266 Power Monitor firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2097]
### Description of the task

As the robot comes together, we need to re-configure the I2C peripheral and integrate it with the new firmware

Currently the power monitor firmware is disabled because it blocks any other code from running if the power monitor isn't connected 

### Acceptance criteria

- [ ] Enable power monitor firmware
- [ ] Integrate into main board 

## Blocked By
N/A

**Comment by jonathanlew** [comment]
we're no longer using the INA266 firmware
