### ISSUE TITLE
Property to Uniquely Identify Thunderbots E-stop Arduino 

### ISSUE THREAD

**Issue by amrm3lm** [UBC-Thunderbots/Software#2119]
### Description of the task
When our full system is run, we search available serial ports for the Estop Arduino based on the properties of Arduino UNOs. It would be better if we could program a USB property to our Estop Arduino to uniquely identify it. 

### Acceptance criteria

- [ ] add property to current Estop
- [ ] Verify that full system is able to form serial connection based on that property

### Blocked By

#2070

**Comment by jonathanlew** [comment]
Adding a property seems to involve changing the VID and PID (https://stackoverflow.com/questions/442833/forcing-driver-to-device-match), which seems too invasive
