### ISSUE TITLE
Fix Goalie Corner Cases

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2147]
### Description of the task
There are some corner cases with the goalie: 
* if the goalie transitions into the dribble state, it will not be restrained to the defense area and will chase the ball anywhere
* If a ball teleports behind the goalie, the goalie will bump the ball into the net

### Acceptance criteria

- [ ] fix bugs listed above

**Comment by SpeedyPetey** [comment]
I've been told, the fix for this has already been merged in.
