### ISSUE TITLE
Add numeric ID to Primitives

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#220]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
In the old AI, each primitive is represented by a numeric ID as part of an enum. This ID is sent over radio in order  
**Describe the solution you'd like**
Port over the enum from the old AI, and add a function that returns an enum for each primitive.
I will put up a WIP PR from my radio branch for reference (edit: #221).
@garethellis0 has suggested the visitor pattern for this instead, see discussion in #221, also see @MathewMacDougall's comment below

**Describe alternatives you've considered**
Might consider a mapping from enums to strings, but requires more discussion.

**Additional context**

**Comment by MathewMacDougall** [comment]
We may not need an explicit mapping from enums to strings if we implement #159 . Both the string and the enum value can be sent in the `Primitive.msg` messages. And then #217 could always use the enums instead of strings.
