### ISSUE TITLE
Handle Robot Statuses from Radio

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#222]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
Statuses like cap voltages, battery voltage, temperatures, etc. are returned from the robot over radio. These statuses can be displayed in the visualiser and/or logs to aid in debugging robots.

**Describe the solution you'd like**
There are callbacks in the dongle class that handle robot status data. We can use the existing robot status handling code (in `mrf/robot.cpp`) to translate these into readable data, and then publish them from the radio_communication node.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by MathewMacDougall** [comment]
If the radio encoding/decoding is the same and used by both the software and firmware, it would make sense to put it in `shared_util` so we only need the code in one place, and both firmware and software will be using the same version. The existing firmware will need to be moved to the new repo first @Tim1520
