### ISSUE TITLE
Robot announcements

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2225]
### Description of the task

The Jetson Nano doesn't have a screen and monitoring tshark or the router page to figure what IP it got is pretty annoying to do repeatedly, we need a more robust way of knowing which robots are online and what IP they received. 

A simple solution is for the robot to broadcast a packet on that network indicating that its online with some useful information. 

### Acceptance criteria

- [ ] Write a python program that broadcasts a packet on the network
- [ ] Define a proto for the broadcast packet (it should contain, robot id, robot ip, mac address to begin with)
- [ ] Broadcast packet every 2 seconds (you should figure out how to get the broadcast IP programatically)
- [ ] Write a corresponding python function that can run on the host/AI computer that blocks for 4 seconds and returns all the protos that were broadcasted.

### Blocked By
N/A

**Comment by LiCody** [comment]
Closed with PR: https://github.com/UBC-Thunderbots/Software/pull/2238
