### ISSUE TITLE
Enemy robots obstacle size changing when friendly robot is in close proximity

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#2227]
### Description of the task
When friendly robot is close to an enemy robot, the enemy robot obstacle size reduces so the friendly robot attempts to move closer, then the obstacle size grows back to regular size making the friendly robot path plan back. This results in the friendly robot not settling down to one position. This problem can be recreated by enabling and running `SimulatedThetaStarTest.DISABLED_test_theta_star_robot_and_dest_in_different_obstacle test`. This bug can also be seen in `SimulatedDribbleTacticPushEnemyTest`.
![robot_obstacle_size_changing](https://user-images.githubusercontent.com/28585597/128290622-be9c8a1b-6c6f-4b1f-8e53-0bfe34ab8b5b.gif)

### Acceptance criteria

- [ ] Fix the oscillation so the friendly robot is able to move close to enemy robots without the obstacle size constantly switching
- [ ] Enable the disabled `SimulatedThetaStarTest`s
- [ ] Add more tests

**Comment by jonathanlew** [comment]
this won't be a problem with the new motion planner
