### ISSUE TITLE
Handle Robot Charge state

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#223]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
In the old AI, the desired robot charge state (whether the capacitors are charged, discharged, or floating) is encoded into the radio packet before sending. 

**Describe the solution you'd like**
A brief digging around suggests that the charge state is always in FLOAT unless the play state is in HALT. As plays are quite far off from now, this may be a low priority issue.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by MathewMacDougall** [comment]
Based on previous empirical experience, it seems like the charge state is always _CHARGED_ unless the Play state is in halt? Is that what you meant?
