### ISSUE TITLE
Clean up vector of vector of Tactics

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2242]
### Description of the task
Last year, we experimented with returning a vector of vector of Tactics from Plays to have more control over priority and reduce oscillations, but it didn't achieve its goals, so it can be removed to simplify things

### Acceptance criteria

- [ ] Replace vector of vector of Tactics with a vector of Tactics

**Comment by amrm3lm** [comment]
wasnt this still helpful for assigning tactcs when our robots had yellow/red cards?

**Comment by jonathanlew** [comment]
I don't recall making special behaviours for yellow/red cards. Do you have an example?

**Comment by amrm3lm** [comment]
in robocup we changed the order of vectors for `shoot_or_pass` play so that 2 `crease_defenders` were always assigned first. We did this to prioritize `crease_defenders` since not all tactics could be assigned when we were down multiple robots (due to yellow/red cards)

**Comment by jonathanlew** [comment]
can't it be implemented without the single layer of vector?

**Comment by akhilveeraghanta** [comment]
This tiered assignment thing tried to paper over the underlying assignment issue but it didn't work

If this ticket involves updating STP then its not a 1 story point, i.e `{{tactic1}, {tactic2, tactic3}} -> {tactic1, tactic2, tactic3}`

if its just `{{tactic1}, {tactic2, tactic3}} -> {{tactic1, tactic2, tactic3}}` then 1 story point makes sense


edit: Flagging as Triage until the scope is resolved a bit more, please remove when the scope is updated

**Comment by amrm3lm** [comment]
I looked at `stp.cpp` again and realized that yes any vector can work fine

**Comment by jonathanlew** [comment]
vector of vector is actually useful, so not going to clean this up
