### ISSUE TITLE
Log when a play is applicable but whose invariants don't hold

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2248]
### Description of the task

We choose which Play to run by checking whether `Play::isApplicable()` is true in our current gameplay. Then, we keep running the play as long as `Play::invariantHolds()` is true. This means that `Play::isApplicable()` should normally be more restrictive than `Play::invariantHolds()`.

It would be very weird if we had a situation where `Play::invariantHolds()` is false when `Play::isApplicable()` is true, so we should know when that happens.

Use the logger module to log a debug message when this behaviour happens during our gameplay. It probably makes the most sense to write this message in `STP::calculateNewPlay()` (but maybe `STP::updateAIPlay()` makes more sense).

### Acceptance criteria

- [x] Write a `LOG(DEBUG)` message including the name of the play and a message telling us that the `Play::invariantHolds()` is false when `Play::isApplicable()` is true.

**Comment by jonathanlew** [comment]
closed due to #2280
