### ISSUE TITLE
Make ROS nodes interrupt-based

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#227]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
Our ROS nodes should only run when the callbacks are triggered, rather than poll all the time.
* The `network_input` should only process and publish data when it is received from the network
* The `AI` node should only make a new decision when it receives new data
* The `grsim_communication` node should only send new commands when it receives new field data or new primitives
* Same as above for `robot_communication`

**Describe the solution you'd like**
Rather than have a `main` function with an infinite loop, move the logic to the callback functions and call `ros::spin()` rather than `ros::spinOnce()` in the loop.

**Describe alternatives you've considered**
Leaving things as they are. This should be a better solution that makes managing timestamps easier (no need to update them without new data), and reduce the load on people's CPUs (as per #153 )

**Additional context**
None

**Comment by garethellis0** [comment]
Moving this to the Work Jar because this has become a debilitating issue where there's 100% CPU usage all the time for some team members.
