### ISSUE TITLE
Normalize the timestamping system

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#228]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
After the change in #179 we now have several timestamping systems in use. We should normalize our useage of timestamps to a single system.

Depends on #227 since managing timestamps will be easier after the nodes are callback-based.

**Describe the solution you'd like**
We should typedef `double` to `Timestamp`, and use this as the timestamp standard. Remove the old AITimestamp class (that wrapped std::chrono), and remove our use of std::chrono.

**Describe alternatives you've considered**
Using a different timestamping system like std::chrono. We should use the t_capture values so everything is as close to the "real world" timestamp as possible.

**Additional context**
None

**Comment by MathewMacDougall** [comment]
One thing I just realized is that the `ssl game controller` (the replacement for refbox) uses a different timestamping system than `SSL Vision`. Rather than defining a time in seconds since the "epoch" of when the application started, the SSL Game Controller uses a UNIX timestamp, in microseconds. The `.proto` file is [can be found here](https://github.com/RoboCup-SSL/ssl-game-controller/blob/master/pkg/refproto/ssl_referee.proto).

This may pose problems if we need to synchronize SSL Vision data or internal state with the Game Controller Commands. I don't think this is _currently_ an issue, as our `GameState` class doesn't use the timestamp (even though it's in the ROS message). @jordanzliu FYI.

I'm going to try take a look at what RoboTeam Twente did. I suspect they just don't deal with the Game Controller timestamp (as our `GameState` is based off their code).

@henrymliu @garethellis0 FYI

**Comment by garethellis0** [comment]
I suspect that your assumption is correct. It makes a lot more sense to base decisions off of the timestamps of the data that is the primary decision driver.
