### ISSUE TITLE
Implement ESP32 one-shot pulse firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2407]
### Description of the task
Resources from Dannon on discord:

https://circuitcellar.com/research-design-hub/projects/a-multipurpose-signal-generator/

This person used the LED PWM block to do it, and he has example code (gave code a read, not exactly sure how the LEDC block turns off PWM

https://www.buildlog.net/blog/2017/11/esp32-step-pulse-experiments-with-timers/ 

Another method, they also give you access to the interrupt registers (on overflow with the output compare timer), so we could use the interrupt to disable the PWM 

### Acceptance criteria

- [ ] Figure out how to triggler a pulse of a given width on a gpio pin using an ESP32
- [ ] Create a wrapper function that can take any pulse width and trigger the timer
- [ ] If possible, test fw on powerboard!

### Blocked By
Somewhat by powerloop firmware (where to put the code), but prototyping/testing is not blocked

**Comment by LiCody** [comment]
Forgot to close with PRs for powerloop
