### ISSUE TITLE
Thunderscope: Arbitary Plot Widget

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2411]
### Description of the task

We have a lot of variables across the code base that are more useful as real-time scrolling plots. 

This is a brand new feature for thunderscope, and will be critical for debugging.

We prototyped a basic version of this for the thunderscope prototype (see performance plots below), which might be worth looking at.

![123123123123](https://user-images.githubusercontent.com/31548846/149849265-9fa15ff0-cf2b-4f6f-8e4d-b5d8c5116a9f.gif)

Here is the code: https://github.com/akhilveeraghanta/Software/blob/5ce066a7320d24c04d4f22de57f3fc2a4cae8028/src/python_tools/thunderscope.py#L246

### Acceptance criteria

- [x] Create a protobuf that can store a name-value pair
- [x] Populate that proto with some variable (performance hz is a good one) and LOG(VISUALIZE) it
- [x] Create the python widget to handle incoming arbitrary named values.
- [x] The plot should  have a 10 second window, and should scroll left as time goes on.
- [x] Make sure the legend shows all the plots and hide/show works
- [ ] **Strech goal**: it would be cool, if the legend was next to the plot rather than on-top, and the values stayed hidden by default when they popup.
- [ ] **Another strech goal**: Its nice to have the performance plot to always be there, and the abitrary plot widget be another plot. So it would be nice if we could instantiate this widget with filters, the performance widget would just plot anything with Hz in its name (or if you can think of a better way to have 2 widgets, one with just Hz and the other with all that works too)

### Blocked By
N/A

**Comment by nimazareian** [comment]
After further testing with libraries that use the GPU to plot (e.g. VisPy), it seems like a better and simpler approach to use a third party application such as PlotJuggler to plot real time values, as they seem more optimized while also providing more useful built-in features. PyQt based libraries such as VisPy do have the benefit of being integrated right into Thunderscope, however, they do not provide any special features that we would find useful. Additionally, Vispy does not have built in support for stacked plots, requiring us to use third party libraries to modify the data to have the effect of stacked plots. Finally, integrating VisPy into Thunderscope resulted in a 5-7 second increase in launch time which is to significant, specially for simulated tests and Thunderscope constantly relaunching.
The code for the VisPy testing can be found here: https://github.com/nimazareian/Software/blob/nima/vispy_testing/src/software/thunderscope/common/proto_plotter.py
