### ISSUE TITLE
Update Primitive proto to take in a Path instead of destination

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#2418]
### Description of the task
`MovePrimitive` proto currently only takes a single `destination` point. Replace this with a `Path` proto so we can pass full paths down to the robot. 

### Acceptance criteria
- [ ] Replace `destination` with `Path path` in `Primitive.proto`
- [ ] Update all occurrences of `destination` with path, including in HRVO

### Should be done after
#2373

**Comment by jonathanlew** [comment]
re-opened due to missing integration into hrvo
