### ISSUE TITLE
Fix Floating Point Errors with Er Force Simulator

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2419]
### Description of the task
There are SIGFPE errors when using Er Force Simulator. They should be fixed but this can be done in parallel with integrating simulated tests.

### Acceptance criteria

- [ ] Fix Floating Point Errors with Er Force Simulator
- [ ] re-enable sigfpe checking in tests

**Comment by itsarune** [comment]
Haven't seen this in a while
