### ISSUE TITLE
Add path files to binary in systemd

### ISSUE THREAD

**Issue by amrm3lm** [UBC-Thunderbots/Software#2443]
### Description of the task

While systemd is setup on the Nanos, the location of the paths to the binaries that need to be run have not been added. The files can be hardcoded, or a config file can be made and imported by the appropriate systemd directives. 

### Acceptance criteria
Add path to the following files: 

- [ ] announcement.service
- [ ] announcement_watcher.service
- [ ] ui.service
- [ ] ui_watcher.service
- [ ] tftp.service
- [ ] tftp_watcher.service
- [ ] redis.service
- [ ] redis_watcher.service

### Blocked By
#2432

**Comment by jonathanlew** [comment]
resolved by https://github.com/UBC-Thunderbots/Software/pull/2517
