### ISSUE TITLE
Use encoder boards to calibrate motors

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2451]
### Description of the task

Once we starting running Thunderloop on boot, we can't have the encoder initialization in series with everything else
Imagine we boot the robot while holding it or setting it down on the edge of a table, we don't want it to drive off

We need to figure out the best time to run it

Couple options:
* make the user press a button on the LCD explicitly to initialize
* initialize on the first move primitive
* or both

### Acceptance criteria

- [ ] Figure out best time to initialize encoder (something that is not on boot/when the program is run)
- [ ] Remove inline encoder init from the motor service and call it somewhere better

### Blocked By
N/A

**Comment by itsarune** [comment]
the encoder calibration process became an indicator of Thunderloop status, so this task isn't relevant anymore
