### ISSUE TITLE
Test geneva drive firmware

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2458]
### Description
- Source both geneva endstops
- Source geneva encoder
- Implement prototype fw that can move the geneva system to a fixed angle
- Figure out where the encoder even is?
- Write fw to read the encoder data
- Figure out endstops + write fw to trigger an interrupt on endstop
- Figuring out how many encoder pulses it takes to move from one fixed slot to another
- When we start, we need to spin the motor in 1 direction until the endstop is triggered to home the geneva
- By default it should be in center slot 3

![image](https://user-images.githubusercontent.com/31548846/152617716-7c5d3f98-7f7a-4d57-9a2e-222eeb262e9c.png)

**Comment by itsarune** [comment]
Geneva has been deprecated
