### ISSUE TITLE
Proj Path Planner: Profiling EnlsvgPathPlanner

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2489]
### Description of the task

In this task, we'd profile the EnlsvgPathPlanner and figure out which module is most expensive (in terms of time).

The deliverable for this issue would be the profiled call graph telling us the most expensive functions. We'll use this and talk about it in the meeting to see how we can improve the code to be faster.

If you want to focus on only running one test, you'd disable every test except one. You do this by appending `DISABLED`_:
`TEST_F(TestEnlsvgPathPlanner, DISABLED_test_enlsvg_path_planner_empty_grid)`

### Acceptance criteria

- [ ] a screenshot of a EnlsvgPathPlanner test call graph (ideally one involving start and/or end inside an obstacle)

**Comment by jonathanlew** [comment]
https://github.com/UBC-Thunderbots/Software/issues/2506 and https://github.com/UBC-Thunderbots/Software/issues/2507 were created
