### ISSUE TITLE
Port the rest of our geometry and utility functions from the old code

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#25]
We will need all of our geometry and utility functions from the old code, including the different shapes, lines, and all the functions used to find intercepts etc. These should be brought into the new code.

**Comment by jordanzliu** [comment]
do we have any use for Hungarian? its only usage is in unit tests right now

**Comment by MathewMacDougall** [comment]
No, it would have been from an old attempt at optimizing tactic assignment but as far as I'm aware was never used. We don't have a use for it now so I wouldn't bother porting it.
