### ISSUE TITLE
Handling MotionConstraint::HALF_METER_AROUND_BALL & MotionConstraint::AVOID_BALL_INTERFERENCE

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2504]
### Description of the task

Currently, the new motion planner will not handle HALF_METER_AROUND_BALL and AVOID_BALL_INTERFERENCE motion constraints correctly. Since these constraints are dynamic (they move around), they shouldn't be handled by the GlobalPathPlanner. Using these constraints passed into the GlobalPathPlanner most likely wouldn't work properly.

### Acceptance criteria

- [ ] Re-design motion constraints so that static and dynamic obstacles so that they can be handled by the global path planner & hrvo respectively

**Comment by jonathanlew** [comment]
merged with https://github.com/UBC-Thunderbots/Software/issues/2602
