### ISSUE TITLE
proj_motion_planner: Replace LinearSpline2D with std::vector<Point>

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2506]
### Description of the task

By using LinearSpline2D, we do unnecessary computations in our path planning architecture. We can get away by using std::vector<Point>

### Acceptance criteria

- [ ] Replace using `Path = LinearSpline2D` with `using Path = std::vector<Point>` in path_planner.h
- [ ] Fixing all the build issues that occur

**Comment by jonathanlew** [comment]
resolved by #2661
