### ISSUE TITLE
proj_motion_planner: Rewrite findClosestUnblockedCell using a K-d tree

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2507]
### Description of the task

Since we're precomputing fields in the EnlsvgPathPlanner, we can get performance benefits when finding the closest unblocked point by precomputing our grid using a K-d tree.

### Acceptance criteria

- [ ] Investigate K-d tree libraries or solutions
- [ ] Investigate if we can come up with a solution that works with HRVO's K-d tree and Enlsvg's path planning K-d tree needs
- [ ] Implement it

**Comment by JoshuaWu7** [comment]
Removing issue, see #2749 for more general route
