### ISSUE TITLE
Tune realism of the Er Force Simulator

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2512]
### Description of the task
The Er Force Simulator should be tuned to match reality. 
The default values of ball restitution/friction for example is 1.f/1.f, which is unrealistic and more reasonable numbers have been plugged in. However, this should be tuned with IRL experiments

### Acceptance criteria

- [ ] Perform live experiments
- [ ] Tune Er Force using some calibration tests

**Comment by nimazareian** [comment]
After porting `CreaseDefenderTacticTest` to ErForceSim, `CreaseDefenderTacticTest.test_chip_ball` fails due to the ball not reaching the defender because of high friction. 
This test should be re-enabled as a part of the friction fix.

**Comment by nimazareian** [comment]
Closed as a part of #2653
