### ISSUE TITLE
Find Direct and Indirect Passes for a Robot

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2523]
### Description of the task
Given a Robot, the World, and whether the robot is friendly or enemy, calculate the direct passes and indirect passes available to the robot assuming it had possession of the ball at the ball interception point. By direct passes, we mean line of sight to friendly/enemy robots depending on which team that robot is on. By indirect passes, we mean passes that could be executed by chipping. For all passes, the receiving robot should have some space around it where there are no opposing robots. This threshold should be passed in with a reasonable default value, e.g. robot radius. It's a useful evaluation for quickly evaluating good actions if we're under pressure, without invoking the pass generator.

### Acceptance criteria

- [ ] Create a findDirectPasses function
- [ ] Create a findIndirectPasses function

**Comment by itsarune** [comment]
Resolved by #2561
