### ISSUE TITLE
Configure and Announce Robot Constants

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2526]
### Description of the task
One idea to support a hybrid fleet is to have robots be configured with the robot constants that match its hardware through a deployment tool, and then on boot up and periodically, the robot will announce its robot constants, so that AI can create robots with the right robot constants. Rather than sending and receiving all robot constants, which is currently not a protobuf, we could send and receive a model number

### Acceptance criteria

- [ ] as titled

**Comment by itsarune** [comment]
Closed: not a priority right now
