### ISSUE TITLE
Thunderscope: save and load docks 

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2529]
### Description of the task

Pyqt lets us save dock configurations and load them:

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/dockarea.py

### Acceptance criteria
- [ ] Build in dock save/load feature show in the example above
- [ ] Figure out how to presist that between thunderscope runs (you might need to use the `pickle` python library to save the state into `~/.config/tbots` 

### Blocked By
N/A

**Comment by jonathanlew** [comment]
resolved by https://github.com/UBC-Thunderbots/Software/pull/2576
