### ISSUE TITLE
Build the logic for the console

### ISSUE THREAD

**Issue by qgolsteyn** [UBC-Thunderbots/Software#255]
### Description of the task

Add logic to receive and log messages from /rosout

### Outline the task in more detail

This work is needed to implement the console of corner_kick. We should add a new saga and reducer called `console` which receives messages from /rosout using the actions defined in `actions/ros.ts`

### Acceptance criteria

- [ ] Subscribes to /rosout
- [ ] Receives messages from /rosout and adds them to the Redux state

**Comment by qgolsteyn** [comment]
You will need to create a new reducer and saga object with a separate state.

**Comment by qgolsteyn** [comment]
Essentially, you want the saga to subscribe to the rosout topic and the reducer to add messages to the state when receiving actions of type ros_NEW_MESSAGE with ros topic /rosout.

**Comment by MathewMacDougall** [comment]
Just to clarify, where is this going to show up in the Visualizer and what is the purpose? This is different from the `Annunciator/Robot status` messages right?

`/rosout` is going to contain *_ALL_* messages published to the system, which includes all ROS messages (`Ball`, `Team`, `Primitives`, etc.) AND all output from our `LOG` statements. Unless some super-fancy filtering is done, the `Ball`, `Team` and similar messages will drown out anything useful (like the LOG calls).

I think it might be preferable to publish `LOG` message to their own topic and just display those? This can still be separate from the `ROBOT_STATUS` messages.
