### ISSUE TITLE
Visualize Ball and Robot Speed Threshold

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#2556]
### Description of the task
The Simulated PyTest Ball and Robot Speed Threshold validation needs to be visualized

### Acceptance criteria

- [ ] as titled

**Comment by akhilveeraghanta** [comment]
Look at software/simulated_tests/robot_speed_threshold.py
and software/simulated_tests/ball_speed_threshold.py 
and implement the TODOs on line 37
