### ISSUE TITLE
Handheld Controller Integration

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2562]
Could be integrated with robot diagnostic widgets. The example demo branch send a primitive every time a controller event is triggered (e.g. joystick moves), which is probably too much. But from some testing, it also didn't seem to cause any problems.

**Comment by itsarune** [comment]
Code for this exists on a demo branch, blocked on #2721 before integration

**Comment by nimazareian** [comment]
Branch using `Xbox360Controller` library: https://github.com/nimazareian/Software/tree/nima/xbox_demo
