### ISSUE TITLE
Add polygon shape support for VisualizerMessenger

### ISSUE THREAD

**Issue by FSXAC** [UBC-Thunderbots/Software#258]
Sending polygons from Ai to visualizer is currently not supported. Implement the `drawPoly` method in `Util::VisualizerMessenger` class to enable sending shape messages for polygons.

### Acceptance Criteria
- [ ] C++ code can call the VisualizerMessenger drawPoly method and send a vector of vertices
- [ ] VisualizerMessenger constructs the shape message for the layer.

**Comment by MathewMacDougall** [comment]
This needs to be implemented on the AI side? Some more detail here would be great. You can use the new templates in https://github.com/UBC-Thunderbots/Software/pull/245 for reference.
