### ISSUE TITLE
Add pre-determined drawing layers in VisualizerMessenger to documentation

### ISSUE THREAD

**Issue by FSXAC** [UBC-Thunderbots/Software#259]
In VisualizerMessenger, any shape could could be drawn to a set of pre-defined layers. The layers are referenced by name. The names should go somewhere more accessible (in the doc).

**Comment by garethellis0** [comment]
Can we close this in favor of https://github.com/UBC-Thunderbots/Software/issues/268?

**Comment by FSXAC** [comment]
Sure thing. Closed.
