### ISSUE TITLE
Thunderscope: Implement dragging robots

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2593]
### Description of the task
Currently we can't easily drag individual robots easily because we don't support the teleport command, sending set world state commands repeatedly is not a great experience.

Also be able to add and remove robots (maybe using right click on the robot)

We should add support for teleport robot protos and use that to drag robots around on the page.

### Acceptance criteria

- [ ] implement teleport_robot functionality in er_force_sim
- [ ] add dragging robot feature to world_layer
- [ ] add it to the help popup in thunderscope.py

### Blocked By
N/A

**Comment by williamckha** [comment]
Resolved by #3033
