### ISSUE TITLE
Thunderscope: Colour Palette

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2595]
### Description of the task
* we don't explicitly pull from a color palette, It would be nice to have a unified pallete
* can maybe look into the palletable library

### Acceptance criteria

- [ ] Look at all places we use colors in thunderscope (any calls to mk.Pen and mk.Brush)
- [ ] Create a system to provide colors to these places
- [ ] If everyone agrees on a pallete, then it can just be in the colors.py file.

### Blocked By
N/A

**Comment by jonathanlew** [comment]
we should have a default palette but then ppl can customize the palette to their liking

**Comment by williamckha** [comment]
Closing this, we have consolidated all colors into `constants.py`
