### ISSUE TITLE
Make Kickoff Friendly Play better

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2612]
### Description of the task

Currently KickoffFriendlyPlay chips the ball in the opposition half as soon as NORMAL_START is issued. Make KickoffFriendlyPlay do something more intelligent.

### Acceptance criteria

- [ ] Create a Play FSM for a new KickoffFriendlyPlay
- [ ] Validate it using a simulated pytest
- [ ] Ensure that KickoffFriendlyPlay transitions smoothly to OffensePlay using Inter Play Communication

**Comment by itsarune** [comment]
part of the PR #2695, which is yet to be updated

**Comment by williamckha** [comment]
Closed in favour of #3287
