### ISSUE TITLE
Global Path planner doesn't respect motion constraints

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2621]
### Description of the task

![](https://user-images.githubusercontent.com/31548846/167345316-48537bfe-4b7a-4972-ba3e-eb2e4eb8862d.gif)

Robots don't seem to respect the motion constraints, they path plan through the friendly and enemy defense areas.

### Acceptance criteria

- [ ] make sure robots have their motion constrained

### Blocked By
N/A

**Comment by jonathanlew** [comment]
resolved by https://github.com/UBC-Thunderbots/Software/pull/2637 and/or https://github.com/UBC-Thunderbots/Software/pull/2623
