### ISSUE TITLE
Update plots to use the GPU through OpenGL libraries

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#2634]
### Description of the task

We need to plot a lot of data at 60hz and the CPU based plotting widgets are too slow to keep up. 
So we use a 3D OpenGL widget and limit the mouse movements to _not_ include any 3D orbit/rotations.

Currently, we also limit zooming in and out using the scroll wheel because the grid would need scale with the zoom based on the FOV and other things. We would also need to adjust the axis markings to scale accordingly. (Similar to how the grid lines on the field widget currently automatically scale) 

This requires a non-trivial amount of work, and a bit of scoping is required before diving in (hence the difficulty 13)

### Acceptance criteria

- [ ] Implement the wheel event in `GLViewWidget2DPlot` to allow zoom
- [ ] Dynamically update the axis labels on wheel event
- [ ] Dynamically update the grid (i.e similar to how the field widget does it + aligned with the axis labels)

### Blocked By
OpenGL Plotter PR

**Comment by nimazareian** [comment]
Here's Akhil's initial OpenGL implementation: https://github.com/akhilveeraghanta/Software/blob/akhil/opengl-plotter/src/software/thunderscope/arbitrary_plot/named_value_plotter.py
It requires support for zooming and scaling axis.

I've been playing around with VisPy library for 2D plots. This library by default utilizes OpenGL and has support for zooming + scaling axis, but it requires a bit more work to support multiple overlayed plots.
Additionally, we should use Qt's threading to have the plots run in parallel to the rest of thunderscope so it doesn't slow down if we plot more. 
An example: https://www.youtube.com/playlist?list=PL2OQ8odJIDfPU67ML2k-ldvgtISoxJE8b

**Comment by nimazareian** [comment]
Explained here: https://github.com/UBC-Thunderbots/Software/issues/2411#issuecomment-1396612622
