### ISSUE TITLE
Rename `logger/init.h` to `Logger.h`

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#267]
**Describe the bug**
Due to how it evolved, we currrently define the logger in `logger/init.h`, we should rename this to `logger/Logger.h`.

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
NA

**Additional context**
NA

**Comment by garethellis0** [comment]
File no longer exists.

**Comment by MathewMacDougall** [comment]
Yes it does, in `src/software/util/logger/init.h`
