### ISSUE TITLE
Create a General EnumString Class

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#268]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
Create a `EnumString` class that allows for us to create a compile-time enum with corresponding methods to lookup the enum values to strings (ie. with macros and/or templating). This will be important in allowing us to interface to the visualizer, which runs primarily off strings.

This will be a generalization of the enum-string conversion stuff added in #251.

Note: name of this class is poor and should be changed.

**Describe the solution you'd like**
- [ ] Implement `EnumString` class or similar
- [ ] Use newly created class in the `VisualizerMessenger` class to allow us compile time checks with the the layer enum (currently just a list of string).

**Describe alternatives you've considered**
Runtime enum to string conversion. Ideally we want compile time checks, so this is out.

**Additional context**
NA

**Comment by garethellis0** [comment]
The first answer on https://stackoverflow.com/questions/28828957/enum-to-string-in-modern-c11-c14-c17-and-future-c20 is probably what we want.

**Comment by MathewMacDougall** [comment]
Replaced by #857
