### ISSUE TITLE
Update variables in ER Force sim to use snake_case

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2718]
### Description of the task

ER Force simulator is a physics simulator made by another Div A team in robocup. We use their simulator to simulate games in our simulated test environment as it incorporates random noise that allows us to stress test our gameplay. We want to eventually incorporate and maintain our own version of the simulator but currently we have it sitting in our external libraries folder.

One major problem is that their implementation uses camelCase for variable names while we use snake_case. This ticket would involve converting these variables into snake case. For example (`localInertia` would become `local_inertia` in si`mrobot.cpp` and `overlappingPairCache` would become `overlapping_pair_cache`)

### Acceptance criteria

- [ ] Navigate to Software/src/extlibs/er_force_sim and browse the `.h` and `.cpp` files found inside those directories
- [ ] Identify offending variables and update them to use snake case
- [ ] Fix any build issues that come up when running `bazel build //software/...` in the `Software/src` directory

**Comment by AdenC123** [comment]
Talked about this with Nima- it will cause massive merge conflicts since so many variable names are changed, so it will be left as is. Also, we will want to keep it updated with ER Force changes.
