### ISSUE TITLE
Implement a way to see recent packet loss in network service

### ISSUE THREAD

**Issue by LiCody** [UBC-Thunderbots/Software#2727]
### Description of the task
Currently, we have a way of calculating packet_loss in `network.cpp` however it is currently an averaged count over however long were sending primitives but we want it to be useful for detecting sudden packet loss. 
possible idea: "we should make a count that checks how much packet loss we're seeing in the last 100 or so packets"

### Acceptance criteria

- Change calculation in `network.cpp` to calculate "recent" packet loss[ ] 

### Blocked By

Robocup cleanup

**Comment by raymond212** [comment]
@LiCody Is it possible that the packets are received out of order? If so, should the out of order packets be considered as lost packets?
