### ISSUE TITLE
HRVO: Investigate DS/Alg to find the Nearest Neighbors to an Agent

### ISSUE THREAD

**Issue by JoshuaWu7** [UBC-Thunderbots/Software#2749]
### Description of the task
We need to investigate a good data structure and algorithm that allows each agent to find its "K" nearest neighbor(s). HRVO currently uses a KD-tree implementation however we don't know if that's the route we want to take. 

Starting Points:
* https://en.wikipedia.org/wiki/K-d_tree
* https://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf
* https://dspace.mit.edu/bitstream/handle/1721.1/123119/1128186935-MIT.pdf?sequence=1&isAllowed=y

### Acceptance criteria

- [ ] Experiment and test the candidate option that could find the K nearest neighbors
- [ ] Performance test the current KD-tree implementation and candidate implementation

### Blocked By
N/A

**Comment by nimazareian** [comment]
Resolved in #2784
