### ISSUE TITLE
Investigate communication between Jetson and ESP32 DevKit using I2C

### ISSUE THREAD

**Issue by LiCody** [UBC-Thunderbots/Software#2756]
### Description of the task
- I2C is one of our planned back up communication protocol for communicating for the power service. This should just be an initial investigation into feasibility and performance no integration needs to be done. 

This may require modifying the device tree (hopefully not)
You can use the Arduino IDE to flash the ESP32 and hopefully there is program where you can send and receive messages on the jetson or you can write a small c++ program or python script for the jetson

### Acceptance criteria

- [ ] How fast can this run
- [ ] Does this use interrupts on ESP32 side

**Comment by itsarune** [comment]
I believe UART was fine this year, @LiCody can say more
