### ISSUE TITLE
Change Robot UI to use a button instead of a rotary encoder

### ISSUE THREAD

**Issue by LiCody** [UBC-Thunderbots/Software#2768]
### Description of the task
- Robot UI currently uses a rotary encoder to navigate screens/menu but due to issues with the rotary encoder robot UI is disabled. Instead we are planning to use a button to navigate screens/menus. 

### Acceptance criteria

- [ ] Modify Robot UI to use buttons instead of rotary encoder

**Comment by itsarune** [comment]
UI board has no UI
