### ISSUE TITLE
Break coupling between Simluator and Agent in HRVO

### ISSUE THREAD

**Issue by Bvasilchikov** [UBC-Thunderbots/Software#2771]
### Description of the task

Currently, HRVO was imported as-is to the codebase. Right now the code is heavily coupled together, and it is hard to make changes. It is also hard to read and understand how it works. 

- Remove `Simulator` dependence in `Agent`
- Refactor time_step to be passed into `Agent.update()` as a parameter instead
- Change the way `reached_goals` is updated

### Acceptance criteria

- [ ]

**Comment by nimazareian** [comment]
Additionally should add dynamic time_step to `PrimitiveExecutor::stepPrimitive` and remove time_step constant. Related to #2855

**Comment by nimazareian** [comment]
#2814 and subsequent HRVO PRs resolve this
