### ISSUE TITLE
Merge Network Logger messages to reduce log spam (LOG INFO, DEBUG, WARNING)

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2775]
### Description of the task

When we use the NetworkLogger to log messages from the robot, we notice that the messages begin to lag significantly when they get sent on the network when we have spammy messages. This ticket involves updating `network_sink.cpp` so that we detect spammy messages and reduce the frequency they get sent so that we don't overload the network.

One such way we can merge together messages could be:
Current logger output:
INFO << Breakbeam detected
INFO << Breakbeam detected
INFO << Breakbeam detected
INFO << Breakbeam detected
INFO << Breakbeam detected

Updated logger output:
INFO << Breakbeam detected (5)

We want to:
- merge repeated messages together
- repeated messages that happen after a certain time threshold still get sent (as repeated)

One such way of accomplishing this is to store the last message is Network Sink and use a counter to count how often the message comes in, and then send it IF we receive a new message different from the last message OR if we pass a timeout value

### Acceptance criteria

- [ ] repeated messages get merged together, reducing log spam
- [ ] tested on robots

**Comment by nimazareian** [comment]
Should consider looking through G3Log's documentation and features for possible approaches to reducing spam. Although these may not be exactly what we're looking for, features such as `LOG_IF` and log filtering could be good starters.
Repos:
https://github.com/KjellKod/g3log => https://github.com/KjellKod/g3log/blob/master/docs/API.md
https://github.com/KjellKod/g3sinks
