### ISSUE TITLE
Validation for ball placement play

### ISSUE THREAD

**Issue by PhilD71** [UBC-Thunderbots/Software#2780]
### Description of the task
Currently, `ball_placement_play_test.py` does not have any validation. Validation needs to be added for this test (lines 84 and 88). A good starting point would be looking at `ball_placement_play_test.cpp`

### Acceptance criteria

- [ ] Always validation for ball placement
- [ ] Eventually validation for ball placement

**Comment by itsarune** [comment]
merged via #3046
