### ISSUE TITLE
Integrate FreeKickPlay and KickoffPlay into OffencePlay

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2798]
### Description of the task

In our current architecture, it's difficult to define clear transitions out of Kickoff and FreeKick into OffencePlay and becomes a bit arbitrary on when we transition to OffencePlay. So this ticket involves integrating KickoffPlay into OffencePlay so that we don't have to worry about this situation.

You can take a look at this closed PR for inspiration (or as a basis) #2695 
### Acceptance criteria

- [ ] Integrate FreeKickPlay and CornerKickPlay into OffencePlay
- [ ] Ensure current free kick play and corner kick play tests are passing (supplement the tests if you feel it is necessary)

**Comment by raymond212** [comment]
Closing in favor of separate implementations of FreeKickPlay #2953 and KickoffPlay.
