### ISSUE TITLE
Thunderscope: Verify/Test that Thunderscope launches without error in CI

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#2804]
### Description of the task
Currently, CI does not test that Thunderscope can be launched without an error, thus, we can have a broken Thunderscope be merged with the master branch without the reviewers noticing. 
A simple approach to this would be to test that Thunderscope can be launched in CI and that it can remain running for X seconds. A further improvement would be to check for Python/C++ error messages in that time frame. Prior to trying these approaches, the assignee should research whether other approaches exist for testing PyQt/PyQtGraph applications in Python, as that might simplify the testing and could enrich our ability to test with a greater detail.
Should also look into testing frameworks for PyQt such as: 
- https://pytest-qt.readthedocs.io/en/latest/intro.html
- Or `unittest` with `QtTest`

### Acceptance criteria

- [ ] If Thunderscope can not be launched or has an error, CI should notice it and let the author and reviewers know.
- [ ] Add a review mode argument to thunderscope_main which disables estop (and also protounix io probably for safety) and allows CI to run without estop and makes it easier for reviewers to test robot diagnostics

**Comment by itsarune** [comment]
This environment variable could help in CI: https://stackoverflow.com/a/55446762

By default, Thunderscope will error out on launch in CI

**Comment by nimazareian** [comment]
#2788 should now detect most tscope errors
