### ISSUE TITLE
Write unit tests for REDIS client

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2805]
### Description of the task

all the tests in `redis_client_test.cpp` are disabled. Convert these tests to use a test fixture (TEST_F), and create a process running `redis-server` so that we can have the redis client tested in CI

You can use the google test fixture's `SetUpTestSuite()` method to make a process that runs

### Acceptance criteria

- [ ] Existing tests pass and are enabled
- [ ] We test `getSync`, `getAsync`, `setSync`, `setAsync`, `setNoCommit`, `syncCommit`, `asyncCommit`

**Comment by williamckha** [comment]
Closing this for now, given that we might nuke redis (#3315)
