### ISSUE TITLE
Add DynamicParameters for parameters in the Particle Filter

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#281]
### Description of the task
Replace the constants in the Particle Filter with tuneable parameters

### Outline the task in more detail
The Particle Filter from our old code is being initially moved to our new system as part of #198. The code can be found in `network_input/filter/particle_filter.*`. In order to make the code compile, the old Parameters (at the top of the `.h` file) where temporarily changed to constants.

These constants should be changed back to Parameters that use our new DynamicParameter system.

* Create a Parameter of the appropriate type for each. They should go in their own namespace/group called "ParticleFilter"
* You will need to add the parameter to the following files. You should be able to copy what is already there and modify it based on the existing examples.
    * `software/param_server/cfg/Params.cfg`
    * `software/util/parameter/dynamic_parameter.cpp/.h`

### Acceptance criteria

- [ ] Create a Parameter of appropriate type for each constant at the top of `particle_filter.h`
- [ ] Replace the constants at the top of `particle_filter.h` with the new parameters

**Comment by Thunderbots** [comment]
This was closed by #413
