### ISSUE TITLE
Investigate sharing constants between C++ and Python for Jetson nano and ansible script

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2819]
### Description of the task

ask @LiCody 

software constants are currently pybinded so that thunderscope can modify the values in real-time.

Display code wants to use py_constants for redis keys and other values. This requires the following addition the BUILD file
```
data = ["py_constant.so"]
```
However when this is added, an error occurs on the Jetson
```
ImportError: .../py_constants.so.4: cannot open shared object file: No such file or directory
```
I believe this is due to py_constants being compiled for x86 due to some funkyness in pybind11_bazel rules

Related to this, attempting to compile a py_binary with above data field while also specifying --cpu=jetson_nano leads to the below error.

```
No such file or directory # include <aarch64-linux-gnu/python3.8/pyconfig.h>
```

### Acceptance criteria

- [ ]

**Comment by williamckha** [comment]
Python has been removed from our robot software and the UI display is no more
