### ISSUE TITLE
Thunderscope: Add toolbar for controlling AI vs AI simulation

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#2842]
### Description of the task
We should look into adding a `QToolbar` (or other types of widgets) that has simulation control buttons (e.g. Pause/Play simulation, speed up/down playback, add robot, ...)
Could have a look at this for some ideas: https://realpython.com/python-menus-toolbars/

### Acceptance criteria

Some ideas for features can include:
- [ ] Play/Pause controls
- [ ] Speed up/down playback controls
- [ ] Add/remove robots
- [ ] Normal start game controller command/shortcut

**Comment by williamckha** [comment]
Resolved by #3033, #3132, #2827, #3198
