### ISSUE TITLE
Use Different Multicast Channels for different purposes

### ISSUE THREAD

**Issue by sauravbanna** [UBC-Thunderbots/Software#2861]
### Description of the task

Currently, the same Multicast channel is used for World, Robot Status, Robot Logs, and Primitive Set data. This can cause that channel to have too much data sent to it which can cause delays.

### Acceptance criteria

- [ ] Use 4 separate Multicast channels from the ROBOT_MULTICAST_CHANNELS list for each of the above data
- [ ] Change Robot Communication to consume these 4 values
- [ ] Change Thunderloop and Network Service to consume these 4 values

**Comment by itsarune** [comment]
@nimazareian @sauravbanna  Is this still a priority? I don't know how beneficial this change would be

**Comment by nimazareian** [comment]
Ya I don't think it's needed anymore. 

Long term it could be cool to have multicast channel dynamically configurable within the GUI though
