### ISSUE TITLE
bashrc commands

### ISSUE THREAD

**Issue by walnka** [UBC-Thunderbots/Software#2867]
alias rdiag="~/Software/src/tbots.py run thunderscope --run_diagnostics --interface {interfacenum}"
alias tmuxr="tmuxinator"
# Custom Functions (by Willem)
fnano() {
  myssid=$(iwgetid -r)
  if [ "$myssid" != "tbots" ]; then
    echo "Not on tbots wifi"
    return 1
  fi
  cd ~/Software/src/
  bazel run //software/jetson_nano/ansible:run_ansible --cpu=jetson_nano -- --playbook deploy_nano.yml --hosts 192.168.0.20$1 --ssh_pass {password}
}

fpower() {
  myssid=$(iwgetid -r)
  if [ "$myssid" != "tbots" ]; then
    echo "Not on tbots wifi"
    return 1
  fi
  cd ~/Software/src/
  bazel run //software/jetson_nano/ansible:run_ansible --cpu=jetson_nano -- --playbook deploy_powerboard.yml --hosts 192.168.0.20$1 --ssh_pass {password}
}

**Comment by itsarune** [comment]
Implemented a version of this in #2947
