### ISSUE TITLE
Remove assumption that ObstacleFactory returns ball obstacle for HALF_METER_AROUND_BALL constraint

### ISSUE THREAD

**Issue by Bvasilchikov** [UBC-Thunderbots/Software#2871]
### Description of the task

Currently, when there is a `MotionConstraint::HALF_METER_AROUND_BALL`, we assume that the obstacle factory correctly creates a ball obstacle, and inserts it as the first obstacle in the obstacles list. We don;t like to make this assumption since the caller has no guarantee the list is populated.  We should update the implementation so that we can be sure that a ball obstacle is returned.

### Acceptance criteria

- [ ]  this line doesn't exist: `new_obstacles[0]`

**Comment by williamckha** [comment]
I don't think this is an issue anymore
