### ISSUE TITLE
Use obstacle pointers instead of list indexes for candidate velocities in HRVO Agent

### ISSUE THREAD

**Issue by Bvasilchikov** [UBC-Thunderbots/Software#2872]
### Description of the task

Currently, the main implementation of the HRVO algorithm relies on creating candidate velocities, by considering the intersections of 2 velocity obstacles. However, that class that holds the information,  `CandidateVelocity`, (intersection velocity, and the 2 intersecting obstacles), uses integers to index into an obstacle list. This means we have a class with indexes into a list. It would be better, if we instead could directly reference the obstacles, by usage of pointers.

### Acceptance criteria

- [ ] Candidate velocity doesn't index into a obstacle list, and uses obstacle pointers instead

**Comment by williamckha** [comment]
HRVO has been removed
