### ISSUE TITLE
Frequently check for motor faults in MotorService

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#2895]
### Description of the task
We should check for motor faults frequently and take appropriate action when a fault is noticed. E.g. When a motor has `shortdet_u` fault (may happen due to fast acceleration), it stops running and will not run again until the motor is resetted manually in code or thunderloop is restarted. It is important for us to automate this process (in a safe manner) s.t. during an actual game the robot can continue functioning without manual resetting. When other faults are noticed, we may want to shutdown the robot to avoid further damage.
Note that checking for faults requires SPI transfers which is slow on the Jetson, so to have thunderloop running at max frequency, we would want to spread out fault checks over different iterations of thunderloop, or possibly grouping SPI transfers. 

Observed faults should be added to the MotorStatus message. It would be nice to have some sort of red outline/flashing/... in Robot View widget to show when there is an `ErrorCode` or when there's a fault. This is really important functionality for all software and elec to have while field testing and debugging.

### Acceptance criteria

- [ ] Detect if any of the 5 motors fault without significantly slowing down thunderloop frequency
- [ ] Take appropriate action when a fault is detected
- [ ] Visualize fault/error code in Robot View widget

**Comment by itsarune** [comment]
+ check if the encoder is connected
