### ISSUE TITLE
No protos being received after Stop command

### ISSUE THREAD

**Issue by williamckha** [UBC-Thunderbots/Software#2936]
### Description of the task

Occasionally after a `Stop` command is sent, all robots stop responding. Looks like no protos are received

![image](https://github.com/UBC-Thunderbots/Software/assets/60044853/a2190e47-cfbd-4c08-b912-f3e9264adf4d)

### Acceptance criteria

- [ ]

**Comment by williamckha** [comment]
Closed in favour of #2941

**Comment by nimazareian** [comment]
Next time you see this bug, could you check to see whether yellow fullsystem has also crashed? (Can look at the proto plotter in the Yellow Fullsystem tab)

**Comment by williamckha** [comment]
> Next time you see this bug, could you check to see whether yellow fullsystem has also crashed? (Can look at the proto plotter in the Yellow Fullsystem tab)

Yeah yellow fullsystem also crashed
