### ISSUE TITLE
Implement nearest_enemy Evaluation Function

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#296]
### Description of the task

Implement the nearest_enemy evaluation function.

### Outline the task in more detail

We would like to implement the nearest_enemy evaluation function in our new codebase. It is currently defined in the old codebase at `ai/hl/stp/evaluation/team.cpp`. With respect to the interface of this function (ie. what it takes and received), there should be similar types available in the new codebase. That said, it is possible that this function takes a type that is larger then it needs (ex. taking a `World` when it just needs a `Team` and a `ball`). Basically, try to use the smallest type you possible can; this will make it easier to test, review, develop, and work with in the future. 

Note: The function name should be `camelCase` according to our convention. We should also update the `nearest_friendly` function to follow the same convention

### Acceptance criteria

- [ ] Function nearest_enemy is implemented
- [ ] Function nearest_enemy is unit tested

**Comment by MathewMacDougall** [comment]
Re-opening since this wasn't actually completed.
