### ISSUE TITLE
Add geometry function to step along perimeter of rectangle/polygon

### ISSUE THREAD

**Issue by williamckha** [UBC-Thunderbots/Software#2994]
### Description of the task

We want to write an algorithm that can step a given `distance` along the perimeter of a rectangle. Specifically, starting from some given point `start` along the perimeter, we want to return the point that we will land on after stepping `distance` along the perimeter. 

Ideally, we should abstract this so that we can step along the perimeter of any polygon.

<img src="https://github.com/UBC-Thunderbots/Software/assets/60044853/ca8b35fc-997c-46b4-a821-4c0936b28e0a" width=60%>

### Acceptance criteria

- [x] Implement `stepAlongPerimeter` in a new file under `software/geom/algorithms`  
    ```cpp  
    stepAlongPerimeter(const Polygon polygon, const Point start, double distance)  
    ```  
- [x] You may need to implement some helper functions (e.g. determine the polygon segment on which a given point lies)
- [x] Positive `distance` should step clockwise and negative `distance` should step counter-clockwise
- [x] Write tests for `stepAlongPerimeter`

**Comment by nimazareian** [comment]
@PhilD71
