### ISSUE TITLE
We should track enemy robots and try to block their shots during freekicks

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#3011]
### Description of the task
During freekicks, we have 3 robots that remain stationary allowing the enemy robot to easily pass/shoot in between them. We should update this such that we have robots blocking specific pass/shot lanes. This could also involve tracking the robots orientation, as the way it's facing is likely the direction it's going to kick in. It's important to be careful that robots can easily chip over us as well...
#2970 from robocup introduces a version of this change.

### Acceptance criteria

- [ ] Update enemy freekick play 
- [ ] Add simulated tests for this

**Comment by itsarune** [comment]
@Andrewyx By the SSL robocup rules:

`When the free kick command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 0.5 meters distance away from the ball (the same distance as in stop). `

Currently, in EnemyFreeKickPlay, we violate this 0.5 m rule. This should be fixed as part of this task.
