### ISSUE TITLE
Remove blocking pop up messages from Thunderscope

### ISSUE THREAD

**Issue by nimazareian** [UBC-Thunderbots/Software#3013]
### Description of the task
Opening new pop up windows using `.exec()` causes the main Qt even loop to be blocked which then freezes all of thunderscope GUI. We should consider using `.show()` instead, possibly with [`setWindowModality()`](https://doc.qt.io/qt-6/qmessagebox.html#setWindowModality).

More explanation: https://stackoverflow.com/questions/38265985/qdialog-show-vs-open

This is most prevalent in the battery warning pop up (I think): 

https://github.com/UBC-Thunderbots/Software/blob/dfe80320f11fdf8bd0b2acb271ae35dd9d6d1220/src/software/thunderscope/robot_diagnostics/robot_info.py#L327-L346

and the newly (to be added at the time of writing this) `RobotCrashDialog`.

Though we should be careful with this as well, since during an actual game, we're not allowed to touch our laptop to close popups that are blocking the rest of the UI. So we should also consider alternatives to popups that can show the similar msg and it disappears automatically (such as a custom _toast_ GUI components) or have the option to click and show the msg...

### Acceptance criteria

- [ ] 

### Blocked By
Not necessirally blocked, but part of the changes are in #2940

**Comment by nimazareian** [comment]
@sauravbanna can this ticket be closed?

**Comment by nimazareian** [comment]
> @sauravbanna can this ticket be closed?

Following up on this

**Comment by williamckha** [comment]
I think we can close this, there are no more usages of `QMessageBox` other than for the Thunderscope help dialog
