### ISSUE TITLE
Fill ERROR_CODE field in RobotStatus msg

### ISSUE THREAD

**Issue by Bvasilchikov** [UBC-Thunderbots/Software#3020]
### Description of the task
We support sending error messages, such as high cpu temperature, in the RobotStatus proto msgs we send from the robot, however, they are not filled in. We should have some thresholds for when we should fill these fields. 

Should also see if there are other error messages we can/should include.

### Acceptance criteria

- [ ]

**Comment by Andrewyx** [comment]
Code Written:
- Added func to Thunderloop to poll errors. Sends notif once upon detection of each type.
- Added Constant for Jetson max temp (80 C)

Changes:
- Removed Dribbler Temps --> Redundant as in other classes
- Reserved above in protobufs (enum 2)

Remaining Tasks:
- Testing on bots
