### ISSUE TITLE
Add logic to receive layer messages

### ISSUE THREAD

**Issue by qgolsteyn** [UBC-Thunderbots/Software#308]
### Description of the task

We want to receive messages from the AI and add them to the application state

### Outline the task in more detail

This work depends on #251. We should be able to receive messages from the DrawLogger and add them to the application state. We also need to override current data if the message we received pertains to a layer that we already have data for.

### Acceptance criteria

- [ ] Given we are connected to the AI, when we receive a new layer messages, then we should add it to the state 
- [ ] Given there is already data for a layer, when we receive a new layer message for that layer, then we should override the data with new information

**Comment by garethellis0** [comment]
Closing as no-longer relevent.
