### ISSUE TITLE
Persist key:value data in the visualizer

### ISSUE THREAD

**Issue by qgolsteyn** [UBC-Thunderbots/Software#311]
### Description of the task

We want a way, using Redux, to have data persist across application run of the visualizer.

### Outline the task in more detail

Using a Redux saga, we want to use what the browser offers us (probably local storage) to persist information across application run. For now, a simple way to persist string values should suffice.

Essentially, when I send a Redux action to save data, providing a key (or id) and a string to store, I should be able to retrieve said string by providing the key to Redux.

### Acceptance criteria

- [ ] Given I have a string to persist, when I send a key and the string to Redux, the string should be saved across application run
- [ ] Given I have a string to retrieve, when I request said string with the key, Redux should be able to provide it to me (probably through the state object)

**Comment by MathewMacDougall** [comment]
No longer relevant with new C++ Visualizer.
