### ISSUE TITLE
Fix KickoffEnemyPlay: Friendly robot enters enemy half during kickoff causing kickoff violation

### ISSUE THREAD

**Issue by suchirss** [UBC-Thunderbots/Software#3119]
### Description of the task

When testing KickoffEnemyPlay in kickoff_play_test.py, a friendly robot violates kickoff rules by entering the enemy half. During enemy kickoff, friendly robots are not allowed to enter the enemy half and the center circle. This can be seen through Thunderscope when running kickoff_play_test.py:

![KickoffEnemyPlay_fail_cropped](https://github.com/UBC-Thunderbots/Software/assets/65541635/b71f920b-8f45-4d22-bca1-215a0613b252)

The high level goal is to adjust KickoffEnemyPlay so that our robots stay outside of the enemy half and center circle for the duration of kickoff. 

To test this validation, run kickoff_play_test.py (once it is merged) and see if robots stay outside of the enemy half + center circle during enemy kickoff. You can do this through the command: ./tbots.py test //software/ai/hl/stp/play:kickoff_play_test -t

Note that you will have to adjust kickoff_play_test.py to run enemy tests, as this is currently commented out:
![image](https://github.com/UBC-Thunderbots/Software/assets/65541635/e734c665-5a3e-4224-9509-3cb750e7bd30)

### Acceptance criteria

- [ ] friendly robots do not enter enemy region when running KickoffEnemyPlay
- [ ] kickoff_play_test.py passes tests when is_friendly_test is False

### Blocked By

#3123

**Comment by nimazareian** [comment]
My changes should fix this. Though it is also blocked by #3105
