### ISSUE TITLE
Bump python version

### ISSUE THREAD

**Issue by Bvasilchikov** [UBC-Thunderbots/Software#3175]
### Description of the task

Those are rookie numbers

### Acceptance criteria

- [ ]

**Comment by Mr-Anyone** [comment]
This is done. Do you just want me to pull?  Which version do you want?

**Comment by Bvasilchikov** [comment]
Awesome - I was thinking 3.10 at least, but if you have latest then that's even better. Is it tested on both ubuntu 20 and 22? also might need to check wsl works, so if you can make a PR that would be a great start, thanks!

**Comment by nimazareian** [comment]
As part of this we should probably look into bumping up our Black python formatter as well, since right now it seems like it doesn't handle formatting f-strings very well.
