### ISSUE TITLE
Cleanup The CMakeLists.txt

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#318]
### Description of the task
Cleanup the `CMakeLists.txt` with a focus on reducing it's length by reducing the amount of duplication present.

### Outline the task in more detail

Currently the `CMakeLists.txt` is over 580 lines. Once #217 is completed we should be able to remove the inclusion of _every_ primitive in every that uses _any_ of the primitives (including the tests). Additionally, we should make a variable with the common libraries we use (`catkin_LIBRARIES` and `G3LOG` at the time of this writing) so that we don't duplicate the inclusion of them everywhere.

While you're at it, you may want to resolve #19.

### Acceptance criteria

- [ ] Consolidate things into variables if possible, in particular commonly used libraries
- [ ] Remove any unneeded inclusions of primitives in targets (probably mostly in test targets)

**Comment by MathewMacDougall** [comment]
We should also be able to remove any headers included  in the executables. These were included before in order for CLion to properly treat them as project files, but this has been fixed in later versions.

**Comment by garethellis0** [comment]
Yup, this is covered in #19, mentioned in the description above!

**Comment by MathewMacDougall** [comment]
Whoops didn't see that.

**Comment by MathewMacDougall** [comment]
No longer relevant with bazel
