### ISSUE TITLE
[Robot Software] Add message for soctherm: OC ALARM 0x00000001 on the Jetson Nano

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#3181]
### Description of the task

This error appears in the `dmesg` logs when the Jetson isn't getting stable power. elec should know when this happens.

1. Read the /var/log/dmesg file line-by-line
2. Do a string match of `soctherm: OC ALARM 0x00000001`
3. If the line contains this error, add a new ErrorCode (`UNSTABLE_POWER_SUPPLY`) https://github.com/UBC-Thunderbots/Software/blob/359d90e451e4aa60b99015a46f8edf7b9822f915/src/proto/robot_status_msg.proto#L71 to the robot_status_msg

### Acceptance criteria

- [ ]

**Comment by Mr-Anyone** [comment]
https://stackoverflow.com/questions/9533708/how-to-read-ring-buffer-within-linux-kernel-space
