### ISSUE TITLE
Add `NotImplementedError` for functions that'll be overridden in Python

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#3294]
### Description of the task

To prevent functions that we do not expect to be overridden to be executed in Python, we should raise a `NotImplementedError`

Here are the places (that I know about) where we should add this:
- [x] https://github.com/UBC-Thunderbots/Software/blob/3cc5a2d4c45205f3b0dc7eae6e85f328e2973160/src/software/thunderscope/gl/widgets/gl_toolbar.py#L31

### Acceptance criteria

- [x] Replace known instances of these abstract function with an implementation that raises a `NotImplementedError`

**Comment by Mr-Anyone** [comment]
I am pretty sure there is something called an abstract base class that  enforces this in python.

**Comment by williamckha** [comment]
> I am pretty sure there is something called an abstract base class that enforces this in python.

Yep https://docs.python.org/3/library/abc.html
