### ISSUE TITLE
Properly Implement += Operator for Point

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#340]
### Description of the task
The `+=` operator for `Point` does not work. 

### Acceptance criteria

- [ ] Confirm the `+=` operator for `Point` does not work as expected (adds, but does not assign)
- [ ] Fix the `+=` operator
- [ ] Confirm the `-=` operator for `Point` does not work as expected (does not compile)
- [ ] Fix the -=` operator
- [ ] Add some tests

**Comment by henryymliu** [comment]
@garethellis0 are you planning to work on this soon/is this urgent? this could be assigned to a newer member if not

**Comment by garethellis0** [comment]
I am not, please feel free to re-assign.

**Comment by MathewMacDougall** [comment]
I also wouldn't say this is urgent or critical for competition. @henrymliu we could put this further in the backlog and remove the `+=` operator for now?
