### ISSUE TITLE
Change Point2D type to geom::Point type in VisualizerMessenger for the draw polygon method

### ISSUE THREAD

**Issue by FSXAC** [UBC-Thunderbots/Software#341]
### Description of the task

Point2D is a ros message type, it should not be used as it breaks the abstraction. Use geom::Point in `VisualizerMessenger::drawPoly()` method instead.

Change all references of Point2D in VisualizerMessenger to use geom::Point

**Comment by garethellis0** [comment]
@FSXAC - was this resolved by #397?

**Comment by FSXAC** [comment]
Oops I must've forgotten I created this task when I merged the PR
