### ISSUE TITLE
Move old firmware to new repo

### ISSUE THREAD

**Issue by Thunderbots** [UBC-Thunderbots/Software#352]
### Description of the task

Move the robot firmware from the old GitLab repo to our new GitHub repo

### Outline the task in more detail

We need to move the robot firmware as-is to the new github repository. It should go in `src/thunderbots/firmware`. The `setup_firmware.sh` script will need to be added to our `environment_setup` folder. Most importantly, the CMakeLists.txt file will need to be moved and confirmed that is still works. It uses commands to flash the robot firmware.

### Acceptance criteria

- [ ] firmware is moved to `src/thunderbots/firmware`
- [ ] firmware setup script is moved to `environment_setup`
- [ ] Code builds and robots can be flashed

**Comment by garethellis0** [comment]
@MathewMacDougall - is this gonna get done? I'm taking it off the milestone for now.

**Comment by MathewMacDougall** [comment]
Not my highest priority this week, so that's fine.
