### ISSUE TITLE
A* navigator with boost graph and boost astar

### ISSUE THREAD

**Issue by Thunderbots** [UBC-Thunderbots/Software#356]
### Description of the task

Implement a simple A* navigator.

### Outline the task in more detail

The Boost library implements graphs and the A* algorithm, so we should use them to make our own A* navigator for the AI. This initial version does not need to avoid obstacles, but it should be able to return a path from a node near the starting location to the node near the ending location.

I'm not yet sure how to break this ticket down further as I don't know enough details about Boost::graph and boost::astar. How exactly they can be created and made to work together will need to be investigated.

For this ticket, all we want is to be able to create the graph from the `Field` object, without any obstacles. We should be able to provide some starting node and goal node, and have the algorithm generate a path.

### Acceptance criteria

- [ ] Create a boost graph from our `Field` object
- [ ] Use the Boost::astar to generate a path from the graph. It does not need to navigator obstacles for now

**Comment by MathewMacDougall** [comment]
Closing as the PR was closed since we moved to other planning algorithms and interfaces
