### ISSUE TITLE
Create a function to calculate final speed values from path segments

### ISSUE THREAD

**Issue by Thunderbots** [UBC-Thunderbots/Software#358]
### Description of the task

Implement a function to calculate final_speed values for path segments.

### Outline the task in more detail

Given 3 points that represent 2 connected line segments, this function should compute the final speed a robot shoudl have as it transitions between the two segments. This value will be used by the Navigator when creating MoveIntents so that the robot will not stop between planned path segments.

The value returned should be a function of the angle between the segments. For example, if the segments are nearly in parallel, then the final_speed value between the segments can be very high since the robot would not have to adjust mutch to transition between the segments. Conversly, if the second segment was tangent to the first (forms a right angle), the final_speed would be much lower so that the robot is able to slow down and transition between the segments without totally overshooting.

This function should go in a new `src/thunderbots/software/ai/navigator/util.*` file in the `Navigator` namespace.

A few unit tests should be written for this function, but not too many since we will need to validate this on the field later once we have a path planner completed.

### Acceptance criteria

- [x] Implement the function to calculate the final speed values
- [x] Write a few unit tests

**Comment by MathewMacDougall** [comment]
Closing as this was resolved in #389
