### ISSUE TITLE
Port an old Evaluation function to the new code

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#36]
### Description of the task

Move a single evaluation function from the old code to the new code.

### Outline the task in more detail

The Evaluation functions are what we use for our gameplay decisions. Pick a single evaluation function from the old code, move it to the new code, and add a few unit tests.

In the old code, the evaluation functions are found in `software/ai/hl/stp/evaluation`

You will need to create a new `evaluation` folder in the new code, in `software/ai/hl/stp/`

Because most of the old evaluations functions depend on one another, you will need to find an independent evaluation function. Ideally, one that only relies on classes we currently have available (`Robot`, `Ball`, `Point`, `Angle`). Note that the old functions may take a `World` datatype. This is just a class that wraps `Ball`, `Robot`, etc. Look at how it's being used to determine what the function actually needs.

Once you've chosen the function you want to move, copy-paste / re-implement it in the new code. Create a new file for the function and name it appropriately. Multiple evaluation functions live in each file so make sure the name is generic enough. Also make sure that the evaluation function is placed in a namespace called `Evaluation`

Eg. 
```
namespace Evaluation {
    // Your function here
}
```

*Make sure you comment the function and name it appropriately so we know what it does. Ask for help if you're not sure*

Finally, add a few unit tests for the evaluation function. Create a new 'evaluation' folder under the 'test` folder. Make a new file to test the new evaluation function, and implement a few unit tests.

### Acceptance criteria

- [ ] Create a new `stp/evaluation` folder
- [ ] Implement the evaluation function
- [ ] Create a new 'test/evaluation` folder
- [ ] Implement at least 3 unit tests for the evaluation function

**Comment by garethellis0** [comment]
#25 is closed

**Comment by MathewMacDougall** [comment]
Prioritized #49 over this in the short term for the September milestone. This actually can be bumped from the September milestone, since #24 still needs to be done and would benefit from more development time, since it's the trickier and more essential structure.

**Comment by henryymliu** [comment]
Evaluation functions in the old code are located in `software/ai/hl/stp/evaluation`
