### ISSUE TITLE
Refactor folders so we have a matching "test" and "src" folder

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#360]
### Description of the task
Refactor folders so we have a matching "test" and "src" folder.

### Acceptance criteria

- [ ] Move all code into a `src` folder
- [ ] Refactor the `test` folder so that it's structure mirrors the `src` folder in terms of where each test file is and what source file that test file is testing

**Comment by MathewMacDougall** [comment]
Resolved with migration to bazel
