### ISSUE TITLE
Add Tests For The PlayFactory

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#375]
### Description of the task
Add Tests For The PlayFactory

### Outline the task in more detail
Add unit tests for all publicly accessible functions in the `PlayFactory`.

### Acceptance criteria

- [ ] Add unit tests for all publicly accessible functions in the `PlayFactory`

**Comment by MathewMacDougall** [comment]
I'll likely be doing this as part of #24 , or right after.

**Comment by Thunderbots** [comment]
This was resolved as part of #403
