### ISSUE TITLE
Implement ratePass In PassGenerator

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#383]
### Description of the task
Implement the `ratePass` function in the `PassGenerator` class.

### Outline the task in more detail
We should roughly base the implementation of this on how it was done in the old code. See here for details: https://wiki.ubcthunderbots.ca/-LNDlFcpV2p--IwnWNlJ/software/passing

### Acceptance criteria

- [ ] `ratePass` in `PassGenerator` is implemented

**Comment by garethellis0** [comment]
@JamesPetrie - what was the logic behind rating risk based on both the enemy intercept risk and the distance of the enemy to the receive point of the pass? (in `enemy_risk.cpp` in the old codebase)

**Comment by JamesPetrie** [comment]
I think the idea with that was that there were two separate considerations: the probability of the ball getting to the passee, and the amount of space the passee has once the ball arrives.

This sort of distinguishes between the case where the enemy robot is really close to the passer, and the case where the enemy robot is close to the passee. Both might have an equally likely chance of interception, but you'd prefer the one where the location you're passing to is empty of enemies.

**Comment by garethellis0** [comment]
Ah perfect. Thanks for the context James!
