### ISSUE TITLE
Implement Communication to ROS Param Server w/ Visualizer to Start AI Logic

### ISSUE THREAD

**Issue by kelvinkoon** [UBC-Thunderbots/Software#392]
### Description of the task

Implement a way to communicate between the Visualizer and the ROS Param Server's information using ROSLib.js to start AI Logic.

### Outline the task in more detail

We should base it on getting and setting values in the ROS Param Server. New ROS actions will be created for getting and setting the values. The reducer will be used to manage state of these values from the ROS Param Server. 

The saga will be used to retrieve all parameters from the ROS Param server upon starting the application. Then, it will listen for updates from the ROS param server. 

The communication between both is going to be using rosbridge. 

### Acceptance criteria

- [ ] Create a sort of UI to set configurations
- [ ] Create action to retrieve information from ROS Param Server
- [ ] Create action to set information in the ROS Param Server
- [ ] Implement actions to communicate with ROS Param Server
- [ ] Have UI send actions (For instance, button click sends action to get ROS Params)

**Comment by MathewMacDougall** [comment]
Closing as this is replaced by #518
