### ISSUE TITLE
Refactor Geometry Classes For Readability

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#40]
Currently, we have several geometry classes with names like `Rect` and `Seg`. These are much less clear than names like `Rectangle` and `Segment`, and don't really save much space. We should rename them accordingly.

**Comment by garethellis0** [comment]
@MathewMacDougall - this is more my opinion then something we have to change, but I think it warrants attention.

**Comment by MathewMacDougall** [comment]
As part of this, I would also like to split the geometry classes into their own files. Currently `Rect` has its own file but most other shapes are all in the `shapes` file. We should be consistent, and I think they should all have their own files.
