### ISSUE TITLE
Implement path smoothing for navigator paths

### ISSUE THREAD

**Issue by jordanzliu** [UBC-Thunderbots/Software#401]
### Description of the task

Create a function that consumes a list of `Points` that forms a jagged path, and return a smoother path.

### Outline the task in more detail

Right now, A* will return a jagged list of points due to the fact that we are using a grid graph to find a path. Create a `NavigatorUtil` namespace and create a function that will remove as many points from the path as possible without intersecting any obstacles. 

### Acceptance criteria

- [ ] Create a function that will smooth a path

**Comment by MathewMacDougall** [comment]
No longer necessary with Theta*
