### ISSUE TITLE
Automatic cpp and cfg generation for DynamicParameters

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#412]
### Description of the task

Currently to add a parameter, we need to edit both a cfg file and a cpp/header file. This adds a lot of steps and complexity to something that should be simple to setup and use. 

This ticket involves implementing a code generator in python to generate both the cfg/cpp files from a yaml file, where all the parameters are defined in a specified format. 

Generate cfg and cpp from yaml for DynamicParameters

### Outline the task in more detail

- Depends on DynamicParameters

### Acceptance criteria

- [ ] YAML to CPP and CFG conversion works and has been verified
- [ ] Passes param exists in param server integration test
- [ ] Supports all 4 xmlrpc types
- [ ] Supports lists of parameters of same type
- [ ] Supports multiple pages of parameters
- [ ] Making sure that the parameter updates are seen across all the nodes.
- [ ] Documentation on the wiki on the structure of the parameters
- [ ] Readme on how to use the new setup

**Comment by garethellis0** [comment]
@akhilveeraghanta - is it realistic to get this in this week? I'll open the milestone for next week, but it's totally your judgement call.

**Comment by akhilveeraghanta** [comment]
I finished the core of the generation and tested it all that’s left is the Singleton, I’m hoping for a PR up tonight, if something comes up I’ll let you know


Edit: Ok yeah you are right, I am going to remove the milestone and update this ticket. Was a bit too optimistic.
