### ISSUE TITLE
Implement Catch Action

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#428]
### Description of the task

Create and implement the CatchAction

### Outline the task in more detail

The CatchAction is one level of abstraction above the CatchIntent. It should kick the ball at a given destination with some given speed, making sure to satisfy the preconditions of the CatchIntent.

### Acceptance criteria

- [ ] Implement the CatchAction
- [ ] Unit tests

**Comment by henryymliu** [comment]
I think the description is a bit wonky; "...kick the ball at a certain speed"

Anyways, this seems like an interesting one. I'm working under the assumption that `jcatch.c` is used in firmware... which seems incomplete when I read through the file. Did this work well last year?

The old catch action is just as sketchily written and doesn't seem to follow coroutines properly, which obviously will have to be done in this new version.

**Comment by henryymliu** [comment]
After some field testing, it has been determined that the firmware implementation is not working properly. Since this wasn't used in competition, I've moved this issue to the backlog pending a firmware primitive rewrite.
