### ISSUE TITLE
Implement Stop Action

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#430]
### Description of the task

Create and implement the StopAction

### Outline the task in more detail

The StopAction is one level of abstraction above the StopIntent. It should stop the robot (with the option to coast), making sure to satisfy the preconditions of the StopIntent.

### Acceptance criteria

- [ ] Implement the StopAction
- [ ] Unit tests

**Comment by akhilveeraghanta** [comment]
@MathewMacDougall should the stop action do any kicking?

**Comment by MathewMacDougall** [comment]
Whoops sorry that's more bad copy-pasta by me. No, it should just stop the robot. I've quickly updated the description.
