### ISSUE TITLE
Remove thread and locks from VisMessenger

### ISSUE THREAD

**Issue by FSXAC** [UBC-Thunderbots/Software#484]
### Description

Remove use of `std::thread` from `VisualizerMessenger` class. Refer to referenced comment below for details.

### Acceptance criteria

- [ ] VisualizerMessenger function exactly as same as before
- [ ] No fatal signal received error upon termination

> Ah, so this looks like we're not joining to the thread we have spawned. Basically if you destroy an `std::thread` object that is still running, it will call `std::terminate` and just kill your program. In this case that's somewhat OK, in that we were trying to stop it anyways, but this would be a serious problem if we ever tried to destruct a `VisualizerMessenger` in the middle of execution. The fix here is basically to tell the `std::thread` object that it's time to end in the `VisualizerMessenger` destructor, and then wait for it to end before destroying the `std::thread` object. I had to deal with this for the `PassGenerator`, checkout the destructor for that here (https://github.com/UBC-Thunderbots/Software/blob/master/src/thunderbots/software/ai/passing/pass_generator.cpp).
> 
> After thinking about this some more and reading up on the boost `tcp::acceptor` documentation, we could remove all threading stuff and just use `async_accept` instead of `accept`? Here's an example: https://stackoverflow.com/questions/1087199/boostasio-how-do-i-use-async-accept-to-accept-incoming-connections. This would remove all the threading and locking issues.

_Originally posted by @garethellis0 in https://github.com/UBC-Thunderbots/Software/pull/445#issuecomment-472439874_

**Comment by garethellis0** [comment]
@FSXAC - could you please fill out the issue template for this issue?

**Comment by FSXAC** [comment]
Yep, I'll get around to it soon

**Comment by MathewMacDougall** [comment]
Closing as this isn't relevant anymore, since we're using ROS to send binary data now.
