### ISSUE TITLE
Read and write to ROS Param Server using Visualizer UI

### ISSUE THREAD

**Issue by kelvinkoon** [UBC-Thunderbots/Software#518]
### Description of the task
Read the ROS Param Server's data by converting the YAML files's information to JSON and hydrate it into the state. 
Write to the ROS Param Server using the Service Request.

### Outline the task in more detail
The state should store the name, value, description, range, and type. The saga should fetch the JSON, hydrate the state (fetch the current value), and update the value (validate the value, update the ROS param server using the Service Request) and update the state.

### Acceptance criteria

- [x] Read the ROS param server and hydrate to state
- [x] Write to the ROS param server by sending a service request
- [x] Develop a rudimentary UI
- [x] Have UI dispatch actions to update the ROS param server and state

**Comment by MathewMacDougall** [comment]
@kelvinkoon @qgolsteyn is this now an improved version of #392? Seems to cover similar stuff, but now with the new YAML

**Comment by kelvinkoon** [comment]
> @kelvinkoon @qgolsteyn is this now an improved version of #392? Seems to cover similar stuff, but now with the new YAML

Yes, this is the updated version.

**Comment by MathewMacDougall** [comment]
Ok, I'll close #392 then
