### ISSUE TITLE
create "calcBinaryTrespassScore" utility function for circles

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#523]
### Description of the task

Create a trespass function that indicates the trespass score of a point with respect to a circle.

### Outline the task in more detail

Trespass scores indicate how far into a "bad region" a given point is. The higher the score, the more the point is "trespassing" in the region.

This function should return a value in the range [0,1] that indicates how much the given point is trespassing in the region given by the circle. The function signature should be something like the following:
`unsigned int calcBinaryTrespassScore(Circle c, Point p);`

The function should return a trespass score of 1 if `p` is inside the circle, and 0 otherwise.

The `binary` function from #521 can be used for the implementation

This function should go in the `src/thunderbots/software/ai/navigator/trespass.*` files.

### Acceptance criteria

- [ ] Implement the function
- [ ] unit test

**Comment by FSXAC** [comment]
Why is blocked by the unit step function issue?

**Comment by FSXAC** [comment]
Actually now that I come to think of it, once we implement `calcLinearTrespassScore`, couldn't the `calcBinaryTrespassScore` be like:

```
def calcBinaryTrespassScore(circle, point):
    return calcLinearTrespassScore(circle, point) > 0
```

**Comment by MathewMacDougall** [comment]
It was blocked since we were originally planning to use the `unitStep` function as an implementation. You're right about the alternative implementation (I didn't think of that), but if we already have the `unitStep` function we might as well use that since it's a bit more consistent.

**Comment by MathewMacDougall** [comment]
Closing because the current navigator doesn't need this. YAGNI
