### ISSUE TITLE
create "calcLinearTrespassScore" utility function for circles

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#525]
### Description of the task

Create a trespass function that indicates the trespass score of a point with respect to a circle.

### Outline the task in more detail

Trespass scores indicate how far into a "bad region" a given point is. The higher the score, the more the point is "trespassing" in the region.

This function should return a value in the range [0,1] that indicates how much the given point is trespassing in the region given by the circle. The function signature should be something like the following:
`unsigned int calcLinearTrespassScore(Circle c, Point p);`

The function should return a trespass score of 0 if `p` is outside the circle, and values that linearly increase to 1 when the point is exactly in the middle of the circle.

The `linear` function from #522  can be used for the implementation

This function should go in the `src/thunderbots/software/ai/navigator/trespass.*` files.

### Acceptance criteria

- [ ] Implement the function
- [ ] unit test

**Comment by FSXAC** [comment]
the function prototype should be something like `double calcLinearTrespassScore(Circle c, Point p);` where the return value is a floating point right?

**Comment by MathewMacDougall** [comment]
yup

**Comment by MathewMacDougall** [comment]
Closing because the current navigator doesn't need this. YAGNI
