### ISSUE TITLE
Properly Remove Expired Robots

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#530]
### Description of the task
Deal with issue caused by incorrectly removing robots from the teams in `network_input`.

### Outline the task in more detail
`network_input` throws an exception because we try to remove all robots older then a given value, but some robots have a timestamp that is greater then that value. We do a check to ensure this doesn't happen, but we only check against the id of the robot that we just received a packet for and there could be other robots on the team that have a different timestamp.

**Comment by MathewMacDougall** [comment]
This should be resolved
