### ISSUE TITLE
Use autokick_fired to determine when the Kick Action is done

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#580]
### Description of the task

The Kick Action currently checks the ball's velocity vector to determine if the robot has kicked the ball and the action is done. This should be upgraded to use the `autokick_fired` data from the robot status, since this will also very materialistically indicate if a kick has occured.

### Outline the task in more detail

The Kick Action should return done when the `autokick_fired` status has recently been true for the robot taking the kick.

### Acceptance criteria

- [ ] Use `autokick_fired` to calculate when the Kick Action is done
- [ ] Unit tests

### Blocked By
#1135

**Comment by garethellis0** [comment]
Marking as difficulty 13 because this will likely require some architecture changes to allow robot status to be exposed to actions.

**Comment by jonathanlew** [comment]
Not worth the effort since checking vision for a kick (ball movement) should be sufficient
