### ISSUE TITLE
Remove filterAndPublishVisionData wrapper function once we move to a better simulator

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#609]
Currently we have a wrapper function around the `filterAndPublishVisionData` function because grSim sends garbage packets that contain bad data from very far in the future. Once we are using a better simulator that doesn't do this, we can remove this wrapper function.

### Blocked By 
#768 #1135

**Comment by jonathanlew** [comment]
Note that after #768 and #1135 it will be called `publishVisionData` wrapper function since that layer will no longer do filtering
