### ISSUE TITLE
Robot Communication over Radio

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#63]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We kind of need an MRF backend to communicate with the physical robots.

**Describe the solution you'd like**
Port the MRF backend from the old code.

**Describe alternatives you've considered**
We could also rewrite it from scratch, but that would likely take a long time. 

**Additional context**
Breaking this down a bit:
- There is a libusb wrapper in `util/` that we should consider porting too. Additional classes in `util/` such as `NonCopyable` may also be useful to port over. Need to figure out where to put these.
- `Annunciator` is used for conveying messages from the field (ex. dead robots, hardware issues, basically whatever makes the dongle beep); this may have to be ported too and integrated into whatever logging system we come up with
- The old backend directly communicates with a `MRFRobot` instance; since we no longer have this and instead are using primitives only, this will have to be changed.
- `MRFRobot` has the packet encoding function, and some flag (`drive_dirty`) for `dirty_drive`, and keeps track of the charger state.
- It seems like `dirty_drive` is used to keep track of how many robots actually send primitives to the dongle, so it can adjust the packet size accordingly??? (`MRFDongle::submit_drive_transfer`)

**Comment by henryymliu** [comment]
Will update this more as I discover new things.

**Comment by MathewMacDougall** [comment]
Bumping to November milestone as this isn't critical for October. @henrymliu how's progress?

**Comment by henryymliu** [comment]
I think I can theoretically attach to the dongle now (need to verify on Saturday). Close to having something that can send primitives to the robots.

**Comment by henryymliu** [comment]
@MathewMacDougall good news: fixed the unfinished transfer issue, now we are officially able to send drive packets

bad news: this involved a hack, namely turning the backend_output node into a GTK application because the libusb wrapper callbacks use glib, which basically needs the GTK main loop :(

I think the long term plan would be to make a separate thread that handles libusb callbacks. This probably also means some synchronization, but it shouldn't be too bad.
In addition, we still need to figure out a) the vision thread and b) how the dongle is going to be shared across backend_input and backend_output

**Comment by MathewMacDougall** [comment]
That's great! You are a god.

Unfortunate about the hack, but at least it's isolated to a single, relatively small node (yay new architecture). I didn't realize `glib` was so reliant on `GTK`.

The vision thread is easy, assuming we can send vision packets in addition to drive packets (I remember they were different). The `backend_output` node can simply subscribe directly to the ball/team data published by the `backend_input` node and create a packet from that. That is the critical path between data input/output that skips all the AI logic processing time.

For dongle sharing, especially considering the potential complexity of these callbacks and synchronization, it might be worth putting the dongle entirely in it's own node. The dongle node can then listen for `Primitive` messages (or something even simpler, maybe a pre-encoded packet), and publish messages it receives from the robots. Can we receive messages yet?

@garethellis0 for thoughts on separating the dongle into it's own node.

**Comment by garethellis0** [comment]
Hmm, separating the dongle into it's own node seems like a fairly reasonable option, but I'd like to see what the hacky implementation looks like first. @henrymliu - could you point me at the branch you're doing this on (presumably on your fork)? 

With regards to the glib/gtk coupling, at least theoretically, I don't think they're really linked at all? Gtk might make it _easier_ to use glib, but we should totally be able to use it without it (I would think).

**Comment by henryymliu** [comment]
@MathewMacDougall I figured that was the only major change we need before supporting vision packets, I don't think that is too difficult to implement (although i might be busy for the rest of the term). 
Messages are... technically being received I think? It's just that I have nowhere to send them to for now (stuff like charger state, estop state, robot statuses). 
I'll have to think about the dongle node option a bit more, although it seems to work.

@garethellis0 Branch is on https://github.com/henrymliu/Software/tree/mrf_backend_test
The hack is in main.cpp in the backend_output node; basically we init a GTK application and start it in a separate thread before the ROS loop.

**Comment by garethellis0** [comment]
Oh man, there's a LOT of stuff here. I'm really struggling to get a handle on what's going on just because of the sheer volume of the diff. Not sure how you wanted to do this, but I'd suggest chopping that branch down to the minimum required stuff, then hopefully it should be a bit easier to figure out how we can do this without gtk.

**Comment by henryymliu** [comment]
Yep, I plan to cut some more stuff out later (esp. `Annunciator`, maybe `Property` too). The dongle class definitely could be trimmed/split up as well.
The `libusb` wrapper is also heavily integrated with GLib, so that's the first point to start decoupling.
