### ISSUE TITLE
Add C++ unit-test documentation to the wiki

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#64]
Would like someone to document unit tests on the wiki (specifically for C++ unit testing):
• What they are
• Why they are good / why we use them
• How to add them (where in cmake to add entries, where to add files)
• Good practices (aka the stuff we talked about with short, single-purpose tests and descriptive test names)

For now put this on a new page under the `Software` folder of the wiki

**Comment by garethellis0** [comment]
Added general unit testing documentation and C++ unit testing documentation. Re-scoped this ticket to not include C unit testing docs (since we haven't ported firmware over to the new repo yet) and opened #68 to track adding C unit testing documentation.
