### ISSUE TITLE
Determine how to estimate enemy passes when calculating enemy threat

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#642]
### Description of the task

Currently we had to disable accounting for friendly robots when estimating the number of passes is would take a robot to receive a pass from whichever robot currently has the ball, because it caused oscillations in the defense. When a friendly robot moved to block the pass, this changes where the pass may be received from so the robot moves again, and oscillates.

We should figure out a way around this, if we still think it's worth accounting for. Is there a smart way to ignore the robot "marking" an enemy receiver without making the code more complicated?

**Comment by jonathanlew** [comment]
blocked on possession stuff
