### ISSUE TITLE
 Add C unit-test documentation to the wiki

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#68]
Would like someone to document C unit tests on the wiki

Most of the work for this was already done in #64, but we're missing a section on adding C unit tests. It should be pretty similar to the section for adding C++ unit tests.

The unit testing section is under `Software` -> `Conventions` -> `Unit Testing` on the wiki

**Comment by garethellis0** [comment]
I think this was created when we had a different unit testing framework for C, but since we're using GTest now I don't think there's any reason to have separate docs.

**Comment by MathewMacDougall** [comment]
Can confirm this was for an old C unit testing framework with old firmware. No longer relevant.
