### ISSUE TITLE
Rename or Change the functionality of grsim_output.SendPrimitives

### ISSUE THREAD

**Issue by EvanMorcom** [UBC-Thunderbots/Software#742]
### Description of the task

grsim_output.sendPrimitives() send more than what the name suggests.

Either we rename the function or change the implementation so that the function only takes primitives as a parameter.

**Comment by garethellis0** [comment]
@MathewMacDougall - given current plans with the simulator, should we just close this?

**Comment by MathewMacDougall** [comment]
Leave it for now. The simulator currently won't cover all of grsim's capability (mainly manually doing stuff), so before we totally commit to nuking it I may take a little time to just simplify it a lot, since we don't need the "realism" which added complexity in the first place.
