### ISSUE TITLE
Merge "IndirectFreeKickPlay" into "DirectFreeKickPlay"

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#763]
### Description of the task
- Separate direct and indirect free kick plays (probably have a generic `FreeKickPlay` that they both extend)
- Delete `CornerKickPlay` and use `IndirectFreeKickPlay` instead.
  - This will require changing the cherry-pick region assignment to be more based on ball location
- `DirectFreeKickPlay` is going to be basically the same as `IndirectFreeKickPlay` except that it can check for direct shots.

### Acceptance criteria

- [ ] Make `IndirectFreeKickPlay`
- [ ] Make `DirectFreeKickPlay`
- [ ] Remove `CornerKickPlay` and use `IndirectFreeKickPlay` instead

**Comment by matthewberends** [comment]
There will be a rule change this year at robocup where only `DirectFreeKickPlay` are to exist as opposed to a separate `IndirectFreeKickPlay` so we should remove `IndirectFreeKickPlay`.

### Updated Description of the task
- Remove `IndirectFreeKickPlay` and replace it with a `DirectFreeKickPlay`
- `DirectFreeKickPlay` is going to be basically the same as the current`IndirectFreeKickPlay` except that it can check for direct shots.



### Acceptance criteria



- [ ] Remove `IndirectFreeKickPlay`
- [ ] Make `DirectFreeKickPlay`

### Blocked By

**Comment by garethellis0** [comment]
Sounds good, feel free to just directly update the issue description in the future.

**Comment by garethellis0** [comment]
@matthewberends - was this completed a while back?

**Comment by matthewberends** [comment]
> @matthewberends - was this completed a while back?

No this hasn't been done. This slipped under my radar over the break. Ill try to get it done this week
