### ISSUE TITLE
Redesign PassGenerator To Be Deterministic

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#766]
### Description of the task
Currently, `PassGenerator` is not deterministic because the optimization it uses occurs in a seperate thread. This is by-design so that it is performant in game scenarios, but it means that tests for it are quite flaky. We should redesign it to separate out the threading if possible (or at least add a compiler flag to disable it) and add a way to run it for a set number of iterations for the testing purposes.

### Acceptance criteria

- [ ] Seperate out threading from the `PassGenerator` class entirely, or failing that, add some sort of compile-time option to disable it
- [ ] Re-enable all `PassGenerator` tests and ensure that they pass.
- [ ] Consider: what about for other tests for plays that use the PassGenerator? We need to make those deterministic as well. This likely means we're missing some acceptance criteria here.....

### Blocked By
Dynamic params

**Comment by jonathanlew** [comment]
@garethellis0 is this done?

**Comment by jonathanlew** [comment]
> Gareth Ellis :penguin:  12:29 PM
Partly done. It's deterministic, but you need to pass a bool into the constructor, we needed the dynamic param changes to allow us to share some "deterministic" param between all the play configs that use the passgenerator

**Comment by garethellis0** [comment]
Thanks for following up on this @jonathanlew !
