### ISSUE TITLE
Move Old Code From Gitlab To Github And Mark As Deprecated

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#772]
### Description of the task
We have some old code on gitlab that people consistently have to go back to look at, even though it's not used. Migrate it to a github repo and prefix the repo name with `(Deprecated)`.

### Acceptance criteria

- [ ] Old "software" repo is migrated to a "(Depreceated) Software" repo on github
- [ ] README in "(Depreceated) Software" repo has a big warning about it being old and deprecated code.

**Comment by MathewMacDougall** [comment]
Done. See https://github.com/UBC-Thunderbots/Software-Deprecated
