### ISSUE TITLE
Change Tactics To Return Actions Instead Of Intents

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#773]
### Description of the task
Currently, tactics return intents by calling actions. However this can make it hard to test tactics, because you have to understand the behavior of the action the tactic is using in order to figure out what intent should be returned. As such, we should consider having tactics return actions, which can then be queried to get the next intent.

This has some issues:
- actions are stateful and use coroutines (so can't be copied easily while running)
- do you _really_ need to understand actions to have an expected output from tactics?

This ticket is to consider this idea, and file tickets if we decide to pursue it.

### Acceptance criteria

~- [ ] Decide to pursue this idea or not~
~- [ ] Figure out work required, if we decide to pursue~
~- [ ] File appropriate tickets for required work, if we decide to pursue~
- [x] Split `updateStateAndGetNextIntent` into `updateControlParams`, `updateWorldParams`, and `getNextIntent`
- [x] Write a visitor that can visit and update a given `Action` with a given `World` via `updateWorldParams`
- [x] Change Tactics to return actions
- [ ] Have actions be updated in `stp.cpp` via the visitor, then retrieve params from them instead of directly from tactics
~- [ ] File docs on why we don't just use setters instead of `updateWorldParams` and `updateControlParams` for `Tactic`'s and `Action`'s~

**Comment by MathewMacDougall** [comment]
Slightly related, while we're redesigning here we should consider how we can make the most guarantees about Tactics and Actions being given data they need. Sometimes right now our `execute` functions rely on data provided by `controlParams`, which means we need to check that data exists before we perofrm operations.

This leads to checks like
```
if(!enemy_threat) {
	// stop
}else {
	// do normal stuff
}
```

Ideally we don't want to perform these checks at all.

**Comment by garethellis0** [comment]
I'm going to start poking around at some implementation options for this

**Comment by garethellis0** [comment]
Notes from offline slack discussion:

• note down in docs why we don't have setters for `Tactics` or `Actions`
• split all `Action`'s into `setWorldParams` and `setControlParams`
• write a visitor for `Action` 's to update the world params


```
tactics = current_play.getTactics()
for (tactic in tactics){
   tacticUpdateVisitor.update(tactic)
}
actions = [tactic.getAction() for tactic in tactics]
for (action in actions){
   actionUpdateVisitor.update(action)
}
intents = [action.getIntent for action in actions]
```

<sub>[View in Slack](https://thunderbots.slack.com/archives/D75195G7Q/p1573276588006200)</sub>

**Comment by jonathanlew** [comment]
@garethellis0 Is this done?

**Comment by garethellis0** [comment]
Almost, some small changes required to wrap it up. Put it on the Feb 8th milestone.

**Comment by garethellis0** [comment]
@MathewMacDougall - how strongly do you feel about docs around this? Looking at the software architecture docs this seems like a bit too low level for that doc.

**Comment by MathewMacDougall** [comment]
Yea probably too low level for the architecture doc. In-code documentation should be good enough, or just make a ticket to doc it and we can revisit it.

**Comment by garethellis0** [comment]
Where in code would we put this? I can't think of a _super_ logical spot.

**Comment by MathewMacDougall** [comment]
I think `stp.h` is best, but I've made #1160 to tackle this later in a more comprehensive overview of STP in-code.
