### ISSUE TITLE
Update Play Architecture To Update World-Dependent Tactic Parameters Outside Each Individual Play

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#778]
### Description of the task
Currently we have to manually update the tactics each each play each time the play ticks, even if the parameters for the tactic are just coming directly from the world. With #775 and #776 we have the ability to update the world-dependent parameters for a tactic outside the play. Use the visitor created in #776 to update the world-dependent parameters for a given tactic independently of the play.

### Acceptance criteria

- [ ] Create some mechanism (likely a function that returns a list by reference) for each play to indicate the tactics it's currently running. Note that the play should be able to change the tactics it's using at any time during the play.
- [ ] Remove all calls to `updateWorldParams` for each tactic in all plays
- [ ] Using the mechanism you created above, have each play indicate the tactics that it's using at any given time
- [ ] Use the visitor created in #776 to update the world params (`updateWorldParams`) for all the tactics that a given play is using **after** the play returns them.

### Blocked By

#775
#776

**Comment by jonathanlew** [comment]
Seems like this is done
