### ISSUE TITLE
Replace existing Visitors with the new templated Visitor

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#780]
### Description of the task

Once #777 is completed we should replace our existing usages of the visitor design pattern with the new templated version.

The classes that will need to be changed are:
1. The `GrsimCommandPrimitiveVisitor`
2. The `IntentVisitor`
3. The `MrfCommandPrimitiveVisitor`
4. The `PrimitiveVisitor`
5. The `ActionVisitor`(if https://github.com/UBC-Thunderbots/Software/issues/773 is merged)
6. The `TacticVisitor` (if https://github.com/UBC-Thunderbots/Software/issues/776 is merged)

### Acceptance criteria

- [ ] Replace all existing instances of the visitor design pattern with the new templated version
- [ ] Make sure all existing tests pass

### Blocked By

#777

**Comment by garethellis0** [comment]
After some research in #777, a templated visitor doesn't appear to bring significant benefit.
