### ISSUE TITLE
Redesign Geometry Utils

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#781]
### Description of the task
Our geometry utilities are currently very fragmented. We should consider rewriting it to be more uniform and cross-compatible. Perhaps backing it with boost geometry stuff is the answer?

Some notes from pre-year planning:
```
More print operators for geometry shapes
Clean up polygon
Enforce that polygon is not crossed over itself in constructor
Maybe not an issues if we use boost
Make rectangle and triangle subclass polygon
Look into replacing all geometry functions with boost implementations
Can we just typedef our types?
Separate Angle and AngularVelocity classes
Separate Point and Vector classes?
Maybe generic shape class?
```

*this issue is to discuss & plan this*

### Acceptance criteria

- [ ] Discuss points in description of this issue
- [ ] File appropriate tickets if we elect to pursue a redesign.

**Comment by jsn0716** [comment]
Now included in #959
