### ISSUE TITLE
Explicitly delete default constructors of classes we don't want to default construct

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#788]
### Description of the task

There are some classes, like `Ball` for example, that we don't want to allow to be default constructed because it's ambiguous and the object has no inherit meaning without constructor parameters (like the initial state of the ball).

For all classes like this, we should make sure we are deleting the default constructor so we can't accidentally default construct anything and force our parameterized constructor to be used.

### Acceptance criteria

- [ ] Delete all default constructors for classes we don't want to default construct

**Comment by jonathanlew** [comment]
Scoped out some work in https://github.com/UBC-Thunderbots/Software/issues/1683
