### ISSUE TITLE
Investigate Alternative Simulators

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#798]
### Description of the task
Grsim has some _serious_ physics issues. For example, we can't seem to tune the physics constants to allow **both** dribbling and chipping/kicking. It's also buggy as all heck. Investigate alternatives!

### Acceptance criteria

- [ ] Investigate alternative to Grsim and doc design / process here
- [ ] Create issues to actually switch away if we decide to, or fix issues with grsim if we decide to stick with it

**Comment by garethellis0** [comment]
Note: this is potentially superceded by #768

**Comment by MathewMacDougall** [comment]
Superceded by #768
