### ISSUE TITLE
Separate the MoveAction into Move, MoveWithAutokick, MoveWithDribble, MoveWithAutochip

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#800]
### Description of the task

Right now the MoveAction has too many flags to indicated if the dribbler or various forms of autokick / chip should be enabled when moving. This makes it hard to read / understand the parameters of the MoveAction at a glance.

We should separate this into several distinctly named Actions, similar to how we separated the generic `KickAction` into a `KickAction` and `ChipAction`.

More planning should be done to create a similar ticket for the equivalent software Primitives. Is it best to tackle these one class at a time, or alltogether?

### Acceptance criteria

- [ ] Create a `MoveAction`
- [ ] Create a `MoveWithAutokickAction`
- [ ] Test the `MoveWithAutokickAction`
- [ ] Create a `MoveWithAutochipAction`
- [ ] Test the `MoveWithAutochipAction`
- [ ] Create a `MoveWithDribbleAction`
- [ ] Test the `MoveWithDribbleAction`

**Comment by jonathanlew** [comment]
completed in https://github.com/UBC-Thunderbots/Software/pull/1871
