### ISSUE TITLE
Make a new mrftest

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#802]
### Description of the task

In order to support MECH and ELEC development, as well as our software / firmware development, we need a new tool that will allow us to control the robots at a low level without needing the AI or vision.

In the past we had an application called `mrftest` that was a simple GUI showing robots state, and allowed for basic control like charging the capacitors, moving individual wheels, or telling the robot to drive in a direction. This was very useful for testing and debugging robots electromechanically.

It will be critical we re-implement a tool like this early this year in order to support development. A more concrete plan and actions items should be made.

### Acceptance criteria

- [ ] Collect desired features from MECH and ELEC
- [ ] Re-implement `mrftest` in some capacity

### Blocked By
#1124

**Comment by jonathanlew** [comment]
Needs to send primitives, too

**Comment by akhilveeraghanta** [comment]
@jonathanlew I think I might have some extra bandwidth this week I can take this on if ur swamped with tickets, it also helps me test that the multicast groups are working and really make everything with proto support is ironed out

**Comment by jonathanlew** [comment]
> @jonathanlew I think I might have some extra bandwidth this week I can take this on if ur swamped with tickets, it also helps me test that the multicast groups are working and really make everything with proto support is ironed out

Go for it if you can!

**Comment by MathewMacDougall** [comment]
Reassigning to Jon since he's currently working on this
