### ISSUE TITLE
Clean Up Obstacle & Robot Obstacle Classes

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#812]
### Description of the task
Cleanup and improve the `Obstacle` and `RobotObstacle` tests. This is a collection of suggested improvements, see "Acceptance Criteria" below. 

Note that this is closely related to #814.

### Acceptance criteria

- [ ] use a factory to create obstacles from Robot, Ball, etc. There should be no need to compile those things in to the obstacle class
- [ ] `RobotObstacle` should extend `Obstacle`
- [ ] `Obstacle` should just extend some sort of shape type (this depends on #781) instead of implementing it's own geometry utils
- [ ] We should remove all "magic" scaling factors from both `Obstacle` and `RobotObstacle` and instead choose values grounded in real-world values.

### Blocked By

#781

**Comment by jonathanlew** [comment]
We should be using sets of obstacles instead of vectors, but we don't support >, ==, <, etc operators

**Comment by garethellis0** [comment]
Sorry, why do we need `<` and `>` for a set? And can we just add `==` operators?

**Comment by jonathanlew** [comment]
Sorry I'm not being precise here. Whatever it is we need to make it a set, we should implement that

**Comment by MathewMacDougall** [comment]
Oh. Usually just a hash function for `unordered_set`, and I think just `<` for `set` (which is implicitly ordered). But yea sounds good.

**Comment by jonathanlew** [comment]
`unordered_set` sounds good, we don't care about any ordering at all (which is why vector makes no sense)

**Comment by garethellis0** [comment]
Ah I see. Thanks for noting that, this discussion will be helpful for whomever takes this issue.

**Comment by jonathanlew** [comment]
>     * use a factory to create obstacles from Robot, Ball, etc. There should be no need to compile those things in to the obstacle class
@garethellis0 Can this factory also create obstacles from motion constraints and cover the work for #1010?

**Comment by garethellis0** [comment]
That seems reasonable to me at first glance.
