### ISSUE TITLE
Ensure All Geom Functions Appropriate Use `const&`

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#813]
### Description of the task
Over the past year we've discovered that several geom functions were taking things by value instead of by const reference. This can result in a significant slowdown, particularly as these functions are called quite often. We should remove all the functions in `geom` to see if they're using `const&`, and if not, change them if they should be.

### Acceptance criteria

- [ ] Review all functions in `software/geom` and change them so they take values by `const&` wherever **safely** possible

**Comment by scveloso** [comment]
> We should remove all the functions in geom to see if they're using const&, and if not, change them if they should be.

Sorry, what does this mean? How will removing functions in geom tell us if they're using const&? Or is this a typo?

**Comment by garethellis0** [comment]
Sorry yup, that's a typo. Should be `We should check all the functions ...`
