### ISSUE TITLE
Simple Navigator (Port over RRT)

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#83]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
As far as I know we don't have a navigator yet. Adding a simple, tested navigator would allow the robot to navigate.
**Describe the solution you'd like**
Port over RRT from old code since RRT has worked for us in the past.
**Describe alternatives you've considered**
A new but simple, local navigator based on bug navigation, immediately jumping to A*.
**Additional context**
This needs to be done quickly so we can navigate sooner than later.

**Comment by MathewMacDougall** [comment]
Bumping as we're blocked by #9 and #21. Should be reasonable to complete in the November milestone, and we'll actually be able to test this.

**Comment by MathewMacDougall** [comment]
Closing as we're not planning to use RRT.
