### ISSUE TITLE
Native macOS Compatibility

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#830]
### Description of the task

Make our AI compile on macOS (tagging @akhilveeraghanta as another person who might be interested in this). I've tried to adapt #760 to build on macOS 10.14.6, but ran into the following issues with external dependencies:

- g3log: for compatibility with macOS system headers Bazel adds `-DDEBUG=1` to its cmdline build parameters, clashing with g3log's own definition of `DEBUG` (see https://github.com/bazelbuild/bazel/issues/3513). An easy fix for this would be to use g3log's `CHANGE_G3LOG_DEBUG_TO_DBUG` option and rename all instances of `DEBUG` in our code to `DBUG`.
- libusb: Preliminary efforts including the sources into our build didn't work. Building libusb relies on ancient autoconf and automake (eugh), so it seems like the best solution is to directly link the libraries installed using apt/homebrew, having `cc_library` options for each platform to be supported; see this http://zacklalanne.me/cross-platform-compile-using-bazel/
- Haven't tried with visualizer yet

Further notes re setup script:
- Needs homebrew to install Bazel, libyaml (?), and python3
- `pip3 install pyyaml`, is this the best idea?

### Acceptance criteria

- [ ] Compiles and runs on macOS 10.14.x

**Comment by akhilveeraghanta** [comment]
This is a lot of effort to undertake, considering that there are only a few people that use MacOS and are getting by with VM's it is not worth pursuing further.
