### ISSUE TITLE
ThreadedObserver should handle locking and data races?

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#831]
### Description of the task

We have had several cases of people forgetting to lock data for a class that inherits from multiple ThreadedObservers. Because it can be sometimes hard to remember this (it's not super obvious it needs to be done), should the ThreadedObserver be responsible for ensuring there are no data races?

### Acceptance criteria

- [ ] Investiate

**Comment by garethellis0** [comment]
This is not technically feasible without significant extra complexity. The threads do not know about each other and there is not general algorithm for arbitrating between threads that satisfies our needs. Discussed with @MathewMacDougall in person.
