### ISSUE TITLE
Investiage init order issue in full_system_main

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#834]
### Description of the task

In 	full_system_main.cpp`, the order in which the `ai` and backend are initialized affect system behaviour. If the `ai` is initialized before we parse the command line args (where the backend is initialized), the system works as expected. However if the `ai` is initialized after the command line args / backend, the system will crash when the AI gets an invalid refbox gamestate.

The refbox gamestate looks like an uninitialized value, so first check it's being initialized properly. Try figure out why this bad value is only gotten in one case vs the other. Ideally the order shouldn't matter

### Acceptance criteria

- [ ] Fix the bug

**Comment by jonathanlew** [comment]
@MathewMacDougall any update?

**Comment by MathewMacDougall** [comment]
Not sure. I seem to recall someone looking into this, not sure if it's still an issue or not. I can take a look later, but won't get to it for at least a few days due to capstone.
