### ISSUE TITLE
Visualizer: Color status messages based on age

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#837]
# Description of the task

The status messages in the Visualizer should be colored to better highlight active messages. Messages that are less than 1 second old should be highlighted in red (or some other bright color).

### Acceptance criteria

- [ ] Highlight all status messages less than 1 second old

**Comment by jonathanlew** [comment]
Following from #931, we want to test 0-sized vectors in drawNavigator

**Comment by jonathanlew** [comment]
This is based on the old visualizer which we plan to replace so closing
