### ISSUE TITLE
Setup Clang-Tidy In Our Repo

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#839]
### Description of the task
`clang-tidy`(https://clang.llvm.org/extra/clang-tidy) is a super useful tool with a variety of linting tools with automatic fixes for some things. It would be super helpful if we could have this perform automatic checks on the codebase (as part of CI) to save reviewers time commenting on little nitty-gritty things (and hopefully make it easier for PR submitters to fix them).

### Acceptance criteria

- [ ] Setup clang-tidy with options that best match our coding conventions
- [ ] Integrate `clang-tidy` into `fix_formatting.sh` or write a separate script for it
- [ ] Made `clang-tidy` a blocking check in CI
- [ ] Fix any `clang-tidy` issues found

**Comment by garethellis0** [comment]
This may by useful: https://github.com/aszinovyev/bazel-compilation-db

**Comment by jonathanlew** [comment]
Can this run when we merge our code into master so PRs don't get failed builds?

**Comment by garethellis0** [comment]
Modifiying code in CI is generally a poor/dangerous idea (consider the case where it changes something in a way you didn't expect, like clang-format truncating block comments). Generally the way I've seen this done is that a clang-tidy check is made part of the pre-commit git hooks so that all commits are checked before they're created on the users machine.

Also, I'm not sure that all clang-tidy errors (like variable naming) can be automatically fixed.

**Comment by jonathanlew** [comment]
pre-commit git hooks super annoying if they take a while to run...

**Comment by garethellis0** [comment]
Yeah, I agree it's not ideal, but making modifications to code that aren't reviewed at all is just a really bad idea. Worst case it's one more commit at the end of a PR.

**Comment by garethellis0** [comment]
This is extremely low priority right now and possibly of minimal benefit. Likely not getting done this year so closing.
