### ISSUE TITLE
Create and Modify tactics so each tactic corresponds one whitelist

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#874]
### Description of the task
The new `MotionConstraint` system requires that each `Tactic` only corresponds to one whitelist. Some `Tactic`s have stages with different whitelists, and they may need to be broken up and the plays adjusted to respect this requirement.
Note that some `Tactic`s have blacklists, all blacklists except BALL should be removed to prepare for #875. This might be tricky. Discuss each case with @jonathanlew, @MathewMacDougall,  @garethellis0 

See more details in #793 and #854

### Acceptance criteria

- [ ] Identify all `Tactic`s that use multiple whitelist and break them up
- [ ] Remove blacklists from tactics other than BALL
- [ ] Adjust the plays to accommodate
- [ ] Testing to ensure nothing is broken

### Blocked By
Migrating tactics from Robocup2019

**Comment by MathewMacDougall** [comment]
I don't totally understand what you mean by each tactic corresponding to one whitelist? Do you just mean each tactic is associated with a different list, since the tactics are independent?

**Comment by MathewMacDougall** [comment]
Also does this ticket include implementing the visitors?

**Comment by jonathanlew** [comment]
> Also does this ticket include implementing the visitors?

Yes, for the new tactics

**Comment by jonathanlew** [comment]
> I don't totally understand what you mean by each tactic corresponding to one whitelist? Do you just mean each tactic is associated with a different list, since the tactics are independent?

Each tactic, no matter its constructor or state or any other internal variable, corresponds to a single whitelist

We might expect that most tactics should share the same whitelist, which is the empty set.

**Comment by garethellis0** [comment]
@jonathanlew - just to make sure I understand this fully:
we've defined a mapping `(GameState, Tactic) -> MotionConstraints`, but there are some cases (like during kickoff) where we have a different set of tactics depending on the play stage we're in?

If that's the case, I'm struggling to think of any examples. In any case I can think of where we would change the `MotionConstraints` on a given tactic, it's because of a `GameState` change. Can you or @MathewMacDougall find any counter-examples?

**Comment by MathewMacDougall** [comment]
@garethellis0 you're specifically looking for (counter)examples where a Tactic would want to change it's whitelist in the middle of execution for a reason unrelated to a `gamestate`?

I have no current counterexamples and we didn't come up with any during our initial meeting. IIRC if we ever came up with a specific case like that, the thing being avoided would be turned into an `Intent` parameter (like we're planning on doing with the ball), or possibly something else if we're way outside the box.

**Comment by jonathanlew** [comment]
@MathewMacDougall @garethellis0 I'd have to look at the migrated tactics to know for sure. The other thing is when plays pass different whitelists into Tactics depending on the Play's state, that that also breask the ` (GameState, Tactic) -> MotionConstraints` mapping. This issue needs to fix those cases too.

**Comment by MathewMacDougall** [comment]
And just to clarify, our solution was to stop Plays passing whitelists into Tactics right?

**Comment by garethellis0** [comment]
Correct, there will only be a `(GameState, Tactic) -> MotionConstraints` mapping now.
