### ISSUE TITLE
Make new PenaltyGoalie Tactic

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#908]
### Description of the task

We made a very hacky PenaltyGoalie at RoboCup but it was very similar to the existing GoalieTactic and wasn't worth porting over. We should plan to make a proper PenaltyGoalie.

This ticket should be scoped and broken down if necessary. Specs for a PenaltyGoalie are needed (Penalty shot vs Penalty shootout?)

### Acceptance criteria

- [ ] TODO

**Comment by jonathanlew** [comment]
pretty sure this is done
