### ISSUE TITLE
Create DirectVelocity Primitive class

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#91]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We need a class in the AI for the DirectVelocity Primitive, so the AI can use it as an output.

**Describe the solution you'd like**
Implement a DirectVelocity Primitive class that extends from the base Primitive class. This will go in the `thunderbots/software/ai/primtiive` folder. See the `move_primitive.*` files for an example.

Make sure to document the spec of the primitive, using the information from #86. This can probably go at the top of the class (in a big javadoc style comment).

**Comment by MathewMacDougall** [comment]
_We're T-7 days to the end of October, so just doing a quick run-through to see if there's anything we can afford to push to an November sprint._

How's progress on this? It should be a bit easier now that #86 is done. Let me know if I can clarify anything.

**Comment by HaomiaoZ** [comment]
Hey Mathew, I do have question about the Direct Velocity Class. For direct velocity class, all we need to do is to create constructors from either thunderbots_msg or some given values and implement all the virtual functions in primitive.h?

**Comment by MathewMacDougall** [comment]
Hey sorry for the late reply. What you said is correct.

**Comment by MathewMacDougall** [comment]
@HaomiaoZ it would be great if you could also add some unit tests for this class as well. That will give us test coverage right away, and is a good introduction to testing in our codebase.

You can use #131 as an example. Sorry for the last minute change.
