### ISSUE TITLE
Create DirectWheels Primitive class

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#92]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We need a class in the AI for the DirectWheels Primitive, so the AI can use it as an output.

**Describe the solution you'd like**
Implement a DirectWheels Primitive class that extends from the base Primitive class. This will go in the `thunderbots/software/ai/primtiive` folder. See the `move_primitive.*` files for an example.

Make sure to document the spec of the primitive, using the information from #86. This can probably go at the top of the class (in a big javadoc style comment).

**Comment by MathewMacDougall** [comment]
_We're T-7 days to the end of October, so just doing a quick run-through to see if there's anything we can afford to push to an November sprint._

How's progress on this? It should be a bit easier now that #86 is done. Let me know if I can clarify anything.

**Comment by MathewMacDougall** [comment]
@SupoWupo it would be great if you could also add some unit tests for this class as well. That will give us test coverage right away, and is a good introduction to testing in our codebase.

You can use #131 as an example. Sorry for the last minute change.

**Comment by MathewMacDougall** [comment]
Bumped this to the December milestone. I'd like to get this done before Christmas. @SupoWupo any updates?

**Comment by roark-z** [comment]
I've created all the primitive classes and I'm working on the unit tests. My finals schedule is kind of unfortunate since I have finals until the 19th. I might be able to work on it but I don't know if I'll have enough time so I'd appreciate some help 👍
