### ISSUE TITLE
Using AI control buttons cause the Visualizer to freeze

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#928]
### Description of the task

When running the AI with the Visualizer, trying to use the AI control buttons like the Play Override cause the Visualizer to freeze.

### Acceptance criteria

- [ ] Fix the bug

**Comment by jonathanlew** [comment]
While grsim is on, clicking any button in the AI tab causes visualizer to freeze. This has happened as far back as 14db1e11c95e0cae7edd751280853fa9387f926e
