### ISSUE TITLE
Geom: Implement geom util functions

### ISSUE THREAD

**Issue by scveloso** [UBC-Thunderbots/Software#959]
### Description of the task
The current geometry utilities are fragmented, so one of the goals is to make them more uniform and cross-compatible. As a part of the geom redesign, implement the currently used geom functions in a util file. Backing this with boost geometry may be the solution.

This issue should also update function names and comments from the old geometry utilities, as some of the function names / comments were found to be either difficult to understand or wrong. Some other clean up actions for the old geom util are included under acceptance criteria as well, as guidelines for designing and implementing new geom util.

Some notes from pre-year planning regarding util redesign:
```
More print operators for geometry shapes
Clean up polygon
Enforce that polygon is not crossed over itself in constructor
Maybe not an issues if we use boost
Make rectangle and triangle subclass polygon
Look into replacing all geometry functions with boost implementations
Can we just typedef our types?
Separate Angle and AngularVelocity classes
Separate Point and Vector classes?
Maybe generic shape class?
```

### Acceptance criteria

- [ ] All old methods that are being used are reimplemented/considered
- [ ] Merge all `*intersect` functions into a set of `intersection` functions, where they just differ by the arguments they take, similar to the `intersects` functions
- [ ] Make sure similar functions are grouped together
- [ ] All `intersect` functions should return an `std::optional` of some type (could be a `std::optional<std::vector<Point>>` or `std::optional<Point>`) so that they can properly indicate if there is an intersection or not
- [ ] Remove all blank lines between `@param`'s
- [ ] Write out the full function names (ie. `distsq` -> `distanceSquared`)

### Blocked By
- #958 
- #957 
- #956

**Comment by jonathanlew** [comment]
@jsn0716 @scveloso Can we include #209, #781, and #398 in the scope of this issue and close the other issues? Can we update the description to include these extra details? @garethellis0 @MathewMacDougall thoughts?

**Comment by garethellis0** [comment]
@jonathanlew - agreed, happy with consolidating all mentioned issues into this one

**Comment by MathewMacDougall** [comment]
Fine with me as long as we don't end up with 1 giant super-PR.

**Comment by garethellis0** [comment]
Yeah, @jsn0716 @scveloso - when you get to this please break it up. There a _many_ single geometry functions that are probably worth an issue on their own!

**Comment by jsn0716** [comment]
Sounds good to me, I'll keep them in this issue for now and once @scveloso and I get to it, we can break it  up into smaller issues as needed
