### ISSUE TITLE
Dependency Injection for DynamicParametersV2

### ISSUE THREAD

**Issue by akhilveeraghanta** [UBC-Thunderbots/Software#960]
### Description of the task

We used to use the Parameter Server which is an xmlrpc database that ROS provided which provided us with storage/access to parameters that could be loaded at runtime. Now that we are on our own system, we are currently in this in-between phase moving from V1 to V2. 

**Some context:** A parameter is a variable that we change dynamically during runtime through the visualizer. A config is a collection of parameters or other configs (configs can be nested). For example you can have an `AIConfig` with a `PassingConfig` and a `DefenseConfig`. Those nested configs can hold other configs or parameters: See this doc for more details, some things have changed since but the gist of it is still captured:
https://docs.google.com/document/d/1MX824V1DC7oCQixdbVqfsLsnR9JzGFPCrLycQDi0uNE/edit

The idea behind DynamicParametersV2 is to inject dependencies into classes when they need them, rather than having them access state globally. See here for more info on dependency injection: https://stackoverflow.com/questions/130794/what-is-dependency-injection

Previously we had all our parameter statically defined in namespaces, for example: 
~~~c++
namespace Util::DynamicParameters {
    RefboxConfig {
        Parameter<int> OverrideRefboxDefendingSide("paramname", 4);
        ...
    }
 ...
}
~~~

The problem with what we had before is that we had no control over accessing/mutating parameters. For example in `goalie_tactic.cpp` you could access `Util::DynamicParameters::RefboxConfig::OverrideDefendingSide.value()` and do some funky stuff. Also plays and tactics could mutate parameters, we had no way of having const correctness (until now)

So now in DynamicParametersV2, each Config is a class and each parameter or nested config is a member of that class.  See `generate_parameters.py` and `config_utils.hpp` for more info. So the above example now looks like this is `network_input.cpp` in the new system.

~~~c++
  // TODO remove as part of https://github.com/UBC-Thunderbots/Software/issues/960
  Util::DynamicParameters->getAIConfig()
                ->getRefboxConfig()
                ->OverrideRefboxDefendingSide()
                ->value()

~~~

This still doesn't solve the previously mentioned problem, as we are still accessing parameters globally. This is where this ticket comes in! With dependency injection the class using these parameters in `network_input.cpp`, should get a `shared_ptr` to `RefboxConfig` in its constructor and only access those parameters. This will facilitate testing, and make it super explicit as to what parameters are being used in that class. Additionally, using `const_pointer_cast`, we are able to enforce that no play or tactic can ever call a `getMutable` accessor and change the values. 

### Acceptance criteria

- [ ] Create a mutable and immutable DynamicParameter object in `full_system.cpp`. See `config_test.cpp` to see how it is created there.
- [ ] Inject those dependencies into Plays, Tactics and anything else that uses DynamicParameters
- [ ] Ensure `const` correctness, make sure that all plays/tactics get immutable configs (using `const_pointer_cast`) and the visualizer gets a regular shared ptr, where it can use the `getMutable` accessors. 
- [ ] Delete `dynamic_parameters.h` and make sure parameters are not accessed globally.
- [ ] TODO

### Blocked By
#966

**Comment by garethellis0** [comment]
@akhilveeraghanta - are you working on this right now? If so could you assign yourself?

**Comment by akhilveeraghanta** [comment]
This ticket will change quite a bit due to the new design, so we can safely close this
