### ISSUE TITLE
Visualizer: Enable drawNavigator to draw a Path

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#965]
### Description of the task
drawNavigator should draw a vector of `Path`s contained in planned_paths, instead of vector of Points, so planned_paths in Navigator needs to change, as well

Path used to be an std::vector of Point, but to support the potential for Spline Navigator, we made Path = Spline. To make the new Path backwards compatible with the visualizer, Navigator uses getKnots to get the same std::vector of Point. However, Path can be a curvy spline, ie points not interpolated with straight lines. We want to be able to visualize splines fully.

Look at src/software/gui/drawing/navigator.h and src/software/gui/drawing/navigator.cpp

### Acceptance criteria

- [ ] Change planned_paths to vector of `Path`s
- [ ] Make drawNavigator draw the planned_paths
- [ ] Testing

### Blocked By
#945

**Comment by phelanm20** [comment]
@jonathanlew could you add some more detail to this ticket? Thank you!

**Comment by jonathanlew** [comment]
> @jonathanlew could you add some more detail to this ticket? Thank you!

Done!

**Comment by jonathanlew** [comment]
Looks like this has already been implemented
