### ISSUE TITLE
STP: General Cleanup List

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#968]
### Description of the task

A superticket of things to review, cleanup, or change (likely around Jan/Feb 2020). These items should be broken down into their own tickets.
* Either remove Actions / Intent / Primitives that we currently don't use, or refactor them so they are useful. This depends on firmware.
* The `isApplicable` and `invariantHolds` functions for plays don't use their member variables, so maybe can be made static?
* Make a `behindBall` function since we do that so much

### Acceptance criteria

- [ ] Break the items down into tickets

**Comment by jonathanlew** [comment]
Made #1733 and couldn't come up with any other tickets
