### ISSUE TITLE
Make GrSim-Visualizer Run Offline

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#982]
### Description of the task
Currently, GrSim uses UDP to communicate with visualizer and it uses some sort of wifi/ethernet port of our computers to do that. This means that if we aren't connected to wifi/ethernet, then GrSim cannot communicate with visualizer and it also crashes because it can't find a port, I guess.

This was an issue in Robocup 2019 because we wanted to test plays/tactics on grsim/visualizer on the plane ride over to Sydney.

### Acceptance criteria

- [ ] Make GrSim Visualizer Run Offline

**Comment by MathewMacDougall** [comment]
Don't think this is a high priority, but should be easy to at least determine if it's possible or not.

@jonathanlew when you mean offline, you mean just not connected to a network? Or your local interfaces disabled / completely turned off?

@akhilveeraghanta is it possible for local multicast to work while not connected to an external network? Would you just need to specify loopback?

**Comment by jonathanlew** [comment]
@MathewMacDougall Will the new simulator be able to work offline? (i.e. not connected to a wifi/ethernet, but local interfaces on)

**Comment by MathewMacDougall** [comment]
AFAIK yes, but lets leave this open as a reminder until then.
